### ISSUE TITLE
how does SEPARABLE work?

### ISSUE THREAD

**Issue by ghost** [kaskr/adcomp#10]
Hi all,

I am posting here so that any response can be archived.  Please write directly for model-details if my description is not sufficient.

I am working on a spatiotemporal model, which could be "separable", i.e., N(t+1) is independent of N(t-1) conditional on fixed N(t).  So, e.g., in ADMB-RE it would be computationally superior to specify N as random, rather than specifying "innovations" in the transition Epsilon as random (because Epsilon is not separable).

I understand that TMB "automatically" detects sparseness in the random effects (maybe I'm wrong).  I also know that TMB has a SEPARABLE() command that exists when specifying priors on random fields, AR processes, etc., and a GMRF() command that exists for spatial fields.

So:
1.  What does SEPARABLE() do?
2.  Is it still true that its better (for speed and/or memory) to specify models by specifying states as random rather than innovations?
3.  If specifying via states, you have to calculate the "implied" innovation term, which is then penalized.  Can this implied innovation (a matrix<Type> object) then be put into the GMRF() call?  

And, as always, thanks for the amazing software and statistical improvements!

jim

**Comment by PunamA** [comment]
Hi, 
Thank you for this thread. I'm a new user with TMB and have no prior background in c++. 
I've built (i hope) a spatio-temporal model for looking at the incidence of malaria. I have used the SEPARABLE() function for my ST effects, however, i'm questioning whether or not the assumption of separability is appropriate in my setting. My question is two fold:

1) if there is anyone out there that is a TMB expert with knowledge of ST models, how would one test for separability within a TMB model? can this be done?
2) If not, how would one report out the kronecker product, My hope is that i can used alternative R-packages to test for separability (for example "covatest"). Or it might be useful to simply see what the kronecker product looks like as an output.

below is the .cpp file i've created. It has two models (an incidence ST model using negative binomial and a seroprevalence model using a logit link). As mentioned above, i'm particularly looking at reporting the kronecker product out from the SEPARABLE() function in my full model.

#include <TMB.hpp>
#include <math.h>
#include <stdio.h>

//define container for list of matrices - LOM type
template <class Type>
struct LOM_t : vector<matrix<Type> > {
  //constructor
  LOM_t(SEXP x){ /*x is list from R*/
    (*this).resize(LENGTH(x)); /*resize pointer to be the right size*/
    for(int i=0; i<LENGTH(x); i++){ 
      SEXP m = VECTOR_ELT(x, i); /*get ith element of list */
      (*this)(i) = asMatrix<Type>(m); /*put it as ith element*/
    }
  }
};


template<class Type>
Type objective_function<Type>::operator() ()
{
  using namespace R_inla;
  using namespace density;
  using namespace Eigen;
  //We are fitting the simple incidence and sero prevalence model here
 
  // Input Data
  
  DATA_INTEGER(bigN);
  DATA_INTEGER(timeN);
  DATA_MATRIX(case_matrix); //the data bigN by month
  DATA_STRUCT(covariates, LOM_t);  //just transpose this (bigN x 12 by covs)
  DATA_VECTOR(population);  //should be same size as bigN
  DATA_STRUCT(spde,spde_t);
  DATA_MATRIX(A); //bigN by mesh nodes
  DATA_VECTOR(sero_pos); //seropositivity data
  DATA_VECTOR(sero_neg); // seronegativity data
    
  // Parameters
  
  PARAMETER(mean_log_incidence);  //keep as one single values - intercept (fixed)
  PARAMETER(log_sd_incidence_baseline);
  PARAMETER(log_range_incidence_baseline);
  PARAMETER_VECTOR(slopes);  //try define as matrix
  PARAMETER_ARRAY(incidence_baseline);   // is number of mesh nodes by month (should be a parameter array)
  PARAMETER(lognbinomfactor);
  
  PARAMETER(mean_log_sero);  //keep as one single values
  PARAMETER(log_sd_sero_baseline);
  PARAMETER(log_range_sero_baseline);
  PARAMETER(slope_sero);  //single value
  PARAMETER_VECTOR(sero_baseline);   // is number of mesh nodes
  
  //temporal params
  PARAMETER(logit_ar_phi);
  PARAMETER(log_ar_scale);  
  
  // Parameter Transforms
  
  Type range_incidence_baseline = exp(log_range_incidence_baseline);
  Type kappa_incidence_baseline = 2.8284/range_incidence_baseline;
  Type sd_incidence_baseline = exp(log_sd_incidence_baseline);
  Type nbinomfactor = exp(lognbinomfactor);
  
  Type range_sero_baseline = exp(log_range_sero_baseline);
  Type kappa_sero_baseline = 2.8284/range_sero_baseline;
  Type sd_sero_baseline = exp(log_sd_sero_baseline);
  
  Type ar_phi = invlogit(logit_ar_phi);
  Type ar_scale = exp(log_ar_scale);
  
  
  // Priors
  
  Type nll = 0.0;
  
  nll -= dnorm(log_sd_incidence_baseline,Type(-1),Type(1),true);   //these are specifically chosen for national haiti scale, think of better ones later
  nll -= dnorm(log_range_incidence_baseline,Type(1.5),Type(1),true);
  SparseMatrix<Type> Q_incidence_baseline = Q_spde(spde,kappa_incidence_baseline);
  nll += SEPARABLE(SCALE(AR1(ar_phi), ar_scale), SCALE(GMRF(Q_incidence_baseline),sd_incidence_baseline))(incidence_baseline); //space time random field component
  
  
  nll -= (dnorm(slopes,Type(0.0), Type(1.0),true)).sum();
  nll -= dnorm(lognbinomfactor,Type(-1.0), Type(1.0),true);
  
  nll -= dnorm(log_sd_sero_baseline,Type(-1),Type(1),true);   //these are specifically chosen for national haiti scale, think of better ones later
  nll -= dnorm(log_range_sero_baseline,Type(1.5),Type(1),true);
  SparseMatrix<Type> Q_sero_baseline = Q_spde(spde,kappa_sero_baseline);
  nll += SCALE(GMRF(Q_sero_baseline),sd_sero_baseline)(sero_baseline);
  
  nll -= (dnorm(slope_sero,Type(0.0), Type(1.0),true));
  
  nll -= dnorm(logit_ar_phi, Type(3.0), Type(0.5), true);
  nll -= dnorm(log_ar_scale, Type(0.0), Type(1.0), true);
  
  // Algebra
  
  matrix<Type> baseline_field =  A*incidence_baseline.matrix(); //add the random field
  
  matrix<Type> lin_pred;
  
  for (int j=0; j<timeN; j++ ) {  //adding in the covariates by slopes
    lin_pred = covariates(j)*slopes;
    baseline_field.col(j)=baseline_field.col(j).array()+lin_pred.array();
  }
  
  baseline_field=baseline_field.array()+mean_log_incidence;
  
  vector<Type> log_incidence = baseline_field.rowwise().mean();
  
  vector<Type> sero_baseline_field = log_incidence*slope_sero + A*sero_baseline;
  
  for(int j=0; j<bigN; j++) {
    sero_baseline_field[j]+= mean_log_sero;
  }
  vector <Type> inv_logit_sero = invlogit(sero_baseline_field);
  
  // std::cout << baseline_field.col(0).size() << '\n';
  // std::cout << baseline_field.row(0).size() << '\n';
  // std::cout << lin_pred.size() << '\n';
  
  
  // Likelihood 
  
  for (int j=0; j<bigN; j++) {
    for (int i=0; i<timeN; i++) {
      
      nll -= dnbinom2(case_matrix(j,i),exp(baseline_field(j,i))*population[j],exp(baseline_field(j,i))*population[j]*nbinomfactor,true);  //if nbinomfactor > 1 it is overdispersed
      
    }
  }
  
  for (int i=0; i<bigN; i++) {
    nll -= sero_neg[i]*log(Type(1.0)-inv_logit_sero(i)) + sero_pos[i]*log(inv_logit_sero(i));
  }
  
  
  // Reporting
  
  REPORT(baseline_field);  //returns logged outputs
  REPORT(sero_baseline_field); 
  REPORT(inv_logit_sero);  //returns logged outputs
  
  return nll;
}


Punam
