### ISSUE TITLE
undefined symbol: dpotri_

### ISSUE THREAD

**Issue by johnrsibert** [kaskr/adcomp#101]
Having trouble installing TMB on a new(ish) computer, linux mint 17.1. Needed to use sumbolic links for lapack:
liblapack.a -> liblapacke.a
liblapacke.so.3 -> liblapacke.so.3.0
Which seemed to work. Then this occurred:

make[1]: Leaving directory `/tmp/RtmpFKob3H/R.INSTALL605b4d43b0bd/TMB/src'
installing to /home/jsibert/R/x86_64-pc-linux-gnu-library/3.0/TMB/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : .onLoad failed in loadNamespace() for 'TMB', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/home/jsibert/R/x86_64-pc-linux-gnu-library/3.0/TMB/libs/TMB.so':
  /home/jsibert/R/x86_64-pc-linux-gnu-library/3.0/TMB/libs/TMB.so: undefined symbol: dpotri_
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/jsibert/R/x86_64-pc-linux-gnu-library/3.0/TMB’
make: *** [install] Error 1

**Comment by kaskr** [comment]
If you need to manually create symbolic links to you libraries then it sounds like a broken R installation to me. Can you install other R packages that link to lapack such as ```install.packages("Matrix")``` ?

**Comment by johnrsibert** [comment]
Broken R installation was the problem. Thanks.

deb packages are sometimes suck. I installed R 3.2.1 from source, and all was fine.
