### ISSUE TITLE
install.packages for TMB Modelbuilder

### ISSUE THREAD

**Issue by FisherBob** [kaskr/adcomp#103]
When I ran install.packages("") [that is 2 double quotes) I got this error message:  package '' [that is a leading single quote and a terminal single quote] is not available (for R version 3.2.0). 
This is for a Mac system.

What should I do now?

**Comment by bbolker** [comment]
You could try installing any old package, e.g. `install.packages("bbmle")`

**Comment by FisherBob** [comment]
Thank you for the suggestion. I will give it a try.
