### ISSUE TITLE
Rtools version for development

### ISSUE THREAD

**Issue by colemonnahan** [kaskr/adcomp#104]
I'm trying to add some MCMC functionality to TMB. For other packages I've used `devtools::install` to test local changes and then pushed to github. However, the version of Rtools TMB uses (3.1) is incompatible with the latest version of  `devtools` and R, which wants to use Rtools 3.3.

What is the version of Rtools people are using? Or is there a better development workflow I should be using?

**Comment by kaskr** [comment]
TMB is not tied to any particular Rtools version (even though ```install.windows.R``` will grab Rtools31 by default). If you want to use Rtools33 then just install it manually and run ```source("install.windows.R")```.

**Comment by colemonnahan** [comment]
I switched to Rtools 3.3. The `make clean` and `make` tests run fine, but when I try `devtools::load_all` I get the error:

````
> devtools::load_all("c:/Users/Cole/adcomp/TMB")
Loading TMB
Loading required package: Matrix
Loading required package: TMB
Building example simple 
Note: Using Makevars in C:\Users\Cole\Dropbox\emacs-lisp/.R/Makevars 
g++ -m64 -I"c:/PROGRA~1/R/R-32~1.0/include" -DNDEBUG -I -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple     -I"d:/RCompile/r-compiling/local/local320/include"     -O2  -mtune=core2 -c simple.cpp -o simple.o
simple.cpp:2:19: fatal error: TMB.hpp: No such file or directory
compilation terminated.
make: *** [simple.o] Error 1
Error in compile(paste0(name, ".cpp"), ...) (from TMB.R#924) : Compilation failed
In addition: Warning message:
running command 'make -f "c:/PROGRA~1/R/R-32~1.0/etc/x64/Makeconf" -f "c:/PROGRA~1/R/R-32~1.0/share/make/winshlib.mk" -f "C:\Users\Cole\AppData\Local\Temp\RtmpYr9pQo\fileb6c415473" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="simple.dll" WIN=64 TCLBIN=64 OBJECTS="simple.o"' had status 2 
Timing stopped at: 0.02 0 0.06 
````

It's strange to me that `TMB` is a required package to install `TMB`. I get the same error with `devtools::document`, but `runExampe('simple')` works fine.

Should I just abandon `devtools` for this package? I really just want to be able to update the man files. What do you do for workflow?

**Comment by kaskr** [comment]
To update the man files run ```make doc-update``` from the adcomp folder. ```devtools``` is not needed.

**Comment by EllenY** [comment]
I am getting a similar error message. How would I run "make doc-update" from the adcomp folder?
