### ISSUE TITLE
Working with Arrays

### ISSUE THREAD

**Issue by Njoselson** [kaskr/adcomp#109]
Is there a TMB equivalent for the ADMB ability to extract vectors and matrices from arrays. 

If array1 was a 5d array in ADMB, then ```array1(1,1,1)``` would give a matrix of the last two dimensions.

I am trying to convert the following code from ADMB to TMB:
```
dvar5_array Wspwa(1,10,1,2,1,2,1917,2029,0,15); 
dvar4_array SCl(1,6,1,2,1917,2030,1,105);
dvar_matrix PPMmy(1,105,0,15);
3darray WAL(1,2,1,2,1,105);

for(y=1917;y<=2029;y++)
  {
   for (f=1;f<=6;f++)
   {
    Wspwa(f,1,1,y) = elem_div(trans(PPMmy)*(elem_prod(SCl(f,1,y),WAL(1,1))),trans(PPMmy)*SCl(f,1,y));
   }
  }
```
The same procedure goes for filling in all of the ```Wspwa()``` elements.

Because I don't know a TMB equivalent for extracting a vector of values from an array, I have been letting
```
for (l=1;l<=105;l++)//1,105
	{ vec1(l)=SCl(f,1,y,l); }
```
Replace ```SCl(f,1,y)``` But this is extremely inefficient, and the entire recoding of that section:
```
for(y=1917;y<=2029;y++)//2029
  {
   for (f=1;f<=6;f++)//1,6
   {
	for (l=1;l<=105;l++)//1,105
	{ vec1(l)=SCl(f,1,y,l);
      vec2(l)=WAL(1,1,l);
	  vec3=vec1;
	  vec4=vec2*vec3;
	  mat1=PPMmy.transpose();
	  ans1=mat1*vec1;
	  mat2=mat1;
	  ans2=mat2*vec4;
	  ans3=ans2/ans1;
	 for (a=0;a<=15;a++)
	 { Wspwa(f,1,1,y,a)=ans3(a);}
	}
   }
  }
```
 Causes TMB to give a memory allocation error when I run the ```MakeADFun()```

I know that ```array.col(0)``` extracts a slice of the last dimension of the array, but I couldn't find a way for this to help me. 

Is there a possibility of more efficient coding in TMB?

Thanks,

Nathaniel

**Comment by Njoselson** [comment]
In short, is there support for R-style syntax: ```array[,,1,1]``` for example?

**Comment by colemonnahan** [comment]
Hi @Njoselson, I ran across this file which has some helpful examples of how to index:

https://github.com/kaskr/adcomp/blob/b2ef084796a5635e2da7690de9d5972e441869ce/tmb_syntax/matrix_arrays.cpp

**Comment by Njoselson** [comment]
Thanks,

This file, though, only shows capabilities for up to 2 dimensional arrays. I guess Eigen isn't designed for 6 and 7d arrays, so their coefficient wise and and matrix functionality is less useful.

None of the examples show manipulations of large multi-d arrays, so I will assume that it is designed for less complex manipulation. This to me seems a large failing in regards to data heavy projects. 

Nate
