### ISSUE TITLE
Compilation errors on new PC

### ISSUE THREAD

**Issue by colemonnahan** [kaskr/adcomp#117]
When I started using TMB I ran the `install_windows` script and all was good. Then I've been reinstalling locally via `make install` and that also has been working.

However, that PC died today and so I'm starting on a new machine (Win8 64bit) and having all sorts of issues getting TMB to work. When I run the installation script I get this:

````
make build-package
make: uname: Command not found
make[1]: Entering directory `/cygdrive/c/Users/Cole/adcomp'
R CMD build --resave-data=no TMB
make[1]: uname: Command not found
* checking for file 'TMB/DESCRIPTION' ... OK
<truncated>...
````
Is that error regarding `uname` normal? The package seems to install fine. Now when I go to run an example I get this:
````
> runExample('simple')
Building example simple 
Note: Using Makevars in C:\Users\Cole\Dropbox\emacs-lisp/.R/Makevars 
g++ -m32 -I"c:/PROGRA~1/R/R-32~1.2/include" -DNDEBUG -IC:/Users/Cole/Rlibs/TMB/include -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_simple     -I"d:/RCompile/r-compiling/local/local320/include"     -O2  -mtune=core2 -c simple.cpp -o simple.o
In file included from C:/Users/Cole/Rlibs/TMB/include/cppad/local/recorder.hpp:15:0,
                 from C:/Users/Cole/Rlibs/TMB/include/cppad/local/ad.hpp:22,
                 from C:/Users/Cole/Rlibs/TMB/include/cppad/cppad.hpp:78,
                 from C:/Users/Cole/Rlibs/TMB/include/TMB.hpp:29,
                 from simple.cpp:2:
C:/Users/Cole/Rlibs/TMB/include/cppad/local/pod_vector.hpp:58:25: error: redefinition of 'bool CppAD::is_pod() [with Type = unsigned int]'
C:/Users/Cole/Rlibs/TMB/include/cppad/local/pod_vector.hpp:56:25: error: 'bool CppAD::is_pod() [with Type = unsigned int]' previously declared here
make: *** [simple.o] Error 1
Error in compile(paste0(name, ".cpp"), ...) : Compilation failed
In addition: Warning message:
running command 'make -f "c:/PROGRA~1/R/R-32~1.2/etc/i386/Makeconf" -f "c:/PROGRA~1/R/R-32~1.2/share/make/winshlib.mk" -f "C:\Users\Cole\AppData\Local\Temp\Rtmp4cs7Vy\file14144907427a" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="simple.dll" OBJECTS="simple.o"' had status 2 
Timing stopped at: 0.01 0.01 9.79 
````
I have Rtools version 3.2 and R 3.2.2. I tried a handful of combinations of previous versions of R and Rtools but nothing seem to make a difference. I cleared my PATH variable of all things Rtools and ADMB and then `library(TMB)` tacked on these:
`C:/Rtools/bin;C:/Rtools/gcc-4.6.3/bin64;C:/Rtools/gcc-4.6.3/bin;c:/PROGRA~1/R/R-32~1.2/bin/i386`
Which seems to be right and indeed when I check in R I get what seems to make sense:
````
> shell('where make')
C:\Rtools\bin\make.exe
> shell('where g++')
C:\Rtools\gcc-4.6.3\bin\g++.exe
> shell('where R')
c:\Program Files\R\R-3.2.2\bin\i386\R.exe
````
At this point I'm stuck and hoping someone can help decipher the error messages.

**Comment by kaskr** [comment]
The error
```
C:/Users/Cole/Rlibs/TMB/include/cppad/local/pod_vector.hpp:58:25: error: redefinition of 'bool CppAD::is_pod() [with Type = unsigned int]'
C:/Users/Cole/Rlibs/TMB/include/cppad/local/pod_vector.hpp:56:25: error: 'bool CppAD::is_pod() [with Type = unsigned int]' previously declared here
```
occurs on systems for which the types ```size_t``` and ```unsigned int``` are the same. This seems to be the case on 32 bit. Could you try to run the 64 bit version of R instead ?

**Comment by colemonnahan** [comment]
@kaskr Yes this fixed the issue. Thank you!

On Windows the default option for installing R is to install both 32 and 64 bit files. Somehow my PC was not recognizing that the 64 bit binaries were the ones to use.

If anyone else has this problem, I fixed it simply by reinstalling R and unchecking the 32 bit files during the installation. Also check your PATH variable to see if it is pointing to the wrong binaries. In my previous post you can see the issue:

````
> shell('where R')
c:\Program Files\R\R-3.2.2\bin\i386\R.exe
````
which should be
````
> shell('where R')
c:\Program Files\R\R-3.2.2\bin\x64\R.exe
````
All is working fine now.
