### ISSUE TITLE
No ';' after REPORT()

### ISSUE THREAD

**Issue by bchasco** [kaskr/adcomp#119]
I found, on accident, that not including a semicolon after REPORT() does not cause an error when compiling.  And optim doesn't crash when I pass the dll.  I don't know if this is something that could cause problems later on so I thought I pass it along.  I know for some reason they're not always needed (e.g. REPORT() in TMB apparently, and INITIALIZATION_SECTION of ADMB).

**Comment by the-sushi** [comment]
Yes, this is how C/C++ macros tend to work.
