### ISSUE TITLE
two windows parallelization issues

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#122]
hi all,

I found the following two minor issues with parallelization in windows.  I leave it to the developers to decide if these matter, but note them here where they're searchable:
1.  calling REPORT() on the objective function accumulator causes the compilation of the CPP file to fail (this is sometimes useful for bookkeeping and debugging)
2.  initializing the accumulator function at a fixed value (i.e., 0) causes a crash (I generally initialize prior to using += etc., to avoid having issues with un-initialized variables)

Both issues can be seen by uncommenting lines in the modified version of the "spatial_gompertz_parallel.cpp" example below.

cheers,
jim
# include <TMB.hpp>

template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_VECTOR(Y);
  DATA_VECTOR(x);
  PARAMETER(a);
  PARAMETER(b);
  PARAMETER(logSigma);
  parallel_accumulator<Type> nll(this);
  //nll = 0;
  for(int i=0;i<x.size();i++)nll-=dnorm(Y[i],a+b*x[i],exp(logSigma),true);
  //REPORT( nll );
  return nll;
}

**Comment by James-Thorson** [comment]
Hi all,

First off, thank you Kasper for responding to my previous post in the thread!

I am again trying to explore parallelization as a way to increase speed in big spatiotemporal models.  I have two windows machines, and both have errors I cannot diagnose using the linreg_parallel example, where I have slightly modified the R script calling the template script (https://github.com/James-Thorson/TMB_experiments/tree/master/experiment_with_parallel_accumulator):

1.  One machine throws the following error:

> ben <- benchmark(obj,n=100,cores=1:4)
Error in openmp(nc) : Openmp not supported.

2.  The other machine definitely runs in parallel (I can see the increased processor use on my system monitor), but gets no real speed benefit as measured using the benchmarking function ben().

![benchmark](https://cloud.githubusercontent.com/assets/7989837/11378743/96a642ba-92a1-11e5-8065-9c0e11de55b0.png)

Does anyone have another simple, self-contained script that uses parallelization that they could share with me, for me to test parallel options on my machines?  I am also failing to see any improvement using a simple spatiotemporal ("spatial Gompertz") model, here:

https://github.com/James-Thorson/mixed-effects/tree/master/spatial_Gompertz_model

cheers,
jim

**Comment by kaskr** [comment]
Some general advice wrt. parallelization:

* Windows not recommended. The toolchain (Rtools) seems to be only
  partly functional. It is not currently possible to change the number
  of threads at runtime. So what you see on the benchmark graph is the
  timings from a fixed configuration of cores (i.e. just noise).

* The right strategy for improving speed is to find out what category
  your model belongs to (see http://arxiv.org/pdf/1509.00660v1.pdf
  Table 5).

* Example 1: Look at 'tmb_examples/transform.cpp'. The majority of
  time spent doing AD calulations. In this case parallel_acumulator is
  the right approach - see 'tmb_examples/transform_parallel.cpp'.

* Example 2: 'tmb_examples/ar1_4D.cpp'. The majority of time spent
  outside the AD libraries which is typical for spatio-temporal
  models. In this case the right approach is to customize your
  R-installation and the TMB-installation:
  - Install tuned BLAS with you R (MKL recommended).
  - Install TMB with full suite of ordering algorithms (see README).

  NOTE: When setup correctly you can run this example in less than 10
  seconds.

**Comment by skaug** [comment]
I have tried to install MKL from https://mran.revolutionanalytics.com
under Windows 7 with  R version 3.2.2 (2015-08-14)

This gives a  substantial speedup on pure matrix multiplication.
Without MKL
>  m<-diag(1000)+1
>  system.time(m%*%m)
   user  system elapsed 
   0.73    0.00    0.74 

With MKL

> m<-diag(1000)+1
> system.time(m%*%m)
   user  system elapsed 
   0.12    0.00    0.03 

However, I do not get any speedup on tmb_examples/ar1_4D.cpp.
Runtime is 50 seconds (+compilation), but of course
I do not use ordering (Metis).

Hans

**Comment by kaskr** [comment]
@skaug 
Tried the same thing on Windows (VM). It seemed to work fine for
ar1_4D.  Just a guess: Maybe your Matrix or TMB package is linking to
the old BLAS.  Could be you have an old version of Matrix in your
local package folder?  Or, maybe you forgot to re-build TMB using the
new R? During package build pay attention to all '-I' and '-L'. Should
only point to new paths.

**Comment by skaug** [comment]
Thanks. It turns out that my timing was wrong, and that I indeed get a 
substantial speedup by using MKL, as explained below: 

I think the installation is correct, but it seems that I had mis-interperated
the output of system time(). An external stop-watch confirms that with MKL
"ar1_4D" is running 3 times faster. The timing output from R is:

with MKL:
   user  system elapsed 
  49.31    7.49   15.51 

without MKL:
   user  system elapsed 
  49.20    1.94   51.34 

My stopwatch corresponds closely to "elapsed". I am not
sure how to interpret "user" in this case.

**Comment by bbolker** [comment]
I think "user" might be *total* CPU time used, i.e. if the system is simultaneously using 3 cores to do the computation, then "user" time will advance 3x faster than wall-clock/stopwatch time ...

**Comment by James-Thorson** [comment]
Thanks Hans, Kasper, and Ben!

I have confirmed that using Revolution R Open and the MKL library worked
using my work machine running windows, and sped up both the ar1_4D, and my
"geostatistical" delta-GLMM example for eastern Being Sea pollock.  Using 4
cores, it appeared to cut the time to 40% of the time without
parallelization, and it appears to have little impact of memory
requirements.  Anyway, this should be very useful!

jim
