### ISSUE TITLE
sort() or cumsum() function?

### ISSUE THREAD

**Issue by genwei007** [kaskr/adcomp#129]
Hi,

Is there any built-in function like sort() and cumsum() (similar in MATLAB) for PARAMETER_VECTOR and PARAMETER_MATRIX? I only found there is a index_sort.hpp, but hard to know how to use empirically... because of my limited c++ knowledge. Any example to implement? Thanks.

**Comment by skaug** [comment]
Hi,

I do not think you should use sort() on a parameter vector, as
it can lead to non-differential objective function (same as with if-statements).

Hans

**Comment by genwei007** [comment]
Hi skaug,

You are right! I also found this problem when I am trying something like to order the parameters. But the ordered parameters is a model constraint. Does it mean I have to use some R package allowing unequal constraints, rather than doing it in the TMB template?

**Comment by skaug** [comment]
No, reparameterize your model in the TMB template such that the
new parameters have box constraints.

**Comment by genwei007** [comment]
Thank you for the suggestoin, Hans.
