### ISSUE TITLE
Cannot work when PARAMETER_MATRIX * random effect

### ISSUE THREAD

**Issue by cwliu007** [kaskr/adcomp#131]
Hi TMB developers, 
I ran into problem that the parameters (PARAMETER_MATRIX) cannot be estimated when they multiply a random effect. Could you have a look? An example is as follows:   (Attached files: https://srv01.bitsend.jp/download/65d4dfbecd6924314ab700ce5852adc6.html )

```
  for(n=0;n<4000;n++){
      f -= dnorm(GAMMA[n],Type(0),Type(1),true); // random effect
      for(e=0;e<3;e++){
          for(k=0;k<1;k++){
              nu2(k) = exp(lambda(k,e)*GAMMA(n) + loc(k,e));          
          }
          nu2(1) = Type(1);
          Type de = sum(nu2);
          for(k=0;k<(2);k++){nrm(k,e) = nu2(k)/de;}
          f -= log(nrm(Integer(Selection(n,e)-Type(1)),e));
      }  
  }
```

The lambda and GAMMA cannot be estimated. No idea how the TMB works behind the scene. Thanks.

**Comment by skaug** [comment]
The model is most likely over parameterized. You can use the "map"
argument of MakeADFun() to turn off parameter until the model
behaves well, and in that way get insight into what the problem is.

**Comment by genwei007** [comment]
Yes, that is why I treat gamma as ramdom effect and integrated out. Some R packages can estimate the model by EM with integrating gamma. So I think turning off parameter should be not necessay.  For testing, I found, when setting lambda as scalar parameter, it can be estimated. But not lucky when setting lambda as PARAMETER_MATRIX. The problem may arise accessing its elements by lambda(k,e)?

**Comment by genwei007** [comment]
To follow up, the model in discussion is nominal response model (see http://srmo.sagepub.com/view/polytomous-item-response-theory-models/n2.xml). The data are on ordinal scale.

I temporally set the three 'lambda' by 'PARAMETER(lam1); PARAMETER(lam2); PARAMETER(lam3);'. As a result, TMB can get estimates of the three 'lambda'. (Using PARAMETER_MATRIX will NOT give any estimates)

Then, another question arised. For testing estimation stability, I simulated 20,000 * 3 large samples (true value: lambda=1, loc= -1) and estimated parameters by TMB and Mplus software (which has stability in estimating the model), and do a rough comparison. The Mplus (using EM with Gauss-Hermite quadrature) gave
~~~
lam1   lam2   lam3   loc1   loc2     loc3 	
1.009  1.035  0.984  -1.013  -1.012  -0.985
~~~
and TMB (using Laplace approximation) gave
~~~
lam1   lam2   lam3   loc1   loc2   loc3 	
0.888  0.842  0.888 -0.950 -0.966 -0.972 
~~~
It seems TMB underestimated the 'lambda'.

And, adding importance sampler: 'MCcontrol = list(doMC = TRUE, seed = 123, n = 100)' in TMB, it gave
~~~
lam1   lam2   lam3   loc1   loc2   loc3 	
1.087  0.869 1.097 -1.014 -0.979 -1.034
~~~
and 'n = 500' gave
~~~
lam1   lam2   lam3   loc1   loc2   loc3 	
0.977  0.918  0.998 -0.981 -0.995 -1.011 
~~~
and 'n = 1000' gave
~~~
lam1   lam2   lam3   loc1   loc2   loc3 	
0.963  0.950  0.905 -0.977 -1.004 -0.982
~~~

It appeared that using Laplace approximation with importance sampler is better for discrete data. I also found some discussions on this:
https://groups.google.com/forum/#!topic/admb-users/7RltSt9Pm1A
http://tinyurl.com/qz68fyv (see Page 34) 
http://arxiv.org/pdf/1105.1684.pdf

My question is: (1) what is the optimal number of samples 'n' in TMB? (2) does TMB have Gauss-Hermite quadrature? Thanks!

**Comment by skaug** [comment]
(1) If you only consider approximation error, the larger n the better.? (2) TMB does
not have Gauss-Hermite quadrature.

**Comment by kaskr** [comment]
A few additional comments:
- The matrix version works fine, just don't start the optimization in lambda=0 where the gradient is 0 :)
- An alternative to Gauss quadrature is to use Romberg integration ```CppAD::RombergOne``` (but there are not yet any worked out examples)

**Comment by genwei007** [comment]
Thanks for comments. Now it works well. I just checked the Romberg method in CppAD document. So, it seems I have to either (1) replace the Laplace in the internal code or (2) treat random effect as fixed effect and use "RombergOne" in TMB syntax (? not sure at all)... Hope any guideline could be given... Many thanks!
