### ISSUE TITLE
Cannot totally get rid of tracing info

### ISSUE THREAD

**Issue by williamaeberhard** [kaskr/adcomp#133]
Hi,

I'm having trouble completely suppressing all trace output from my `MakeADFun` object when used within `nlminb`. After declaring my `MakeADFun` object, say called `obj`, I do run the trace-suppressing commands given in the documentation:
```r
obj$env$tracemgc <- FALSE
obj$env$inner.control$trace <- FALSE
obj$env$silent <- TRUE
```
and when running `nlminb` with `obj=obj$fn` and `gr=obj$gr`, it does suppress things like the outer mgc and the details at each iteration of `newton`. But I still do get things like
```r
Optimizing tape... Done
Matching hessian patterns... Done
```
or sometimes
```r
Not improving much - will try early exit...PD hess?: FALSE 
```
These clutter my output in big simulations I run in batch mode...

That said, I noticed that running the optimization first, interrupting it, and then running the trace-suppressing commands allows me to eventually run the optimization with absolutely no trace output. I unfortunately cannot do this within my simulations.

Running TMB v. 1.1 in R v. 3.0.2. Can provide MWE if needed. Thanks a lot.

Cheers,

William

**Comment by kaskr** [comment]
For a while it has been possible to give 'silent=TRUE' to MakeADFun to disable _all_ tracing. Does this work for you ?

**Comment by williamaeberhard** [comment]
Just tried it, does not change: still getting those `Optimizing tape... Done` etc.

**Comment by kaskr** [comment]
I can't reproduce. Try to update TMB.

**Comment by williamaeberhard** [comment]
Ok, went through the full update to R 3.2.2 (was about time) and to TMB 1.1-1. Now everything works as expected: issuing a `silent=TRUE` in `MakeADFun` indeed suppresses all trace output while running
```r
obj$env$tracemgc <- FALSE
obj$env$inner.control$trace <- FALSE
```
disables all tracing except the `Optimizing tape... Done` things. Thanks a lot!

Best regards from Halifax,

William
