### ISSUE TITLE
precompile not working on MAC (was: TMB with Mac Yosemite)

### ISSUE THREAD

**Issue by aleianez** [kaskr/adcomp#147]
Hi:
I'm working with TMB on Mac OS Yosemite. Everything going well, except for the "precompile" function. I tried to solve but I still getting the same error. My model compiles but when I make "dyn.load(dynlib("mymodel")) I get the message error : "Unable to load shared object" " Symbol not found"
I tried reinstall over and over "precompiling" each time with "precompile ()" linux way and "precompile(PKG_LIBS ="-install_name `pwd`/$@")" mac-way. 
Is there any solution for this? 

Thank you very much.

**Comment by mebrooks** [comment]
Maybe you're doing something advanced that is over my head, but if not...
have you tried 
```
compile("mymodel.cpp")
dyn.load("mymodel.so")
```
That's how it works on my mac which I have not yet updated to Yosemite.

**Comment by mebrooks** [comment]
I get the same behavior on my Mac running Yosemite
```
Error in dyn.load("rand_walk.so") : 
  unable to load shared object '/Users/molliebrooks1/Documents/State-Space Workshop/random walk/rand_walk.so':
  dlopen(/Users/molliebrooks1/Documents/State-Space Workshop/random walk/rand_walk.so, 6): Library not loaded: pwd/libTMB.so
  Referenced from: /Users/molliebrooks1/Documents/State-Space Workshop/random walk/rand_walk.so
  Reason: image not found
```

**Comment by kaskr** [comment]
Did you get the backticks right?:
```precompile(PKG_LIBS = "-install_name `pwd`/$@")```

**Comment by aleianez** [comment]
Yes. I do copy paste from the "precompile R help" and I`m still getting the same error:


Error in dyn.load(dynlib("spline")) : 
  unable to load shared object '/Users/alejandro/TMB/spline/spline.so':
  dlopen(/Users/alejandro/TMB/spline/spline.so, 6): Symbol not found: __ZN18objective_functionIN5CppAD2ADINS1_INS1_IdEEEEEEEclEv
  Referenced from: /Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.so
  Expected in: flat namespace
 in /Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.so

**Comment by kaskr** [comment]
There seems to be two different issues. @mebrooks could still have missed the backticks?

@aleianez Assuming you ran precompile right try to restart R and recompile 'spline.cpp' (it might still be linking to a broken libtmb from when you experimented with the Linux instructions...).
If still not working it would be useful to have all your compiler output from pre-compilation *and* from 'spline.cpp' - preferably in GitHub Flavored Markdown.

**Comment by mebrooks** [comment]
Sorry, I didn't mean to add confusion to the discussion. With the backticks, now I'm getting the same behavior as @aleianez.

**Comment by kaskr** [comment]
@mebrooks Now you got the first part right too, did you recompile 'rand_walk.cpp' afterwards (with changed time-stamp)?

If yes I think we can mark this as a bug...

**Comment by mebrooks** [comment]
Yes, I deleted the .o and .so files and started over. I did 
```
precompile(PKG_LIBS = "-install_name `pwd`/$@")
compile("rand_walk.cpp")
```
Then new .so and .o files were created, but `dyn.load("rand_walk.so")` gave the error that aleianez posted above.

**Comment by kaskr** [comment]
Hopefully solved in v1.6.4 ?

**Comment by mebrooks** [comment]
It seems that there may still be a bug. In a new R session, doing 
```
library(TMB)
precompile()
system.time(compile("rand_walk.cpp"))
```
gives a warning and takes much longer than the standard compilation.
```
> system.time(compile("rand_walk.cpp"))
Note: Using Makevars in /Users/molliebrooks1/.R/Makevars 
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_rand_walk -DWITH_LIBTMB -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -mtune=core2 -g -O2 -c rand_walk.cpp -o rand_walk.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_rand_walk -DWITH_LIBTMB -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -mtune=core2 -g -O2 -c /Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.cpp -o /Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.o
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.cpp:5:9: warning: 
      Running TMB precompilation... [-W#pragma-messages]
#pragma message "Running TMB precompilation..."
        ^
1 warning generated.
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rand_walk.so rand_walk.o /Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   user  system elapsed 
 40.741   1.354  42.192 
```
At least `dyn.load("rand_walk.so")` seems to work after that.
Then if I delete the `.o` and `.so` files and run the same command in the same session, it takes the normal amount of time to compile and doesn't give a warning.
```
> system.time(compile("rand_walk.cpp"))
Note: Using Makevars in /Users/molliebrooks1/.R/Makevars 
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_rand_walk -DWITH_LIBTMB -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include    -fPIC  -mtune=core2 -g -O2 -c rand_walk.cpp -o rand_walk.o
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o rand_walk.so rand_walk.o /Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/libs/libTMB.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   user  system elapsed 
  3.620   0.189   3.848 
```

**Comment by kaskr** [comment]
Great, it works fine (note the changes in ```?precompile```).
The message ```#pragma message "Running TMB precompilation..."``` is a notification, not a warning.
It only appears the first time you compile a model after ```precompile()```. The second compilation is fast because it uses the precompiled library.

**Comment by aleianez** [comment]
I tried on my mac and everything is working fine for me. Bug deleted!

Thank you very much!

Alejandro A. Yáñez
Master (c) in Fisheries Science
Universidad de Concepción
Chile
+56-41-220 43 45
