### ISSUE TITLE
Hessian computed by automatic differentiation (AD)?

### ISSUE THREAD

**Issue by williamaeberhard** [kaskr/adcomp#148]
Dear TMB team,

I know TMB officially does not support a user-level function for computing the Hessian of fixed parameters for models with random effects. I however do need it for some Newton/quasi-Newton algorithm and was surprised to discover that `sdreport` actually uses `optimHess` to approximate it. Is there hope that one day TMB will use AD for the Hessian too? for the sake of speed and accuracy...

Cheers,

William

**Comment by kaskr** [comment]
For the sake of accuracy we might consider adding it. Unfortunately,
an AD Hessian will not generally provide any speedup compared to the
current approach (finite difference on AD gradient which BTW is same
as ADMB uses).

**Comment by williamaeberhard** [comment]
Ok, thanks for the quick reply and for having added this to the Wish list!

All the best,

William
