### ISSUE TITLE
Using map doesn't always raise objective value

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#154]
I'm trying to use the map feature to set some random effects to 0 so that I can test their significance with a LRT or AIC. Sometimes fixing some parameters to 0 (the restricted model) actually makes the objective lower (better), but I thought the restricted model should always be worse. I wondered if this might something have something to do with how the map is working. 

Here is a simple example where the mean is always zero, and there are random effects of year (y) and individual (i).

Code for REiy.cpp
```

#include <TMB.hpp>                                

template<class Type>
Type objective_function<Type>::operator() ()
{
	DATA_VECTOR(obs);          
	DATA_FACTOR(io);          
	DATA_FACTOR(yo);          
	PARAMETER_VECTOR(rei);
	PARAMETER_VECTOR(rey);
	PARAMETER(logsdresid);
	PARAMETER(logsdi);
	PARAMETER(logsdy);
	Type sdresid=exp(logsdresid);	
	Type sdy=exp(logsdy);	
	Type sdi=exp(logsdi);

	Type jnll;          
	jnll=0;

	for(int o=0; o<obs.size(); o++)
	{
		jnll-=dnorm(obs(o), rei(io(o))+rey(yo(o)), sdresid, true);
	}	
	for(int i=0; i<rei.size(); i++)
	{
		jnll-=dnorm(rei(i), Type(0), sdi, true);
	}	
	for(int y=0; y<rey.size(); y++)
	{
		jnll-=dnorm(rey(y), Type(0), sdy, true);
	}	

	ADREPORT(sdresid);
	ADREPORT(sdi);
	ADREPORT(sdy);
	
	return jnll;
	
}	
```
R code to simulate data and run the model.

```
library(TMB)
compile("REiy.cpp", "-g -O0")
dyn.load("REiy.so")

s=1
set.seed(s)

ni=10
ny=15
sdi=10
sdy=1
sdresid=.5
rei=rnorm(ni, sd=sdi)
rey=rnorm(ny, sd=sdy)


dat=expand.grid(i=1:ni, y=1:ny) 
dat=transform(dat, obs=rnorm(n=ni*ny, mean=rei[i]+rey[y], sd=sdresid))

data=list(obs=dat$obs, io=dat$i-1, yo=dat$y-1)
pars=list(rei=rep(0, ni), rey=rep(0, ny), logsdresid=0, logsdy=0, logsdi=0)

mod=MakeADFun(data, pars, random=c("rei", "rey"), DLL="REiy")
opt= nlminb(mod $par, mod $fn, mod $gr)
summary(sdreport(mod), "report")#close to true values

mapy=list(logsdy=as.factor(NA), rey=as.factor(rep(NA, ny)))
parsy=pars
parsy$logsdy=-26
parsy$rey=rep(0, ny)

mody=MakeADFun(data, parsy, random=c("rei", "rey"), DLL="REiy", map=mapy)
opty= nlminb(mody $par, mody $fn, mody $gr)

opt$objective
opty$objective
```
In this example, the objective for the restricted model is almost 300 units lower. Am I doing something stupid? Is there another way I should be testing the significance of random effects?

If I rerun it with `sdy=10` then it does what I would expect and the objective of the restricted model is higher.

**Comment by kaskr** [comment]
For the restricted model you would have to disable the 'rey' prior term:
```c++
    for(int y=0; y<rey.size(); y++)
    {
        jnll-=dnorm(rey(y), Type(0), sdy, true);
    }
```
This could e.g. be done by letting an empty rey vector signal this special case.
Or perhaps by setting ```sdy=1/sqrt(2*pi)``` since in that case ```dnorm(0,0,sdy,TRUE) = 0```.

**Comment by mebrooks** [comment]
Thanks! I like the `sdy=1/sqrt(2*pi)` solution. I'm so relieved to see more reasonable answers now!

**Comment by mebrooks** [comment]
I did some testing and I get the same objective value if I use `sdy=1/sqrt(2*pi)` or 
```
if (CppAD::Variable(rey(y)))
            jnll-=dnorm(rey(y), Type(0), sdy, true);
```
So I'll use the if statement since it's cleaner and is more flexible as I sometimes want to include MVN random effects. Thanks!
