### ISSUE TITLE
Integer random effects? Is it possible?

### ISSUE THREAD

**Issue by cgrandin** [kaskr/adcomp#155]
Hello once again colleagues,
We are attempting to translate some BUGS code into TMB to improve speed and R-integration. Is it possible to have an integer random effect in TMB, to emulate the function dpois() or dbinom() ?
Thanks,
Chris

**Comment by skaug** [comment]
Not in the way it usually done in TMB (Laplace approximation). However,
you can explicitely "sum over a poisson (say) variable". The nmix example
shows how this can be done. 

Hans

**Comment by bbolker** [comment]
For what it's worth, the Stan manual <https://github.com/stan-dev/stan/releases/download/v2.8.0/stan-reference-2.8.0.pdf>, chapter 11, also has some examples of how to do this (the technical constraint is different, but has the same effect on the class of models that can be fitted ...)

**Comment by cgrandin** [comment]
Thanks guys, I will have a look at both methods.
