### ISSUE TITLE
Sum constraints

### ISSUE THREAD

**Issue by torarneoigard** [kaskr/adcomp#158]
Hi,

Is there a way to have sum constraints on parameters? I have a vector and all the elements should sum to 0. Actually, I have two vectors, one is a normal vector to be estimated and the other is a vector of random effects.

Best wishes,
Tor

**Comment by bbolker** [comment]
If you need `a1+a2 ... + an==0` then the easiest thing to do is to eliminate one parameter, e.g. set `an` equal to `-(a1+a2 + ....)` ...

**Comment by torarneoigard** [comment]
Good idea - thanks a lot!
