### ISSUE TITLE
Array and Matrix Issues

### ISSUE THREAD

**Issue by Njoselson** [kaskr/adcomp#160]
Hi All,

I wrote an issue on this topic earlier in the year: https://github.com/kaskr/adcomp/issues/109 

As far as I can tell, Eigen was only designed for 2D matrices and arrays, so extracting a "slice" of an array is not supported in TMB. This makes data-heavy work very tiring because to reference a portion of an array, you need to create a loop with explicit reference to all the elements. (see the issue before)

Another matrix/array issue that hasn't been addressed though, is that matrix and array functionality don't mix well in Eigen. For example it is not allowed to have a  ```*``` operator mean both "Matrix multiplication" and "coefficient-wise multiplication." That means that this code below is not allowed.
```
m =  (PPMY.matrix()).transpose()* (SCL* WAL).matrix()
```

Here, when the arrays SCL and WAL are multiplied, the result is coefficient-wise, but then that is converted to a matrix and multiplied with PPMY as a matrix. This returns an error about ```*``` being an ambiguous operator.

Is there any solution to this other than breaking this multiplication up into lots of dummy variables which don't conflict?
ie 
```
m1 = (SCL*WAL).matrix()
m2 = (PPMY.matrix()).transpose()
m = m2*m1
```

Since TMB is meant to be designed for to be matrix friendly, it would be strange to me that such an ugly, inefficient solution would be the best that can be done.

These two issues are a big hangup for our organization's transition toward TMB, so any help would be very welcome!

Cheers,
Nathaniel

**Comment by skaug** [comment]
Regarding extracting a "slice" of an array:  Have you looked at the "template" section of the R-docs Package ‘TMB’? The following seems to be what you ask for:
a.col(i).col(j) R equivalent of a[,j,i]. Does this do the job for you?

Regarding your second point about matrix/arrays the your code actually compiles
for me:

```
#include <TMB.hpp>

template<class Type>
  Type  objective_function<Type>::operator() (  ) {
    DATA_VECTOR( y );
    PARAMETER_VECTOR( theta );
    Type g;
    array<Type> SCL(2,2);
    array<Type> WAL(2,2);
    array<Type> PPMY(2,2);
    
  matrix<Type> m =  (PPMY.matrix()).transpose()* (SCL* WAL).matrix();    
    return(g);
  }
```

**Comment by Njoselson** [comment]
That is great! Having re-cloned TMB it compiles perfectly, even with multiple uses for the * operator.

As for the "slicing" functionality, it can only take slices from right to left, is that correct? I suppose we can code our matrices to work around that...

Thank you so much for all the help and for the speedy reply!
