### ISSUE TITLE
Problem running TMB from a CRAN install

### ISSUE THREAD

**Issue by mveitzel** [kaskr/adcomp#161]
Hello TMB/ADMB folks,

I've installed TMB through CRAN (using install.packages("TMB") from the R command line).  I'm running 64 bit Windows 8.1, and R version 3.1.2

When I try to source an R script calling TMB, I get the following error:

> source("linreg.R")
> Error in compile("linreg.cpp") : Compilation failed
> In addition: Warning messages:
> 1: package ‘TMB’ was built under R version 3.1.3 
> 2: running command 'make -f "C:/PROGRA~1/R/R-31~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-31~1.2/share/make/winshlib.mk" -f "C:\Users\MV\AppData\Local\Temp\RtmpCeLVop\file263023d3a08" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="linreg.dll" WIN=64 TCLBIN=64 OBJECTS="linreg.o"' had status 127 

Any thoughts?

Thanks,

MV

**Comment by kaskr** [comment]
See https://github.com/kaskr/adcomp/wiki/FAQ
