### ISSUE TITLE
TMB documentation website down

### ISSUE THREAD

**Issue by rmp15** [kaskr/adcomp#164]
The website containing TMB documentation seems to be down:

http://folk.uib.no/hsk021/tmbdoc/

Has it moved, or is there an alternative source (beyond the examples on GitHub) that I could be directed towards?

Thank you,

Robbie

**Comment by kaskr** [comment]
Yes it has moved. See the wiki:
https://github.com/kaskr/adcomp/wiki/Documentation

**Comment by rmp15** [comment]
Thank you.

**Comment by rmp15** [comment]
Will there be any short courses in the near future about TMB?

Best,

Robbie
