### ISSUE TITLE
Search window not working

### ISSUE THREAD

**Issue by skaug** [kaskr/adcomp#166]
The search field in the upper right corner of http://kaskr.github.io/adcomp/ is not working,
at least on some browsers. I think it has worked before, so it may be a temporary.

The way it is supposed to work is that when you start writing "DATA_" it will show all
functions starting with that. (useful if you do not remember all the data types, say).

**Comment by kaskr** [comment]
That's odd. It worked for me yesterday.
Must be a github web server issue.

**Comment by smartell** [comment]
Works for me
> On Jan 13, 2016, at 2:30 AM, kaskr <notifications@github.com> wrote:
> 
> That's odd. It worked for me yesterday.
> Must be a github web server issue.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/kaskr/adcomp/issues/166#issuecomment-171248438>.
> 

Steve Martell
martell.steve@gmail.com

**Comment by skaug** [comment]
It appears to work now for me as well.
