### ISSUE TITLE
Simulating parameters from estimation covariance for large models

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#167]
Hi all,

I have a large (~10 fixed and ~100,000 random effects) model, and would like to calculate a derived quantity and its standard errors.  However, the function for calculating the derived quantity is non-differentiable (it is specifically a minimum polygon for a 2D spatial process, and requires a sort calculation).  I therefore imagine the easiest way to do this is to simulation draws from the joint covariance of fixed and random effects, evaluated at the MLE for fixed effects and Empirical Bayes estimate for random effects.  I think this is similar to what was done in Lewy and Kristensen 2009 (http://www.nrcresearchpress.com/doi/abs/10.1139/f09-114, see journal page 1812).  I believe this joint covariance is already being manipulated within the sdreport function (and will start looking there myself), but welcome any suggestions for how to avoid storing or working with a square matrix with dimension 100,000...

Is there any recommended function for doing this?  I imagine its a task that, while not exactly common, would be a useful trick for many models, so it would be great to have a generic function for the task.  

cheers,
jim

**Comment by kaskr** [comment]
Such simulations can be performed based on the precision matrix
without building the dense covariance matrix. The machinery is partly
available via the importance sampler. I agree it would be useful to
have available as a generic method. Here some examples:
```
runExample("simple")
```
Calculate the posterior mean of the maximum of the random effects
using importance sampling (using antithetic variates to reduce variance):
```
obj$env$MC(n=1000, phi = max)
```
You can also get direct access to the underlying Gaussian samples:
```
obj$env$MC(n=3, keep=TRUE, antithetic=FALSE)
```
In dimension 100000 you may want to sample in batches of say n=100 
at a time.
