### ISSUE TITLE
Compiling warnings - linux vs mac

### ISSUE THREAD

**Issue by torarneoigard** [kaskr/adcomp#169]
Hi,

I made a function for doing an outer-product of two vectors (it's probably one there already but could not find it).

It compiles (and runs) without any problems on linux but if I compile it on mac I get a lot of warnings (and it won't run.). I use clang on both systems. On mac I use TMB 1.6.6 and on linux its TMB 1.6.5. 

The function I "made" goes like this:

`template <class Type>
array<Type> outerProduct(vector<Type> x,vector<Type> y){
  int Nx = x.size();
  int Ny = y.size();
  array<Type> opr(Nx,Ny);

  for (int i=0; i<Nx ; ++i){
    for (int j=0; j<Ny ; ++j){
      opr(i,j)=x(i)*y(j);
      return opr;
    }
  }
} `

The warning I get looks like this:

SCA_mentella_model.cpp:16:1: warning: control may reach end of non-void function [-Wreturn-type]
} 
^
SCA_mentella_model.cpp:203:11: note: in instantiation of function template specialization 'outerProduct<CppAD::AD<double> >' requested here
  DemF =  outerProduct(DemFY,DemFA);
          ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:911:6: note: in instantiation of member function 'objective_function<CppAD::AD<double> >::operator()' requested here
    F(); // Run through user template (modifies reportvector)
     ^
SCA_mentella_model.cpp:16:1: warning: control may reach end of non-void function [-Wreturn-type]
} 
^
SCA_mentella_model.cpp:203:11: note: in instantiation of function template specialization 'outerProduct<double>' requested here
  DemF =  outerProduct(DemFY,DemFA);
          ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:1130:25: note: in instantiation of member function 'objective_function<double>::operator()' requested here
      res = asSEXP( pf->operator()() );
                        ^
SCA_mentella_model.cpp:16:1: warning: control may reach end of non-void function [-Wreturn-type]
} 
^
SCA_mentella_model.cpp:203:11: note: in instantiation of function template specialization 'outerProduct<CppAD::AD<CppAD::AD<double> > >' requested here
  DemF =  outerProduct(DemFY,DemFA);
          ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:678:20: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<double> > >::operator()' requested here
    Type ans=this->operator()();
                   ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:1169:10: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<double> > >::evalUserTemplate' requested here
  y[0]=F.evalUserTemplate();
         ^
SCA_mentella_model.cpp:16:1: warning: control may reach end of non-void function [-Wreturn-type]
} 
^
SCA_mentella_model.cpp:203:11: note: in instantiation of function template specialization 'outerProduct<CppAD::AD<CppAD::AD<CppAD::AD<double> > > >' requested here
  DemF =  outerProduct(DemFY,DemFA);
          ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:678:20: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<CppAD::AD<double> > > >::operator()' requested here
    Type ans=this->operator()();
                   ^
/Library/Frameworks/R.framework/Versions/3.2/Resources/library/TMB/include/tmb_core.hpp:1284:12: note: in instantiation of member function 'objective_function<CppAD::AD<CppAD::AD<CppAD::AD<double> > > >::evalUserTemplate' requested here
  y[0] = F.evalUserTemplate();
           ^
4 warnings generated.

**Comment by kaskr** [comment]
Your Mac system is doing the right thing: It tells you that you are
returning the result from inside the loop :)
You get the same behavior on Linux by adding the -Wall flag to
CXXFLAGS (can be changed in ```~/.R/Makevars```).

**Comment by torarneoigard** [comment]
Ha ha - how embarrassing. Thanks for that. Yes - it works fine now. I'll close this and if possible delete it :)
