### ISSUE TITLE
Parameters fed to MakeADFun affect objective function when evaluated at another point

### ISSUE THREAD

**Issue by williamaeberhard** [kaskr/adcomp#170]
Dear TMB team,

I found something strange. I can replicate it (I can send you the cpp and R scripts if needed) but it not systematic at all (requirement of one the initial thetas yielding a warning, see below). Here's the problem:

Say I have two sets of fixed parameters theta1 and theta2, both are already transformed so that they belong to R^p (no support issues). I put them in two lists, parlist1 and parlist2, where I add starting values for my random effect beta0 (the same for both lists). I compile with MakeADFun with both theta values, everything else being the same:
```R
obj1 <- MakeADFun(data=datalist, parameters=parlist1, random='beta0', DLL="some_dll")
obj2 <- MakeADFun(data=datalist, parameters=parlist2, random='beta0', DLL="some_dll")
```
I do not get any error or warning when compiling. My "some_dll" does nothing especially fancy, it's a Poisson-Gaussian SSM where I estimate theta in a robust way.

If I evaluate the two objective functions without specifying any argument, `obj1$fn()` and `obj2$fn()`, I obviously get different results because they are evaluated at their respective last parameter value, i.e. theta1 and theta2. To replicate the problem, one the thetas need to give the following warning:
```R
In destructive_Chol_update(L, H, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
```
Now if I try to evaluate the two obj at a specified theta3, `obj1$fn(theta3)` and `obj2$fn(theta3)`, I get different values! With it, I again sometimes get the destructive_Chol_update `Cholmod warning 'matrix not positive definite'` warning, but only at the first evaluation at theta3 after compilation. Note that theta3 is a valid value, and it can be equal to theta1 or theta2.

Am I wrong in assuming that the value of theta fed to MakeADFun should not affect the objective (and gradient) when evaluated at another specified point, even it it yields this destructive_Chol_update warning?

Running TMB 1.6.6 with R 3.2.2.

Thanks a lot, your work and help is much appreciated.

Best regards from Halifax,

William

**Comment by kaskr** [comment]
Normally the two values should be equal but there are a few exceptions:
1. Use of parameter dependent branching (https://github.com/kaskr/adcomp/wiki/Things-you-should-NOT-do-in-TMB) can give surprising results. 
2. Multimodal inner problems (probably not the case here since inner problem is convex) or a close to singular Hessian for inner problem can cause numerical instabilities of the Laplace approximation.
   * You may want to compare random effect part of ```obj1$env$last.par``` and ```obj2$env$last.par```. Are they nearly equal?
   * You may want to change convergence tolerances of inner problem, see ```?newton``` and ```?newtonOption```.

**Comment by williamaeberhard** [comment]
Thanks a lot for your quick and relevant answer!

I do have an `if()` applied to log-likelihood components which are obviously function of the parameters. My function is actually differentiable, with continuous derivatives at least up to the third order, but I don't currently see another way of writing it without `if()`statements. I understand `if`s and Dirac delta functions cannot easily be integrated within AD, but is there hope that one day you will allow TMB not to ignore them? In other words letting the software trust the user that the function is many times differentiable everywhere and segment the AD?

I was able to test a slightly different function, behaving about the same way but not defined in a piecewise fashion: I nearly always get the same obj value with theta1 and theta2 now (good news!). The rare cases where obj1 and obj2 were still not equal was when one, say theta2, yielded an NaN. obj1 and obj2 would then possibly give different values when evaluated at theta3, even when this one was valid (not returning NaN). I cannot reproduce this when I don't evaluate the obj at their respective initial theta, i.e. avoiding `obj1$fn()` and `obj2$fn()`, so this has more to do with the sequence of theta than the initial one fed to MakeADFun.

So, conclusion: no `if()` applied on parameters and make sure the initial theta is valid and does not return NaN!

Thanks a lot for your help!

Cheers,

William
