### ISSUE TITLE
TMB for estimating equations

### ISSUE THREAD

**Issue by rugbel** [kaskr/adcomp#171]
Hi all,
I would like to use TMB for implementing an estimator defined by estimating equations which are not the 
gradient of an objective function. There are no random effects, but coding the jacobian of the estimating equations is challenging (they are rather complex), and AD could be  of some help. 
Do you think it would be possible to trick TMB into doing it ?
Thanks,
Ruggero

**Comment by skaug** [comment]
Hi, I assume you want to solve the system u(x)=0, where x is a vector
and u() is a vector valued function of the same dimension as x.
I assume it is possible to use the objective function

f(x) = sum_i  (u_i(x))^2

for solving the equations wrt x. If, so you can obtain u_i by AD in TMB. Look at example laplace.cpp
in example collection. Derivative calculations are the code "autodiff::gradient(f, u);"

**Comment by rugbel** [comment]
Hi Hans, thanks for the reply.
I would prefer to solve the problem avoiding to pass from the optimization of f(x), as the optimizer may converge to local minima of f that do not solve u(x)=0.
But maybe you just mean that it might be possible to write the usual TMB template for f(x), and then export to R the result of "autodiff::gradient(u, x);"? 
This would actually solve the problem.

**Comment by skaug** [comment]
Hi, the problem is that TMB cannot return a vector from C++ (as far as I know).
Regarding local minima, those would be  easy to diagnose by looking
at the value of the sum of squares.

**Comment by kaskr** [comment]
Just want to point out that ```MakeADFun(...,ADreport=TRUE)``` can be
used to return a vector. However, I agree that it should not be
necessary for this problem.

**Comment by rugbel** [comment]
Thanks, this seems encouraging. 
At any rate, there is some evidence in the numerical analysis literature about the fact that the solving the nonlinear equation u(x)=0 by minimizing f(x) (as defined by Hans) is a method that often works, but it is not always a good idea. f(x) can instead be  rather useful to find the step-length of Newton-like algorithms, though.
