### ISSUE TITLE
sdreport() and reporting just the parameter values

### ISSUE THREAD

**Issue by drfinlayscott** [kaskr/adcomp#174]
Hi,
I am a new user of TMB and I have a question about sdreport() and reporting parameter values.

I can see from the documentation that sdreport() calculates the Hessian and inverts it. This is then used to calculate the std error of the parameters. If I use the argument ignore.parm.uncertatainty=TRUE, then the reported std error is 0 for the reported parameters. Does this still calculate and invert the Hessian, even though the result is not used?

I am asking because sometimes I want the std error and the value of the parameters and sometimes I just want the value without the overhead of calculating and inverting the Hessian.

If I just want the value of the parameters I can use the REPORT() macro in the cpp file and then the model$report() function. One option is therefore to use both REPORT() and ADREPORT() for each parameter I want and use model$report() or sdreport(model) depending on what output I want. However, this has the (very mild) disadvantage of duplicating the REPORT / ADREPORT lines.

To get just the parameter values without calculating and inverting the Hessian, is using REPORT() with model$report() doing the same thing as SDREPORT() with sdreport(model, ignore.parm.uncertatainty=TRUE)?

Thanks

Finlay

**Comment by kaskr** [comment]
Quoting from ```?sdreport```: If ```ignore.parm.uncertainty=TRUE```
then the Hessian calculation is omitted and a zero-matrix is used in
place of ```V(theta)```.

If you want parameters without sds you can get them directly from the
optimizer output. Or you can grab them from the object environment
after running the optimizer (see ```?MakeADFun```): ```obj$env$last.par.best```


Get the parameter estimates in the original list structure using: ```obj$env$parList(par=obj$env$last.par.best)```


The REPORT / ADREPORT macros are for derived quantities. REPORT is
fastest and can output general objects (matrices, arrays,
etc). ADREPORT is different. It joins all output to a single vector
and performs AD on the result.

**Comment by drfinlayscott** [comment]
Great. Thanks.
