### ISSUE TITLE
REPORT() from an Outside function

### ISSUE THREAD

**Issue by Njoselson** [kaskr/adcomp#179]
Hi there,

I am trying to report on Variable values from a different function than my objective function. 

eg
```
#include <TMB.hpp>
#include <iostream>
#include <Eigen/Dense>

template<class Type>
Type square(Type x){return x*x;}

template<class Type>
Type posfun(Type x, Type eps, Type &pen){
  pen += CppAD::CondExpLt(x,eps,Type(0.01)*pow(x-eps,2),Type(0));
  return CppAD::CondExpGe(x,eps,x,eps/(Type(2)-x/eps));
}


template<class Type>
matrix<Type> PMATRIX(Type stddevPmat,Type alphaPmat,Type betaPmat,Type ageplus,Type linf,Type kappa,Type t0,vector<Type> agevectorP,Type stddevpenP,vector<Type> logsize05P,vector<Type> logsize15P)
{
	sdsize= alphaPmat + (0.0714286*betaPmat*(agevectorP-c1)); 
    sdsize(0) = stddevPmat;   
    sdsize(1)=sdsize(0)+posfun(sdsize(1)-sdsize(0),epss,pens);
  REPORT(sdsize);
    return sdsize;
}

template<class Type>
Type objective_function<Type>::operator() ()
{
   DATA_VECTOR(Y);

  PARAMETER (b);
  PARAMETER_VECTOR (sigmaA);
	
	Type LLF=0; 		//OBJECTIVE FUNCTION Value
     return(LLF);

}
```

However, this gives me the error:

```
hake2016.cpp:10:3: error: invalid use of 'this' outside of a non-static member function
  REPORT(pen);
  ^
```

Does this mean that it's not possible to report on variables outside of the objective function? Are there other reasons that it is not advisable to bundle repeated calculations into an outside function?

Thanks,

Nathaniel

**Comment by Njoselson** [comment]
Another question I have about extra functions, is whether they slow down the program's compilation. We am rebuilding a TMB model from a working ADMB model, but the compilation times are getting close to 40 minutes to 1 hour. We have 5 outside functions which are doing substantial matrix/array calculations, so should they be included in the main objective function code, instead of being defined outside?

Thanks! Getting stressed out by the long compilation times!

**Comment by kaskr** [comment]
It is generally recommended to put code in external
functions. However, as you note it is currently not possible to use
the TMB macros from outside the objective_function.

Regarding long compilation times:
* Have you tried ```precompile()``` ?
* Have you tried a non-windows operating system ?
* You may consider compiling each function in a separate translation
  unit. However, there are not yet any worked out examples of this
  technique.

**Comment by Njoselson** [comment]
Hi,

Thank you for letting me know about external functions. Perhaps more of the main LLF can be functionalized for repetitive calculations.

I used the wrong term. I didn’t mean only compilation, but the whole pre-optimization routine. With precompile() the compilation time is about 4 minutes, but the MakeADFun() call takes between 40 minutes to an hour. 

I notice that the R session is only using 25% of my CPU capacity in the Activity Monitor. Is there any way to allow R to use more processing power?

This is on a Mac computer.

Thanks again! You guys are the best!

**Comment by Njoselson** [comment]
After reading this thread: [https://github.com/kaskr/adcomp/issues/122](url) I downloaded the Microsoft Open R program to speed-up run times. I installed it and then re-installed TMB on the new R, but now my c++ compiler has broken. It gives an error:
```
clang: error: no such file or directory: '/usr/local/lib/libcairo.a'
clang: error: no such file or directory: '/usr/local/lib/libpixman-1.a'
clang: error: no such file or directory: '/usr/local/lib/libfreetype.a'
clang: error: no such file or directory: '/usr/local/lib/libfontconfig.a'
clang: error: no such file or directory: '/usr/local/lib/libreadline.a'
make: *** [hake2016.so] Error 1
Error in compile("hake2016.cpp") : Compilation failed
```

I've been reading around to try to find other people with this problem, but no luck finding a solution. This is a Mac computer.

Sorry for all the questions!
