### ISSUE TITLE
Developer's meeting topics

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#185]
TMB and ADMB developers will meet this summer to work on the software and discuss future efforts. If there are any specific topics that might be useful for that agenda, please mention them here, possibly by posting a link to another issue. Thanks!

**Comment by jimianelli** [comment]
Thanks Mollie, I'll be trying to get the agenda together this week and will be sure to refer to this issue link for compiling terms of reference etc.

**Comment by mebrooks** [comment]
I've been thinking about adding the zero-truncated-Poisson, zero-truncated-negative-binomial, and generalized Poisson distributions. The zero-truncated distributions are useful for hurdle models. The generalized Poisson is useful for annual reproductive success (http://www.journals.uchicago.edu/doi/pdfplus/10.1086/650724).
