### ISSUE TITLE
Best practice: is a single call to Type enough?

### ISSUE THREAD

**Issue by williamaeberhard** [kaskr/adcomp#187]
Dear TMB team,

This may be a trivial question but I've seen enough code examples of both alternatives to cast doubt: in the cpp template, when creating, say, a scalar as a `Type`, do you still need to declare it as a Type later on? My initial thought of best practice was to initialize any object by a single call to `Type` outside of any `for` loop and then overwrite it as much as I wanted. But I've seen numerous code examples where `Type` was called again within a loop. Recommendation? Thanks.

Cheers,

William

**Comment by kaskr** [comment]
You probably want to study
http://stackoverflow.com/questions/12446586/local-variables-defined-inside-for-loops-in-c
and
http://stackoverflow.com/questions/7959573/declaring-variables-inside-loops-good-practice-or-bad-practice-2-parter

**Comment by williamaeberhard** [comment]
Thanks!
