### ISSUE TITLE
sdreport speed when using ADREPORT

### ISSUE THREAD

**Issue by vkontis** [kaskr/adcomp#195]
Hello and thanks for all your good work. 

I have defined a vector `p` of length ~250,000 to store the linear predictor. The model takes only a few minutes to fit, but when I try `ADREPORT(p)`,`sdreport()` becomes much slower/hangs (judging by the output it looks like it's finished, but it doesn't exit - I let it run for about 12 hours before killing it). Both `REPORT(p)` and`ADREPORT(p[1])` run very fast, so I am guessing this is related to the size of `p`?

Thanks
Vasilis

**Comment by kaskr** [comment]
```ADREPORT``` works best for relatively short vectors of complex expressions.  There will be a substantial computational waste for long vectors of simple linear derived quantities.

Note that you can pass ```getReportCovariance=FALSE``` to ```sdreport``` to avoid calculating the full covariance matrix of your linear predictor (requires a recent version of TMB from github).

**Comment by vkontis** [comment]
Thanks Kasper, will download the latest github version and give it a try.
