### ISSUE TITLE
Error in sdreport(..., bias.correct=TRUE) in some cases

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#198]
Hi all,

I've found what is presumably a bug in the bias-correction feature, but am having trouble finding a "minimally reproducible example".  The problem has been replicated using a 10-15 minute example using `SpatialDeltaGLMM` on multiple machines (I'm happy to send a script showing the problem), and occurs in recent versions of TMB but not earlier versions.

Essentially, when I run the bias correction feature `sdreport( ..., bias.correct=TRUE)`, it throws the following error after finishing all computations:

``` R
outer mgc:  0.04222905 
iter: 1  value: 25486.97 mgc: 0.001679618 ustep: 1 
iter: 2  value: 25486.97 mgc: 8.075902e-07 ustep: 1 
iter: 3  mgc: 2.874367e-13 
outer mgc:  7.617104 
iter: 1  value: 25486.83 mgc: 0.001682981 ustep: 1 
iter: 2  value: 25486.83 mgc: 8.097102e-07 ustep: 1 
iter: 3  mgc: 2.878808e-13 
outer mgc:  7.629664 
outer mgc:  114440.8 
Problem with these parameter entries:
hyperparameters_z          gamma1_j         gamma1_tp        logsigmaV1       logsigmaVT1        Beta_mean1        logsigmaB1         Beta_rho1      Epsilon_rho1 
                2                 4                 5                10                11                12                13                14                15 
            nu1_v            nu1_vt          gamma2_j         gamma2_tp        logsigmaV2       logsigmaVT2        Beta_mean2        logsigmaB2         Beta_rho2 
               16                17                21                22                27                28                29                30                31 
     Epsilon_rho2             nu2_v            nu2_vt 
               32                34                35 
Error in MakeADFun(obj$env$data, parameters, random = obj$env$random,  : 
  Only numeric matrices, vectors and arrays can be interfaced
```

This problem does not occur without the bias-correction, i.e., using `sdreport( ..., bias.correct=FALSE)`.  Any guesses @kaskr on what might be causing this error to be thrown?  If you had pointers I'd be happy to start diving line-by-line through `sdreport`

cheers,
jim

**Comment by kaskr** [comment]
There have been a number of recent 'improvements' to sdreport... Probably one of them is causing the issue but I have no idea which one.
Perhaps a job for *git bisect* - there are instructions under wiki->development. In any case a reproducible example would be great.

**Comment by kaskr** [comment]
@James-Thorson 
I could re-construct this problem by using parameter maps in conjunction with bias correction.
Could you please check if the branch 'bugfix' solves your problem ?

**Comment by James-Thorson** [comment]
Thank you @kaskr!  That prevented the error.

I see v1.7.2 has the new feature "sdreport: Allow bias correct in chunks to
reduce memory".  Does this happen automatically, or is there documentation
for how to use this?  I'll admit that the bias-correction has been
difficult to use because it has previously been much more memory-intensive
than the optimization for my spatio-temporal projects.

**Comment by kaskr** [comment]
Bias correct in chunks doesn't happen automatically - It's documented in ?sdreport.

**Comment by James-Thorson** [comment]
@kaskr I'm very excited about the new options for saving memory during bias-correction.  In particular, the `split` option sounds useful by only conducting bias-correction on a subset of variables.  But:  how do we identify the "order" of ADREPORTed variables?  Is there some slot of sdreport output (e.g., `SD = sdreport( Obj );  names(SD$value)`) that we can use to match the names of ADREPORTed variables to determine their indices for use in the `split` option?

**Comment by kaskr** [comment]
Indices are pointers into ADREPORTed variables. So, in your example it is the row-indices of
```summary(SD, "report")```
(TODO: this needs to be documented)

**Comment by James-Thorson** [comment]
@kaskr Have you explored package `ff` for storing excess memory on the harddrive?  I have no idea how it would interact with package `Matrix` or `CppAD`, but it seems like another route to overcome the memory-intensivity of the bias-correction options.  If you haven't, I'm happy to put it on my list of things to explore...?

**Comment by James-Thorson** [comment]
@kaskr 

I'm working on a large model where the epsilon bias-correction method is too memory intensive.  I envision using Cole's new(ish) HMC options to sample across random effects, while fixing fixed-effects at MLEs and "turned off" parameters at starting values.  I think this would be generally useful for the class of models where memory is more limiting than computation time (e.g., some spatio-temporal models).  I could produce one-off code to do this, but wonder if you'd be interested in discuss generalized implementations?

**Comment by kaskr** [comment]
It may be worth trying out an implementation using auxiliary variables. Say you have a template

```cpp
PARAMETER_VECTOR(u);  // Random effects
Type ans = 0;         // Joint negative log likelihood
```

and you want to bias correct

```cpp
Type logs = log(exp(u).sum());
```

You get high memory usage because the hessian of `logs` wrt. `u` is dense.
To get a sparse representation pass an additional auxiliary random effects vector:

```cpp
PARAMETER_VECTOR(aux);  // Random effects same length as u
```

Rather than calculating `logs` directly, define it via the 'soft recursions':

```cpp
Type tiny = 1e-4;
ans -= dnorm(aux(0), u(0), tiny, true);                              // aux(0) = u(0)
for(int i=1; i<aux.size(); i++) {
  ans -= dnorm(aux(i), log(exp(aux(i-1)) + exp(u(i))), tiny, true);  // aux(i) = log(exp(aux(i-1)) + u(i))
}
logs = aux(aux.size()-1);
```

Finally

```cpp
ADREPORT(logs);
```

and add `random="aux"` on the R side.

This should give the desired sparsity and thereby solve the memory issue. The question is whether it is sufficiently accurate and robust. Will have to try it on an example...
