### ISSUE TITLE
Example consistency

### ISSUE THREAD

**Issue by jlaake** [kaskr/adcomp#202]
I'm still in the process of learning TMB and when I followed some of the examples in the documentation I ran into a couple of issues that are related to lack of consistency in the examples. I suggest 2 changes.

1) Include compile("xxx.cpp") in each example so you can use source("xxx.r") which didn't work for source("mvrw.r") like it said on web page.  I edited the web page to include a compile before the source but it would be better to include the compile in the .r file because my change won't work unless the user also loads TMB prior to compile call.
2) Include dyn.unload(dynlib(xxx)) at the end of each example .r file.  This would prevent a problem that I encountered in running the tutorial in which the DLL argument was not specified in MakeADFun and I had already run the mvrw example.

I don't see this being a high priority issue but one that may help new users avoid some trouble spots.

regards --jeff

**Comment by kaskr** [comment]
Those are good suggestions. I agree it needs to be fixed.

**Comment by jlaake** [comment]
When you do fix it in mvrw, please remove my edit to the web page which would not be needed and may then cause confusion.  I look forward to working with TMB. Thanks for all your work on it.
