### ISSUE TITLE
saving harddrive space while archiving results

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#203]
In case its useful to anyone, I'm recording my experience with managing harddrive space.  Essentially, simulation experiments require saving many outputs from `sdreport`, which includes a slot `env` that is often large for models with many random effects (>10MB, which is prohibitive for thousands of simulation replicates).  I've modified `TMBhelper::Optimize` to delete the `env` slot when auto-archiving estimates, but this then prevents `summary` from working as it does normally.  This problem can then be circumvented by explicitly calling `TMB:::summary.sdreport` on the `sdreport` output that is missing slot `env`.  

@kaskr, do you think its worth modifying `summary.sdreport` to work on an `sdreport` object that is missing the `env` slot?

**Comment by kaskr** [comment]
@James-Thorson 
Thanks for pointing out the fact that the 'env' slot takes up so much space. That is clearly a bug. Now fixed.
Does that solve your storage issue?

**Comment by James-Thorson** [comment]
Yeah, that fixed it, thanks!
