### ISSUE TITLE
Dimensions of ADREPORTed objects

### ISSUE THREAD

**Issue by joethorley** [kaskr/adcomp#207]
Is there a way to get the dimensions of an ADREPORTed object before it was vectorized?

**Comment by joethorley** [comment]
This issue is still causing me a great deal of frustration - any thoughts?

**Comment by kaskr** [comment]
How about

```cpp
REPORT(x);
ADREPORT(x);
```

```r
dim(obj$report()$x)
```

?

**Comment by joethorley** [comment]
Yes that works although having to include in REPORT is a wee bit of a hack

**Comment by joethorley** [comment]
I do appreciate your response (apologies if my previous comment seems ungrateful!)
