### ISSUE TITLE
simulate example sam.cpp

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#213]
It's nice that the simulate capabilities are in the master branch now. Also, `sam.cpp` from the simulate branch was a good example that I was using as a reference, but it got deleted with the branch. Can you put it back somewhere?

**Comment by kaskr** [comment]
Actually the `sam.cpp` example on the master branch does have the simulation code.

**Comment by mebrooks** [comment]
Sorry! I must have been looking at my fork. I'll figure out how to get it caught up.
