### ISSUE TITLE
suggestions for gdbsource and print.backtrace?

### ISSUE THREAD

**Issue by timjmiller** [kaskr/adcomp#217]
Hi all,
 
Perhaps these are dealt with better in some other way. If so, please ignore this. If not, here are 2 ideas for improving these functions:

1) it would be pretty easy to modify gdbsource to work the same way when the cpp and R files don't have the same: include an optional argument to gdbsource (e.g., cppname) and change:
        attr(txt, "file") <- file
to
        attr(txt, "file") <- cppname
with cppname defined previously as the same as the r file if not specified by the user. 

2) print.backtrace uses grep to looks for a line with "#0": 
    line <- grep("#0", x)
and must return a single value because it is used to subset the vector of lines of output:
    x <- x[line:length(x)]
however, if someone (like me) uses a comment in the R code starting with "#0..." it returns more than one number and then doesn't work. If you want to keep using the same grep call for "line", then changing to 
    x <- x[line[length(line)]:length(x)]
should work since the last occurrence should always be in the gdb output.
 
Thanks for creating this package,
Tim

**Comment by kaskr** [comment]
Should be fixed
