### ISSUE TITLE
Misleading documentation for ADREPORT

### ISSUE THREAD

**Issue by tcwain** [kaskr/adcomp#218]
A minor issue with documentation. The docs for the ADREPORT macro say:

> Report scalar, vector or array back to R with derivative information.
> The result is retrieved in R via the R function sdreport(). 

which implies that it might return an array to R, but it does not. It returns a vector, so that the calling R code has to keep track of the array dimensions and reshape it.

Suggest changing the second line to:
> The vectorized result is retrieved in R via the R function sdreport().

(This also relates to issue #207 .)

**Comment by skaug** [comment]
I have made an attempt to give the user a warning about this in the "documentation" branch.
