### ISSUE TITLE
e+233 appearing in vector<Type> v(n) instead of 0 by default

### ISSUE THREAD

**Issue by DanOvando** [kaskr/adcomp#223]
Having a strange outcome when trying to create a vector of zeros. 

from `help("Template`, to produce a vector of length `n1`
```
vector<Type> v(n1);	R equivalent of v=numeric(n1)
```

in R, `numeric(10)`

```
numeric(10)
 [1] 0 0 0 0 0 0 0 0 0 0
```

Running in TMB

```
 int n=10;
 vector<Type> v(n);

std::cout<< v << "\n";
```
Produces

```
0.000000e+00 1.288230e-231 2.470328e-323  0.000000e+00 2.217802e-314
 [6] 4.969642e+223 1.714401e+161 2.217554e-314 2.217811e-314 7.384064e-309
```

The process is stochastic as well, in that every time I run the model I get a different vector of 10 numbers in v. Seems to be a memory pointer issue maybe?

The first entry is zero, but the rest are all over the board, including a fun `e+233`

Understood that I can fill the vector in with zeros manually, but this was causing some odd behavior when I assumed that values that I didn't fill in manually were zeros, so just trying to understand if this is normal. 

Any thoughts if this is just the nature of the beast, or is this a bug with TMB/my compiler?

```
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          3.2                         
year           2016                        
month          10                          
day            31                          
svn rev        71607                       
language       R                           
version.string R version 3.3.2 (2016-10-31)
nickname       Sincere Pumpkin Patch   
```

System information
```
version 
"Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64" 
                    
```
TMB version 1.7.7
```

**Comment by mebrooks** [comment]
It's a good idea to initialize variables to zero using `setZero` (documented [here](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#af230a143de50695d2d1fae93db7e4dcb)) unless they will surely get initialized elsewhere in the code.  Otherwise they can be filled with garbage as you're seeing. It's just a feature of C++, but it also depends on the compiler.

**Comment by DanOvando** [comment]
Thanks @mebrooks, sorry for the apparently simple question!
