### ISSUE TITLE
RTools update directory structure incompatible with TMB

### ISSUE THREAD

**Issue by mkapur** [kaskr/adcomp#224]
Hi, 
I found an error that will happen when users install the newest version of RTools. This update instead creates a folder in C: called "RBuildTools", with a subfolder "3.3" which contains bin, gcc-4.6.3, etc. 

The TMB test code throws errors such as c:/Rtools/mingw_64/bin/g++ not found; I had to rename the RBuildTools folder to RTools and migrate all subfolders out of "3.3". If there is a way to ensure that TMB searches for both RBuildTools/3.3/ and RTools, this workaround would be unnecessary.

MK

**Comment by kaskr** [comment]
OK, the `install_windows.R` script seems to be outdated. I'm tempted to deprecating this way of installing as it seems to cause unnecessary trouble. The [CRAN installation approach](https://github.com/kaskr/adcomp/wiki/Download) seems to work well on Windows now and would not have the problem you describe ?

**Comment by mkapur** [comment]
Thanks for the quick reply. I should've mentioned that I am on a government machine and need special permissions for every installation step; the protocol I followed is outlined [here](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Steps-to-install-TMB). In general/for personal comp. users, I think the CRAN approach would probably have less hurdles.

MK
