### ISSUE TITLE
Eigen/Dense in CRAN vs install_windows.R

### ISSUE THREAD

**Issue by daliakopoulos** [kaskr/adcomp#230]
Hello,

When installing through CRAN all seems to work but then I get a 
 
"fatal error: Eigen/Dense: No such file or directory" 

in TMB.hpp when trying to install other packages that require TMB (e.g. cavios/tshydro). When I install from source using install_windows.R (after updating the RTools vs RBuildTools problem) tsHydro works fine.

Cheers,
YD

**Comment by kaskr** [comment]
The error `Eigen/Dense: No such file or directory` with the CRAN
install indicates that the package `RcppEigen` is missing on your
system.

**Comment by daliakopoulos** [comment]
Hello, RcppEigen is there, something else must be wrong

**Comment by kaskr** [comment]
What output do you get from:
`system.file("include", package = "RcppEigen")`
?

**Comment by daliakopoulos** [comment]
C:/[...]/R/win-library/3.4/RcppEigen/include

**Comment by kaskr** [comment]
In that case the problem is with the `tshydro` package (`DESCRIPTION` file).
See https://github.com/kaskr/adcomp/wiki/Development under 'Distributing code'.
