### ISSUE TITLE
Does the map-function work for matrices?

### ISSUE THREAD

**Issue by JensWahl** [kaskr/adcomp#235]
Hello, 

I'm trying to apply a the map function to a matrix of parameters (upper triangular  part need to be zero), but  it does not seem to work. 

I have only tried it for a 2x2 matrix and I have tried the following: 
map <- list(matrix(2,2) = factor(NA)) and
map <- list(matrix = factor(matrix(c(1,2,NA,4),nrow = 2, ncol = 2))),

but both gives an error. 

Is there a solution to this problem? 

Thanks in advance! 

Jens

**Comment by kaskr** [comment]
See #14
