### ISSUE TITLE
False convergence of structured time series model!

### ISSUE THREAD

**Issue by ben-mhamed** [kaskr/adcomp#237]
Hi everyone,
I'm trying to fit a structured time series model with TMB but i can't get convergence. can anyone please help me. The model equation are is number 3 [here](http://people.ischool.berkeley.edu/~hal/Papers/2013/pred-present-with-bsts.pdf)
here is the code i write.
Thank in advance

`
DATA_INTEGER(nobs);
DATA_INTEGER(nSeasons);
DATA_VECTOR(month);
PARAMETER(U);  // Considered as random effect

// Take care of the state equation
vector<Type> trend_intercept(nobs);
vector<Type> trend(nobs);
matrix<Type> season(nSeasons,nobs);

// Local Linear Trend and its intercept

for(int i=0;i<nobs;i++){
  trend(i) = U(0,i);
  trend_intercept(i) = U(1,i);
}

// Seasonality

for(int i=0;i<(nSeasons-1);i++){
  for(int j=0;j<nobs;j++){
    season(i,j) = U(i+2,j);
  }
}
for(int i=0;i<nobs;i++){
  season((nSeasons-1),i)=0.0;
  for(int j=0;j<(nSeasons-1);j++){
    season((nSeasons-1),i)+=-season(j,i);
  }
}

Type sdTrend = exp(LogSdState(0));
Type sdTrend_intercept = exp(LogSdState(1));
Type sdSeason = exp(LogSdState(2));

for(int i=1;i<nobs;i++){
  ans+= -dnorm(trend_intercept(i),trend_intercept(i-1),sdTrend_intercept,false);
}
for(int i=1;i<nobs;i++){
  ans+=-dnorm(trend(i),trend(i-1)+trend_intercept(i-1),sdTrend,false);
}

matrix<Type> corSeason(nSeasons,nSeasons);
matrix<Type> varSeason(nSeasons,nSeasons);
vector<Type> sdSeasons(nSeasons);

for(int i=0;i<(nSeasons-1);i++){
  sdSeasons(i) = sdSeason;
  for(int j=0;j<nSeasons;j++){
    if(i!=j){corSeason(i,j)=rho;}else{corSeason(i,j)=1.0;}
  }
}
for(int i=0; i<nSeasons; ++i){
  for(int j=0; j<nSeasons; ++j){
    varSeason(i,j)=sdSeasons(i)*sdSeasons(j)*corSeason(i,j);
  }
}

using namespace density;
MVNORM_t<Type> neg_log_densityF(varSeason);
for(int i=1;i<nobs;i++){    
  ans+=neg_log_densityF(season.col(i)-season.col(i-1)); 
}

// Take care of observations
Type sdObs = exp(logSdObs);
vector<Type> predSales(nobs);
vector<Type> regressors(nobs);
for(int i=0;i<nobs;i++){
  // Regression equation
  regressors(i) = beta1*X1(i) + beta2*X2(i) + beta3*X3(i) + beta4*X4(i) + 
                  beta5*X5(i) + beta6*X6(i) + beta7*X7(i) + beta8*X8(i);

  // Match to observations : Local linear trend + seasonality + regression equation
  y_pred(i) = trend(i) + season(month(i)-1,i) +regressors(i);
  ans+= -dnorm(y(i),y_pred(i),sdObs,false);
}

return ans;`

**Comment by casperwberg** [comment]
I think this question belongs in the TMB-users google group [https://groups.google.com/forum/#!forum/tmb-users](url) . Posting the R-code and data would also be helpful.
