### ISSUE TITLE
Compilation Failure

### ISSUE THREAD

**Issue by ballengerj** [kaskr/adcomp#250]
I am trying to install and use the TMB package but I keep getting an error when trying to run the example using the code:

`runExample(all = TRUE)` (similar error when I run `source("sam.R")`)

Building example ar1xar1 
c:/Rtools/mingw_64/bin/g++  -I"C:/Program Files/R/R-3.3.2/include" -DNDEBUG -IC:/Users/ballengerj/Documents/R Packages/TMB/include -IC:/Users/ballengerj/Documents/R/Library/RcppEigen/include  -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_ar1xar1  -DTMB_LIB_INIT=R_init_ar1xar1    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c ar1xar1.cpp -o ar1xar1.o
g++.exe: error: Packages/TMB/include: No such file or directory
make: *** [ar1xar1.o] Error 1
Error in compile(paste0(name, ".cpp"), ...) : Compilation failed
In addition: Warning message:
running command 'make -f "C:/Program Files/R/R-3.3.2/etc/x64/Makeconf" -f "C:/Program Files/R/R-3.3.2/share/make/winshlib.mk" -f "C:\Users\ballengerj\AppData\Local\Temp\RtmpyQFxxG\file18f89446d4d" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="ar1xar1.dll" WIN=64 TCLBIN=64 OBJECTS="ar1xar1.o"' had status 2 
Timing stopped at: 0.01 0 0.22 

I've tried to diagnose the issue from the answers to several similar threads to no avail.

Here are the results of the following diagnostics:

`system("gcc -v")`

Using built-in specs.
COLLECT_GCC=C:\Rtools\mingw_64\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/Rtools/mingw_64/bin/../libexec/gcc/x86_64-w64-mingw32/4.9.3/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-4.9.3/configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --prefix=/mingw64 --with-sysroot=/home/Jeroen/mingw-gcc-4.9.3/x86_64-493-posix-seh-rt_v3-s/mingw64 --with-gxx-include-dir=/mingw64/x86_64-w64-mingw32/include/c++ --enable-static --disable-shared --disable-multilib --enable-languages=c,c++,fortran,lto --enable-libstdcxx-time=yes --enable-threads=posix --enable-libgomp --enable-libatomic --enable-lto --enable-graphite --enable-checking=release --enable-fully-dynamic-string --enable-version-specific-runtime-libs --disable-isl-version-check --disable-cloog-version-check --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-bootstrap --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-gnu-as --with-gnu-ld --with-arch=nocona --with-tune=core2 --with-libiconv --with-system-zlib --with-gmp=/home/Jeroen/mingw-gcc-4.9.3/prerequisites/x86_64-w64-mingw32-static --with-m... <truncated>
Thread model: posix
gcc version 4.9.3 (x86_64-posix-seh, Built by MinGW-W64 project) 

`shell('where gcc')`

C:\Rtools\mingw_64\bin\gcc.exe

`shell('where make)`

C:\Rtools\bin\make.exe

`shell('where R')`

C:\Program Files\R\R-3.3.2\bin\x64\R.exe

When I run the example simple it seems to work fine, but nothing else seems to work.

**Comment by kaskr** [comment]
`g++` thinks you are specifying two different paths here:
`-IC:/Users/ballengerj/Documents/R Packages/TMB/include`

This is because your package folder name has a space.
Installing TMB to a folder without spaces should solve the problem.

**Comment by ballengerj** [comment]
Thanks, I figured it was something simple but was having a hard time figuring it out. The whole space thing has caused me problems in the past, but I keep forgetting about it.

**Comment by ballengerj** [comment]
It is working fine now!
