### ISSUE TITLE
http://tmb-project.org. (with ending period)

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#252]
On [this page](https://arxiv.org/abs/1509.00660) the link in the text "this http URL" sometimes goes to [this](http://tmb-project.org.) website. After I went to http://tmb-project.org a few times, it looks like my browser "learned" not to go to http://tmb-project.org. anymore.

**Comment by mebrooks** [comment]
Now I can't repeat the behavior, even in a Chrome incognito window, but I swear, there was another web site there. It had a dark blue background with a list of links that included "Scientific Project Planning", and "Microsoft Projects". It looked commercial.

**Comment by the-sushi** [comment]
Well, the href is to `http://tmb-project.org` to me, so it was either a user, browser, or arXiv issue.
