### ISSUE TITLE
Out of range error in MakeADFun

### ISSUE THREAD

**Issue by cf48** [kaskr/adcomp#254]
I'm a new TMB user and I'm getting the out-of-range error  

> TMB has received an error from Eigen. The following condition was not met:
> row >= 0 && row < rows() && col >= 0 && col < cols()
> Please check your matrix-vector bounds etc., or run your program through a debugger.

when executing MakeADFun.  I can't see any error in my C++ code, and neither gdbsource (recommended in the [TMB guide](http://kaskr.github.io/adcomp/_book/Errors.html#compilation-errors)) nor debug seem useful.  

Any suggestions?

Here is my R code:
 ```
library(TMB)
compile("AMSFcTagOnly2pars.cpp")
dyn.load(dynlib("AMSFcTagOnly2pars"))
qp <- list(bpar=-4,lnArand=rep(0,10))
qd <- list(GrowIncDat=matrix(c(112,106,106,102,99,126,112,118,109,96,120,107,115,135,168,132,118,135,112,167,0.245548,0.177283,0.35,1.21011,2.93887,0.500436,0.20941,0.744578,0.152789,2.76643),ncol=3))
qo <- MakeADFun(data=qd, parameters=qp, random = "lnArand",DLL = "AMSFcTagOnly2pars")
```
and here is my C++ code:
```
// AMSFc for tag data only (no shrinkage or age-length data)
// and fixing all pars except bpar and Arand
#include <TMB.hpp>

template<class Type>
Type objective_function<Type>::operator() () {
  // data:
  DATA_MATRIX(GrowIncDat);
  int numGrowIncDat = GrowIncDat.rows();   // number of tagging obs  

  // PARAMETERS:
  PARAMETER(bpar); // Richards parameter b
  PARAMETER_VECTOR(lnArand); // ln(age at tagging) 

  // Fix non-estimated parameters
  int modelType =6; // 5 = VBSchnute; 6 = Richardsab 
  Type Aa=1.;
  Type Ab=15.;
  Type tagLambda=1.;
  Type reLambda=1.;
  Type La=55.; // mean length at age Aa
  Type Lb=253.; // mean length at age Ab
  Type kpar=0.17; // von Bertalanffy k
  Type Lsda=4.7; // sd at age Aa
  Type Lsdb=253.; // sd at age Ab  
  Type rhor0=0.93; // correlation when tagging time increment = 0
  Type rhok=2.; // exponential rate parameter for tagging correlation  
  Type lnRandMean=0.48; // mean of random effects
  Type lnRandSd= -1.3; // sd of random effects
  // procedures: (transformed parameters)
  vector<Type> Arand = exp(lnArand);
  Type randSd = exp(lnRandSd);
  
  // reports on transformed parameters:  DON'T YET KNOW WHAT I WANT HERE
  //ADREPORT(sigma_proc)
  //ADREPORT(sigma_obs)

  Type rhot50=log(rhor0/(1.-rhor0))/rhok;
  Type L2recBias=0.; // measurement bias must be zero without shrinkage data
  Type L1tagPred;
  Type L2recPred;
  Type L1tagSd;
  Type L2recSd;
  Type tagrho;
  Type tagRes1;
  Type tagRes2;
  Type tagLike;
  Type penRand;
  Type Linf;
  Type tzero;

  if(modelType==6)  // Richardsab
    {
      tzero=(1/kpar)*log(bpar*(pow(Lb,1.0/bpar) - pow(La,1.0/bpar))/
			      (pow(La,1.0/bpar)*exp(-kpar*Aa)-pow(Lb,1.0/bpar)*
			       exp(-kpar*Ab)));
      Linf=La*pow(1.0 + (1.0/bpar)*exp(-kpar*(Aa-tzero)),bpar);
    }

  // Initialise objn
  Type objn = 0.0;
  for(int i = 0; i < numGrowIncDat; i++){
    // calculate predicted lengths at tagging and recapture
    if(modelType==5)   // VBSchnute
      {
	L1tagPred=La + (Lb-La)*(1-exp(-kpar*(Arand[i]-Aa)))/
	  (1-exp(-kpar*(Ab-Aa)));
	L2recPred=La + (Lb-La)*
	  (1-exp(-kpar*(Arand[i]+GrowIncDat(i,3)-Aa)))/
	  (1-exp(-kpar*(Ab-Aa)));
      }
    if(modelType==6)   // Richardsab
      {
	L1tagPred=Linf*pow(1.0+(1.0/bpar)*exp(-kpar*(Arand[i]-tzero)),-bpar);
	L2recPred=Linf*pow(1.0+(1.0/bpar)*
			   exp(-kpar*(Arand[i]+GrowIncDat(i,3)-tzero)),-bpar);
      }
    // Calculate sd of lengths at tagging and recapture
    L1tagSd=Lsda + (Lsdb - Lsda)*(L1tagPred - La)/(Lb - La);
    L2recSd=Lsda + (Lsdb - Lsda)*(L2recPred - La)/(Lb - La);
    // Calculate likelihoods for lengths at tagging and recapture
    tagrho=1-1/(1+exp(-rhok*(GrowIncDat(i,3),-rhot50)));
    tagRes1=(GrowIncDat(i,1)-L1tagPred)/L1tagSd;
    tagRes2=(GrowIncDat(i,2)-(L2recPred+L2recBias))/L2recSd;
    tagLike = log(L1tagSd)+log(L2recSd)+ 0.5*log(1-pow(tagrho,2))+
      0.5*(pow(tagRes1,2)+pow(tagRes2,2)-
	   2*tagrho*tagRes1*tagRes2)/(1-pow(tagrho,2));
    // Calculate penalty for Arand
    penRand = 0.5*pow((lnArand[i]-lnRandMean)/randSd,2)+lnRandSd;
    // Add to objective function
    objn += tagLike*tagLambda + penRand*reLambda;
  }
return objn;
}
```

**Comment by kaskr** [comment]
`?gdbsource` says:

*  On Linux/OS X use `compile(cppfile,"-O0 -g")`.
*  On Windows use `compile(cppfile,"-O1 -g",DLLFLAGS="")` (lower optimization level will cause errors).

On Linux I used `compile("AMSFcTagOnly2pars.cpp", "-O0 -g")` and got from `gdbsource("AMSFcTagOnly2pars.R")`:

```
#3  0x00007fffee0c61a2 in objective_function<double>::operator() (this=0x7fffffffada0) at AMSFcTagOnly2pars.cpp:76 
```

I.e. problem is in line 76:

```
			   exp(-kpar*(Arand[i]+GrowIncDat(i,3)-tzero)),-bpar);
```

**Comment by cf48** [comment]
Many thanks for a quick and helpful response.  I've now realised that the out-of-range error was because, when I translated my code from ADMB, I forgot to change the column references in GrowIncDat from 1-3 to 0-2.  With that correction my code runs.

However, what I don't understand is why 
```
gdbsource("AMSFcTagOnly2pars.R")
```
didn't work for me.  When I tried to replicate the steps above (which are the same as I'd done originally), the output I got was still the unhelpful
```
 Error in line:length(x) : argument of length 0
```
(this seems to refer to MakeADFun, which contains "length(x)", whereas my code doesn't) rather than the helpful reference to line 76.

**Comment by kaskr** [comment]
Getting debugging working on Windows may be tricky. Perhaps you can find help in previous issues:

https://github.com/kaskr/adcomp/issues?utf8=%E2%9C%93&q=is%3Aissue+gdbsource

**Comment by cf48** [comment]
Actually, I'm working in Linux: Ubuntu16.04LTS

**Comment by kaskr** [comment]
In that case

https://github.com/kaskr/adcomp#issues-with-library-unloading

should solve your problem.

**Comment by cf48** [comment]
Well, that fixes the library unloading problem (thanks), but not the gdbsource problem.

I ran `readelf -s mymodel.so | grep UNIQUE` and confirmed your suspicion that I have a library unloading problem.  So, I created `~/.R/Myvars` with the line `CXX = g++ -fno-gnu-unique`, compiled and loaded my C++ code and reran `readelf -s mymodel.so | grep UNIQUE` and found the library unloading problem had gone.

I then put the out-of-bounds error back in my C++ code, ran `compile("AMSFcTagOnly2pars.cpp", "-O0 -g")` and then `gdbsource("AMSFcTagOnly2pars.R")` and got the same unhelpful output: `Error in line:length(x) : argument of length 0`

**Comment by kaskr** [comment]
We are on the exact same operating system so I'm surprised it doesn't work.
Could you try this:

1. Verify from command line that `R --slave < AMSFcTagOnly2pars.R` gives the out-of-bounds error.
2. Run debugger manually: `R -d gdb` => `run` => `source("AMSFcTagOnly2pars.R")` => `bt`.
   Did you get the backtrace ? Line `#3` should be the same as I previously posted.
3. Now do the same thing using `gdbsource`. From command line `R` => `TMB::gdbsource("AMSFcTagOnly2pars.R",TRUE)`.
   Did you get the backtrace ?

**Comment by cf48** [comment]
All that seemed to work as you expected:

From 1 I got the out-of-bounds-error
```
TMB has received an error from Eigen. The following condition was not met:
row >= 0 && row < rows() && col >= 0 && col < cols()
Please check your matrix-vector bounds etc., or run your program through a debugger.
```
From both 2 and 3 I got the backtrace, and line #3 was as you'd got (with the reference to AMSFcTagOnly2pars.cpp:76)

**Comment by kaskr** [comment]
To summarize, you've found that `TMB::gdbsource("AMSFcTagOnly2pars.R",TRUE)` works but not `TMB::gdbsource("AMSFcTagOnly2pars.R")` ? (please try both)

**Comment by cf48** [comment]
No, both work.  

The second produces only a single line of output
```
#3  0x00007fffedc1d11e in objective_function<double>::operator() (this=0x7fffffffae60) at AMSFcTagOnly2pars.cpp:76
```
whereas the first produces heaps of output, including the above line.

**Comment by kaskr** [comment]
Now I'm confused... both work ? That means there wasn't a `gdbsource` problem in the first place ???

For future reference it might be useful if you could point out what made the problem go away.

**Comment by cf48** [comment]
Sorry, I should have been clearer.  My usual way of running R is within emacs, using ESS.  It is in this environment that I have been, and am still, getting the `Error in line:length(x) : argument of length 0` output from `gdbsource("AMSFcTagOnly2pars.R")'.  

In your message of 2 days ago (with things for me to try numbered 1, 2, 3) I understood that I should do these from a terminal (rather than in emacs) and so that's what I did.  The same is true for my response to your next message.
