### ISSUE TITLE
AD Studio version 1.0

### ISSUE THREAD

**Issue by arni-magnusson** [kaskr/adcomp#257]
Dear ADMB/TMB developers and users,

I have just released AD Studio 1.0, the next generation of ADMB-IDE and TMB-IDE, combined in one!

Main features:

- Dedicated environment for developing ADMB and TMB models
- Uses the C++ compiler from Rtools
- Based on the Emacs editor, but with simplified keybindings
- Especially good support for R, LaTeX, Markdown, GDB, and Git
- Flexible layout to arrange multiple files on screen

It includes the newest version of all components (ADMB 12.0, Emacs 25.3, Rtools 3.4, etc.) and should fit well on a machine that already has a combination of R, TMB, Rtools, RStudio, and so on. Your feedback is appreciated.

Download information and user manual can be found on the AD Studio website:

https://github.com/admb-project/adstudio

All the best,

Arni

**Comment by the-sushi** [comment]
(Given that this is two years old, I presume it qualifies as being old enough news to be closed)
