### ISSUE TITLE
"file name" spaces and distribution

### ISSUE THREAD

**Issue by reedssorenson** [kaskr/adcomp#260]
Hi, 
I have built a package using TMB objective functions. It works great and the computation is way more efficient than the R functions I used previously. I would like to submit it to Bioconductor. I have tested the package on linux, mac, and windows 10 (64-bit), all worked fine. 

I decided to check it on a Windows Vista (32-bit) machine and I ran into a simple problem that I am having a hard time solving. R packages are installed into "C:/Program Files/R/R-3.4.3/library/[packagename]" on this machine. When I use TMB::compile("C:/Program Files/R/R-3.4.3/library/[packagename]/src/obj_func.cpp") the space between "Program Files" causes it to fail: 
"make: Circular C:/Program <- C:/Program dependency dropped." ...

I am distributing the ".cpp" files in a 'inst/src' folder and requiring the user to compile them using TMB::compile() after installation of the package to avoid the more complicated install with compilation, however, it seems that anyone with an older Windows machine is going to be out of luck with this standard windows configuration.

Things I've tried without success: 
- backslash before the space, e.g., compile("C:/file\ name/blah/blah/blah.cpp") 
- compile(shortPathName("C:/file name/blah/blah/blah.cpp"))
- escaped double quotes around the file name passed to compile, e.g., compile("\"C:/file name/blah/blah/blah.cpp\"")

Is there anything I can do? (e.g. some compile flag?, or some change the compile function to wrap quotes around the ".cpp" file name in the make file? or something else?)
Thanks! 
Reed
FYI, I am a Biologist that knows R but very little about C++ and the compiling process, so I really appreciate the TMB package.

**Comment by kaskr** [comment]
To avoid spaces in the makefile target try this:

```
setwd("path_with_spaces")
TMB::compile("obj_func.cpp")
```

**Comment by reedssorenson** [comment]
Thank you! So simple. :)

**Comment by smartell** [comment]
Try c:\\
