### ISSUE TITLE
private `solveSubset` function

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#263]
As always, thank you so much for the amazing software!  

Are you willing to make the internal function `solveSubset` a private function instead, such that it could be called using `TMB:::solveSubset`?  It could then be used externally e.g., by package `VAST` to explore the spatial covariance of the SPDE smoother, but being private it would hopefully not require any additional documentation

**Comment by kaskr** [comment]
@James-Thorson 
`TMB:::solveSubset` is now added.
