### ISSUE TITLE
Generic method to determine index in `phi` using name of derived quantity

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#265]
Kasper (and @curryc2) ,

Sorry for the many questions, I'm trying to test the speedups we discussed last week.

In VAST, I want to bias-correct a derived quantity `Total_Abundance` but get the standard error for `log_Total_Abundance`.  Doing the epsilon method for `log_Total_Abundance` is dense, hence it would be nice to use the `bias.correct.control = list( split=X)` feature to indicate that I want the epsilon method for `Total_Abundance` but not `log_Total_Abundance`.  However, they are both vectors whose length depends upon the specifics of the model.  

Is there any generic way to check what indices to pass to `split` to obtain all elements of a named object in `ADREPORT` without calling `sdreport` without bias-correction, checking the row names, and then running it again?

Jim

**Comment by James-Thorson** [comment]
Just to make this a bit more clear...

.. I think it would be useful to have a way to interface efficiently with `bias.correct.control` where the user specifies a character vector `BiasCorrNames` naming the `ADREPORT` variables that they want to bias correct.  I can then implement this as:

```R
# First SD run to extract indices
h <- optimHess(Opt$par, Obj$fn, Obj$gr)
SD = sdreport( obj=Obj, par.fixed=Opt$par, hessian.fixed=h )

# Determine indices
Which = which( rownames(summary(SD,"report")) %in% BiasCorrNames )
Which = split(seq_along(Which), cut(seq_along(Which), nsplit) )
Which = Which[sapply(Which,FUN=length)>0]

# Repeat SD with indexing
SD = sdreport( obj=Obj, par.fixed=Opt$par, hessian.fixed=h, bias.correct=TRUE, bias.correct.control=list(sd=FALSE, split=Which, nsplit=NULL) )
```

However, this implementation requires two calls to `sdreport` and is wasting computation time in the first call.  It could be circumvented if I knew how to calculate `Which` directly from `Obj`.

**Comment by kaskr** [comment]
@James-Thorson 
One can now use `obj$env$ADreportIndex()` to get available ADREPORTed indices.

**Comment by James-Thorson** [comment]
Thanks!

You can see where this is used in `TMBhelper::Optimize` to allow users to specify which ADREPORT variables to bias-correct by name, at https://github.com/kaskr/TMB_contrib_R/blob/master/TMBhelper/R/Optimize.R.  I could see this functionality being worth merging into `TMB::sdreport` input `bias.correct.control` but understand if you chose not to do so.
