### ISSUE TITLE
Simultaneously evaluate function and its gradient?

### ISSUE THREAD

**Issue by mlysy** [kaskr/adcomp#269]
In a model with random effects, it seems that the Laplace approximation uses many steps which are common to evaluating both the function and its gradient (with random effects integrated out).  While the optimization routines provided by `optim` and `nlminb` have separate arguments for the function and gradient, `nlm` allows you to combine both into a single call.  Therefore, if the function and gradient can be computed more efficiently together than separately, `nlm` is more efficient (and in fact `nlminb` is now depreciated for this reason).

So, is TBM able to calculate both the function and its gradient simultaneously?

**Comment by calbertsen** [comment]
You can use the `random.start` argument to `MakeADFun` to change the starting values in the inner optimization. By default, the parameter values that gave the best likelihood so far are used.

Therefore, in this code:
```r
library(TMB)
runExample("ar1xar1")
obj$fn(obj$par)
obj$gr(obj$par)
```
The Laplace approximation is needs about four steps in both obj$fn and obj$gr - it will always start the inner optimization at the values corresponding to the MLE.

If you create the object by:
```r
obj <- MakeADFun(obj$env$data, 
                 obj$env$parList(), 
                 random = c("eta"), 
                 random.start = expression(last.par[random]), 
                 DLL ="ar1xar1")
```
the last optimum is re-used, and 
```r
obj$fn()
obj$gr()
```
will only do the optimization in obj$fn.

To use `nlm` for optimization, you can create a wrapper function like this:
```r
newFn <- function(par){
    r <- obj$fn(par)
    attr(r,"gradient") <- obj$gr()
    return(r)
}
```

**Comment by mlysy** [comment]
This is *exactly* what I was looking for, thanks ! !

Of possible interest, we've run some speed/stability comparisons between `nlm` and `nlminb` for a high-dimensional stochastic volatility model, similar to the one [here](https://www.sciencedirect.com/science/article/pii/S0167947313003587).  While the technique above is 1.25-2x faster for `nlm`, optimization was still a bit slower than with `nlminb` (for which applying the technique seems to make no difference).  Moreover, for our particular application `nlminb` generated fewer warnings, and optimization results were about the same.
