### ISSUE TITLE
Issues with library unloading

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [kaskr/adcomp#27]
From the main page:

On recent versions of gcc the following problem may be encountered: When the user cpp file is changed, re-compiled 
and re-loaded, the changes does not take place. To see if you are affected by this issue, assuming your compiled DLL
 is called "mymodel.so", try running:

```
readelf -s mymodel.so | grep UNIQUE
```

If this gives a lot of output it is not possible to unload the library, and R will have to be restarted every time 
## the model is re-compiled. A workaround is to use clang++ instead of gcc.

The following works for me using gcc in both Windows and Linux:

 Initially, first look that mymodel.so (mymodel.dll in Windows) is loaded:
 getLoadedDLLs()

In practice, just run the following to unload mymodel.so (mymodel.dll), without the need to restart R:

  # Clear dyn.load'ed files
  dyn.unload(dynlib("mymodel"))  # First attempt
  gc() # Garbage Collection
  dyn.unload(dynlib("mymodel")) # Second attempt
  getLoadedDLLs()  #Verify that second attempt works

-John

**Comment by torarneoigard** [comment]
Hi, I have the same problem. I downloaded and installed current version of TMB. I have tried R 3.1.2 and 3.2.1 on Ubuntu 15.04. If I make changes in the cpp-file, recompile and run

dyn.load(dynlib("fname"))
obj <- MakeADFun(data,parameters,random = c("x1","x2"),DLL="fname")

The changes are not included. If I quit R, save work space, start R again, reload the library and running the lines above the changes are included. Is there a better way of doing this? On OS X I do not have this problem.

**Comment by bchasco** [comment]
The issue may have been solved for windows machines, but based on earlier
problems I've always just included the following at the top of my compile
scripts.  It doesn't add anytime to the process.

    #updating the cpp file
    res = try(dyn.unload(file))
    #just delete the .o file to make sure changes are added
    if(file.exists("file.o"))
        shell("del file.o"))
    #compile
    compile("file.cpp")
    #load
    dyn.load(file)


On Fri, Dec 4, 2015 at 5:21 AM, torarneoigard <notifications@github.com>
wrote:

> Hi, I have the same problem. I downloaded and installed current version of
> TMB. I have tried R 3.1.2 and 3.2.1 on Ubuntu 15.04. If I make changes in
> the cpp-file, recompile and run
>
> dyn.load(dynlib("fname"))
> obj <- MakeADFun(data,parameters,random = c("x1","x2"),DLL="fname")
>
> The changes are not included. If I quit R, save work space, start R again,
> reload the library and running the lines above the changes are included. Is
> there a better way of doing this? On OS X I do not have this problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kaskr/adcomp/issues/27#issuecomment-161966618>.
>



-- 


Brandon Chasco

**Comment by kaskr** [comment]
This issue only exists on *Linux* with the *gcc* compiler - see the
README under 'Issues with library unloading' (the problem described by
@bchasco is different and has been resolved long ago).

Recommended solution: Add ```CXX = g++ -fno-gnu-unique``` to a file
```~/.R/Makevars``` (create it if it doesn't exist).
Check that you have solved the problem by running (from command line)
```readelf -s fname.so | grep UNIQUE``` after compilation. (Should
give no output)

**Comment by torarneoigard** [comment]
Thanks for this, it worked! :)
