### ISSUE TITLE
How to condition on a parameter

### ISSUE THREAD

**Issue by Zednathan** [kaskr/adcomp#270]
Sorry, could some experts answer my question?
In TMB c++ template, I need to condition on some parameters. For example,
  PARAMETER(x);  
  Type y = 10;
  for(int i = 0;i < x;++i){ 
     y = i;
  }
    return y;

However, in TMB documents it says "Do not use if(x) if x is a PARAMETER, or is derived from a parameter. TMB will remove the whole if-statement and hence produce surprising results."
My question is how to make the above code work.
Thank you very much.

**Comment by smartell** [comment]
Looks like your trying to estimate x as an integer.

**Comment by Zednathan** [comment]
Thank you very much for your prompt reply.
Here I just give a simple example. For this program, TMB will always give 0, no matter what x is, because x is a parameter. I want to know how I can make this program give correct result when I change the parameter value x.

**Comment by bradbell** [comment]
I think that TMB will support the CppAD Integer function; see
https://coin-or.github.io/CppAD/doc/integer.htm

**Comment by Zednathan** [comment]
Hi, Steve
I saw your second comment. Thank you very much. However, when I use the Integer function, TMB gives strange results. This may be because Integer(x) condition on parameter x internally, then TMB compiler removes the condition statements, I guess. My programs are as follows:
C++ template:
 #include <TMB.hpp> 
#include <iostream>
# include <cppad/cppad.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{  
  DATA_VECTOR(age);  

  PARAMETER(x);  

  using CppAD::AD;
  using CppAD::Integer;
  Type j = Integer(x);
  return j;
}

R code:
library(TMB)

compile("test.cpp")  

dyn.load("test")
#dyn.unload("test")

parameters <- list( 
 x = 11.5
  )  

tmb.data = list(
  age = 1:100
)

error_r=try( ( obj <- MakeADFun(tmb.data,parameters, DLL="test", inner.control=list(maxit=10000,trace=F)) ), silent=TRUE )

obj$fn(200)

This last statement will always give 11 no matter the parameter value.
Thanks.

**Comment by calbertsen** [comment]
If you don't need the gradient (which doesn't really make sense for integer parameters anyways), you can get TMB to evaluate the C++ template using double variables.

For example:

C++ code (test.cpp):

```c++
#include <TMB.hpp>

template<class Type>
Type objective_function<Type>::operator()() {
  DATA_VECTOR(age);
  PARAMETER(x);

  if(!isDouble<Type>::value)
    Rf_error("Only works for doubles!");
  
  Type j = CppAD::Integer(x);

  return j;
}
```

R code:

```R
library(TMB)
compile("test.cpp")
dyn.load(dynlib("test"))

obj <- MakeADFun(data = list(age = 1),
                 parameters = list(x = 11.5),
                 type="Fun", ## Only create double version
                 DLL="test")

## Evaluate function at 11.5 using doubles
obj$env$f(c(11.5),type="double")
## Returns 11

## Evaluate function at -5.5 using doubles
obj$env$f(c(-5.5),type="double")
## Returns 5

## Evaluate function at 12.98 using doubles
obj$env$f(c(12.98),type="double")
## Returns 12

## Evaluate function at pi using doubles
obj$env$f(c(pi),type="double")
## Returns 3
```
