### ISSUE TITLE
error in running nan_error_ex.R

### ISSUE THREAD

**Issue by hummingeel** [kaskr/adcomp#272]
Dear TMB users,

I'm recently facing Na/Nan problem `In nlminb(model$par, model$fn, model$gr): NA/NaN function evaluation` after compiling my TMB code and I just found the example named nan_error_ex.R (for debugging purpose) from the following sites:

[https://kaskr.github.io/adcomp/Introduction.html](https://kaskr.github.io/adcomp/Introduction.html)
[https://github.com/kaskr/adcomp/blob/master/tmb_syntax/nan_error_ex.R](https://github.com/kaskr/adcomp/blob/master/tmb_syntax/nan_error_ex.R)

At first, I download the fenv.h file from the site and then inserted this the code:
`feenableexcept(FE_INVALID | FE_OVERFLOW | FE_DIVBYZERO | FE_UNDERFLOW);`
(of course, I also included fenv.h also by adding `#include<fenv.h>` to the next line of `#include<TMB.hpp>`)

Since the first trial did not work, I decided to try the example code (both nan_error_ex.R and nan_error_ex.cpp) from [https://github.com/kaskr/adcomp/tree/master/tmb_syntax](https://github.com/kaskr/adcomp/tree/master/tmb_syntax)
But the result was not different from the first trial: 

```
nan_error_ex.cpp: In member function 'Type objective_function<Type>::operator()()':
nan_error_ex.cpp:7:72: error: there are no arguments to 'feenableexcept' that depend on a template parameter, so a declaration of 'feenableexcept' must be available [-fpermissive]
   feenableexcept(FE_INVALID | FE_OVERFLOW | FE_DIVBYZERO | FE_UNDERFLOW); // Extra line needed
                                                                        ^
nan_error_ex.cpp:7:72: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
nan_error_ex.cpp: In instantiation of 'Type objective_function<Type>::operator()() [with Type = CppAD::AD<double>]':
C:/Users/POPDYN~1/DOCUME~1/R/WIN-LI~1/3.5/TMB/include/tmb_core.hpp:1106:7:   required from here
nan_error_ex.cpp:7:72: error: 'feenableexcept' was not declared in this scope
nan_error_ex.cpp: In instantiation of 'Type objective_function<Type>::operator()() [with Type = double]':
C:/Users/POPDYN~1/DOCUME~1/R/WIN-LI~1/3.5/TMB/include/tmb_core.hpp:1330:7:   required from here
nan_error_ex.cpp:7:72: error: 'feenableexcept' was not declared in this scope
In file included from C:/Users/POPDYN~1/DOCUME~1/R/WIN-LI~1/3.5/TMB/include/TMB.hpp:93:0,
                 from nan_error_ex.cpp:2:
```
What makes the errors keep popping up?

sessionInfo:
![image](https://user-images.githubusercontent.com/38339347/40292817-7d94c754-5d08-11e8-8609-c50bdb8d6098.png)

![image](https://user-images.githubusercontent.com/38339347/40292801-68711332-5d08-11e8-9e86-ed5b0eaf5c03.png)

It would be appreciated for any ideas about this issue!

**Comment by mebrooks** [comment]
This sounds like it might be a question for the [user group](https://groups.google.com/forum/#!forum/tmb-users).

**Comment by the-sushi** [comment]
^
