### ISSUE TITLE
Printing vectors and matrices in gdb; possible to write user contributed library?

### ISSUE THREAD

**Issue by skaug** [kaskr/adcomp#275]
When debugging C++ code, at the gdb command line, it is possible
to write "print i", where i is an integer. But, trying to print Type, vector<Type>, ...
produces output that is not very easy to read.

I imagine that it would be possible to add a .print() function to vector, matrix, array
classes to facilitate printing. Is is possible to put all of this in a user contributed
library, or does it have to go into the files where the classes are defined?

Or is there a much simpler way of printing from gdb?

**Comment by kaskr** [comment]
It seems there are at least two approaches. One uses [Python scripting with gdb](https://sourceware.org/gdb/onlinedocs/gdb/Python.html#Python). I found it by following this [SO question](https://stackoverflow.com/questions/25085465/using-gdb-with-eigen-c-library) which leads to a [python gdb script](https://bitbucket.org/eigen/eigen/src/8b18ff2c70289b47928ae75fdb89a6ac3d018e08/debug/gdb/printers.py?at=default&fileviewer=file-view-default). We might be able to get something like this working.

However, I think I prefer the second approach (to define some print methods as you suggest).
The following works for me. After the TMB include statement define something like:

```cpp
void print(vector<double> x) {
  std::cout << x;
}
void print(matrix<double> x) {
  std::cout << x;
}
void print(array<double> x) {
  x.print();
}
```

From gdb use as:

```
p print(x)
```

**Comment by skaug** [comment]
Thanks. The latter suggestion is working fine.
