### ISSUE TITLE
Lognormal poisson and vector memory issues

### ISSUE THREAD

**Issue by kvert-pre** [kaskr/adcomp#276]
Hi, 

I am fitting a lognormal poisson model on 15 species and it  looks like the object created by TMBhelper::Optimize is out of the vector memory limit. I am using on Mac OS a 64bit Rv4.5.0 with 16GB of RAM. Any advice on how to proceed ? 

Best
Katyana

**Comment by merrillrudd** [comment]
Hi Katyana, this happened to me once but I think it was for a non-TMB project. In R if you type the command 
`memory.limit()`
The default for mine is 16235. If you type
`memory.limit(50000)`
and then run your model with TMBhelper::Optimize, it may be able to save your results in the local environment. This worked for me the one time I had a similar issue, but it wasn't with TMB so I'm not sure if that will solve your specific issue. Good luck!

**Comment by kvert-pre** [comment]
Hi Merill,

Thank you for your suggestion. The command memory.limit() does not work for
Mac and the mac alternative did not work either. I ended up having to run
it on a online server. It was a RAM issue.

Best,
Katyana

**Comment by the-sushi** [comment]
(I know you already ran it online, but for future reference you can increase R's vector memory limit in .Renviron by changing R_MAX_VSIZE)
