### ISSUE TITLE
R 3.5.0, ubuntu 18.04, TMB + RcppEigen warnings, fatal error with linear regression example

### ISSUE THREAD

**Issue by albsim** [kaskr/adcomp#277]
fresh new install of ubuntu 18.04. -> ok

R 3.5.0 installed from this repo: 

    deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/

with secure apt key added by: 

    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

R installed correctly and working even launched from rstudio.
Trying to install `TMB` library, installation command from R console or terminal R in super user mode with this command (tried both and removed one before trying the second, so no possible conflict between user libraries and R libraries):

    install.packages("TMB",type = "source")

the installation starts, 
it install dependant packages (Rcpp,RcppEigen etcetera).
 
**during the installation/compiling of exactly RcppEigen the console starts to kicks like 10000 line of warnings (like if is missing some compiler link)**, this is the first line of which it deviates from normal installation: 

    ** R
    ** inst
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** installing vignettes
    ** testing if installed package can be loaded
    * DONE (Rcpp)
    * installing *source* package ‘RcppEigen’ ...
    ** package ‘RcppEigen’ successfully unpacked and MD5 sums checked
    ** libs
    g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"   -I../inst/include -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-O3QT2W/r-base-3.5.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppEigen.cpp -o RcppEigen.o
    In file included from ../inst/include/Eigen/Core:388:0,
                     from ../inst/include/Eigen/Dense:1,
                     from ../inst/include/RcppEigenForward.h:30,
                     from ../inst/include/RcppEigen.h:25,
                     from RcppEigen.cpp:22:
    ../inst/include/Eigen/src/Core/arch/SSE/PacketMath.h:60:39: warning: ignoring attributes on template argument ‘__m128 {aka __vector(4) float}’ [-Wignored-attributes]
     template<> struct is_arithmetic<__m128>  { enum { value = true }; };
                                           ^
    ../inst/include/Eigen/src/Core/arch/SSE/PacketMath.h:61:40: warning: ignoring attributes on template argument ‘__m128i{aka __vector(2) long long int}’ [-Wignored-attributes]
     template<> struct is_arithmetic<__m128i> { enum { value = true }; };
                                            ^
    ../inst/include/Eigen/src/Core/arch/SSE/PacketMath.h:62:40: warning: ignoring attributes on template argument ‘__m128d{aka __vector(2) double}’ [-Wignored-attributes]
     template<> struct is_arithmetic<__m128d> { enum { value = true }; };
                                            ^
    ../inst/include/Eigen/src/Core/arch/SSE/PacketMath.h:161:43: warning: ignoring attributes on template argument ‘Eigen::internal::Packet4f {aka __vector(4) float}’ [-Wignored-attributes]
     template<> struct unpacket_traits<Packet4f> { typedef float  type; enum {size=4, alignment=Aligned16}; typedef Packet4f half; };

these are the last lines of the install.package("TMB") command:

    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(4) double}’ [-Wignored-attributes]
                          >::type PacketReturnType;
                             ^~~~~~~~~~~~~~~~
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘class Eigen::DenseCoeffsBase<Eigen::Transpose<const Eigen::Block<const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, 1, -1, false> >, 0>’:
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:478:7:   required from ‘class Eigen::DenseCoeffsBase<Eigen::Transpose<const Eigen::Block<const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, 1, -1, false> >, 2>’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/DenseBase.h:41:34:   required from ‘class Eigen::DenseBase<Eigen::Transpose<const Eigen::Block<const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, 1, -1, false> > >’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/MatrixBase.h:48:34:   required from ‘class Eigen::MatrixBase<Eigen::Transpose<const Eigen::Block<const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, 1, -1, false> > >’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/Transpose.h:115:37:   required from ‘class Eigen::TransposeImpl<const Eigen::Block<const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, 1, -1, false>, Eigen::Dense>’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/Transpose.h:52:37:   required from ‘class Eigen::Transpose<const Eigen::Block<const Eigen::Block<Eigen::Block<Eigen::Map<Eigen::Matrix<double, -1, -1>, 0, Eigen::Stride<0, 0> >, -1, -1, false>, -1, -1, false>, 1, -1, false> >’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/ProductEvaluators.h:552:40:   [ skipping 22 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:816:7:   required from ‘void Eigen::PlainObjectBase<Derived>::_init1(const Eigen::DenseBase<ElseDerived>&) [with T = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; OtherDerived = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; Derived = Eigen::Matrix<double, -1, -1>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/Matrix.h:296:31:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; _Scalar = double; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/tmbutils/vector.hpp:93:22:   required from ‘tmbutils::matrix<Type>::matrix(T1) [with T1 = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; Type = double]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/expm.hpp:36:14:   required from ‘atomic::Block<Type> atomic::Block<Type>::inverse() [with Type = double]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/expm.hpp:180:17:   required from ‘matrix_pade atomic::expm(matrix_pade) [with matrix_pade = atomic::nestedTriangle<0>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/expm.hpp:192:52:   required from here`
 
the last line of output from install.packages("TMB",type="source") is:

    g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o simple.so simple.o -L/usr/lib/R/lib -lR
    Build time 16.121 seconds
    
    * DONE (TMB)

   
the installation seems to finish (console gives * DOME(TMB) at the end), but running a basic example of TMB (linear regression) gives fatal R session error.

example in R code:

    tmb_model <- "
    // linear regression
    #include <TMB.hpp>
    
    template<class Type>
    Type objective_function<Type>::operator() () {
    // data:
    DATA_VECTOR(x);
    DATA_VECTOR(y);
    
    // parameters:
    PARAMETER(a); // intercept
    PARAMETER(b); // slope
    PARAMETER(log_sigma); // log(residual SD)
    // we fit sigma on a log scale to keep it > 0
    
    // procedures: (transformed parameters)
    Type sigma = exp(log_sigma);
    
    int n = y.size(); // get number of data points to loop over
    
    Type nll = 0.0; // initialize negative log likelihood
    
    for(int i = 0; i < n; i++){ // C++ starts loops at 0!
    // get negative log likelihood (last argument is log = TRUE)
    nll -= dnorm(y[i], a + b * x[i], sigma, true);
    }
    
    return nll;
    }"
    write(tmb_model, file = "regression.cpp")
    library(TMB)
    compile("regression.cpp")
    
using TMB::compile gives tons of warnings (these are the last worning + gcc line output): 

    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(4) double}’ [-Wignored-attributes]
                          >::type PacketReturnType;
                                  ^~~~~~~~~~~~~~~~
    In file included from /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/Core:436:0,
                     from /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/Dense:1,
                     from /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/TMB.hpp:53,
                     from regression.cpp:3:
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h: In instantiation of ‘struct Eigen::internal::evaluator<Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<double>, Eigen::Matrix<double, -1, -1> >, 1, -1, false> >’:
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:730:20:   required from ‘void Eigen::internal::call_dense_assignment_loop(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Block<Eigen::Matrix<double, -1, -1>, 1, -1, false>; SrcXprType = Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<double>, Eigen::Matrix<double, -1, -1> >, 1, -1, false>; Functor = Eigen::internal::assign_op<double, double>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:879:31:   required from ‘static void Eigen::internal::Assignment<DstXprType, SrcXprType, Functor, Eigen::internal::Dense2Dense, Weak>::run(DstXprType&, const SrcXprType&, const Functor&) [with DstXprType = Eigen::Block<Eigen::Matrix<double, -1, -1>, 1, -1, false>; SrcXprType = Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<double>, Eigen::Matrix<double, -1, -1> >, 1, -1, false>; Functor = Eigen::internal::assign_op<double, double>; Weak = void]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:836:49:   required from ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Block<Eigen::Matrix<double, -1, -1>, 1, -1, false>; Src = Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<double>, Eigen::Matrix<double, -1, -1> >, 1, -1, false>; Func = Eigen::internal::assign_op<double, double>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:804:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Block<Eigen::Matrix<double, -1, -1>, 1, -1, false>; Src = Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<double>, Eigen::Matrix<double, -1, -1> >, 1, -1, false>; Func = Eigen::internal::assign_op<double, double>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/AssignEvaluator.h:782:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Block<Eigen::Matrix<double, -1, -1>, 1, -1, false>; Src = Eigen::Block<const Eigen::CwiseNullaryOp<Eigen::internal::scalar_identity_op<double>, Eigen::Matrix<double, -1, -1> >, 1, -1, false>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/Assign.h:66:28:   [ skipping 26 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/PlainObjectBase.h:816:7:   required from ‘void Eigen::PlainObjectBase<Derived>::_init1(const Eigen::DenseBase<ElseDerived>&) [with T = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; OtherDerived = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; Derived = Eigen::Matrix<double, -1, -1>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/Matrix.h:296:31:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::Matrix(const T&) [with T = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; _Scalar = double; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/tmbutils/vector.hpp:93:22:   required from ‘tmbutils::matrix<Type>::matrix(T1) [with T1 = Eigen::Inverse<Eigen::Matrix<double, -1, -1> >; Type = double]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/expm.hpp:36:14:   required from ‘atomic::Block<Type> atomic::Block<Type>::inverse() [with Type = double]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/expm.hpp:180:17:   required from ‘matrix_pade atomic::expm(matrix_pade) [with matrix_pade = atomic::nestedTriangle<0>]’
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/TMB/include/expm.hpp:192:52:   required from here
    /home/alberto/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/include/Eigen/src/Core/CoreEvaluators.h:960:8: warning: ignoring attributes on template argument ‘Eigen::internal::packet_traits<double>::type {aka __vector(4) double}’ [-Wignored-attributes]
       enum {
            ^
    g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o regression.so regression.o -L/usr/lib/R/lib -lR
    [1] 0

During execution of this R code it gives me immediately fatal error on rstudio (R console), exactly taken from TMB examples:

    set.seed(123)
    x <- runif(20, 1, 10)
    y <- rnorm(20, mean = 1.8 + 2.4 * x, sd = exp(0.3))
    plot(x, y)
    obj <- MakeADFun(
      data = list(x = x, y = y), 
      parameters = list(a = 0, b = 0, log_sigma = 0),
      DLL = "regression")
    opt <- nlminb(start = obj$par, obj = obj$fn, gr = obj$gr)
    rep <- sdreport(obj)

compiler:

    gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
    OFFLOAD_TARGET_NAMES=nvptx-none
    OFFLOAD_TARGET_DEFAULT=1
    Target: x86_64-linux-gnu
    Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-16ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --with-as=/usr/bin/x86_64-linux-gnu-as --with-ld=/usr/bin/x86_64-linux-gnu-ld --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
    Thread model: posix
    gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)

~.R/Makevars (something touched before for RcppArmadillo, maybe it is my fault and the error is here on CXXFLAGS):

    CFLAGS= -O -mtune=native
    CXXFLAGS= -O2 -mtune=native -march=native -pthread -fopenmp $(BLAS_LIBS) $(LAPACK_LIBS)
    FFLAGS=-g -O -mtune=native
    FCFLAGS=-g -O -mtune=native

thanks for the time

**Comment by kaskr** [comment]
The warnings are coming from `RcppEigen` and apparently [can't in general be silenced because of a CRAN policy](https://github.com/RcppCore/RcppEigen/issues/57). The [RcppEigen NEWS file](https://cran.r-project.org/web/packages/RcppEigen/news.html) gives a hint on how to modify `~/.R/Makevars` to get rid of the warnings:

> Pragmas for g++ & clang to suppress diagnostics messages are disabled per CRAN Policy; use -Wno-ignored-attributes to quieten.

The model crash is probably caused by having `-fopenmp` as part of `CXXFLAGS`. It makes TMB think the model implementation is parallel which is not.

**Comment by albsim** [comment]
thank you for the precise answer, I will try.

**Comment by albsim** [comment]
works perfectly thank you

**Comment by mkapur** [comment]
Just wanted to add a clarification for future reader for whom, like me, it might not be perfectly obvious where the change goes. You must navigate to the Makevars file (which may include a Makevars.win version, if on windows). In a text editor, you need to ensure that -Wno-ignored-attributes is getting passed to CFLAGS. I acheived this by adding it to XTRAFLAGS and retaining the calling that into CFLAGS as follows:

```
XTRAFLAGS=-Wno-ignored-attributes
CFLAGS= -g -O3 -Wall -pipe $(PEDANTIC) $(XTRAFLAGS) -std=gnu99
```
deleting .dll, .o and recompiling succesfully cleared all Eigen warnings.

**Comment by John-R-Wallace-NOAA** [comment]
Under Windows, edit the file 'Makeconf' under R\etc\x64.

Search for:
  
      R_XTRA_CFLAGS = 

and change to:

     R_XTRA_CFLAGS = -Wno-ignored-attributes

Restart R.

**Comment by John-R-Wallace-NOAA** [comment]
Editing the 'Makeconf' file worked well for a while, but I now see that under Windows, editing the 'Makeconf' file or adding "-Wno-ignored-attributes" to TMB::compile(): 

     TMB::compile(paste0(Version, ".cpp"), CPPFLAGS = "-Wno-ignored-attributes")

can fail since:

      tools:::.shlib_internal()

that is used to build shared objects for dynamic loading may, unfortunately, add a flag to show all warnings (-Wall) to the g++ function call:


     "C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"W:/MRO/MRO/include" -DNDEBUG -I"W:/MRO/MRO/library/TMB/include"   -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_VAST_v12_0_0  -DTMB_LIB_INIT=R_init_VAST_v12_0_0   -Wno-ignored-attributes       -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c VAST_v12_0_0.cpp -o VAST_v12_0_0.o

**Comment by mkapur** [comment]
@John-R-Wallace-NOAA I encountered this same issue -- editing the makeVars file worked the first time around, but after subsequent restarts (on Windows), and using VAST the wall-of-warnings returned. Any ideas of how to workaround this? To be clear, I'm encountering this issue for my own personal .cpp file, though I also have run VAST on my computer.

**Comment by bbolker** [comment]
Not sure what VAST is ...

I would *hope* that we could find a way to do this without modifying system files.
On Ubuntu 20.10 my `~/.R/Makevars` contains **only** 

```r
CXXFLAGS = -Wno-ignored-attributes 
```

(the less you have to modify in the automatic/default settings that R has decided on, the better ...)

I believe the technical documentation for this is [here](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Customizing-package-compilation)

**Comment by mkapur** [comment]
@bbolker interestingly, that seemed to solve it (fingers crossed it lasts). I deleted all the riffraff in my standalone .txt (to avoid modifying system files) and call that directly using the same argument I specified above. Thanks.

PS. VAST is a spatiotemporal TMB model used heavily by NOAA/Fisheries Scientists.

**Comment by John-R-Wallace-NOAA** [comment]
In Windows, if you don't mind saving the original 'Makeconf' file (R\etc\x64) and then editing the Makeconf file to remove the 'all warnings' '-Wall' flags, this appears to be a bulletproof way to solve the excess RcppEigen warnings issue.

Below is code that does this for you.  Running it once per R installation is all that is needed:

     # On Windows, remove 'all warnings' flag '-Wall' from the Makeconf file and save the original.
     if(.Platform$OS.type == "windows" & !file.exists(paste0(R.home(), "/etc/x64/Makeconf.Original"))) {
        R.Makeconf.File <- paste0(R.home(), "/etc/x64/Makeconf")
        file.copy(R.Makeconf.File, paste0(R.home(), "/etc/x64/Makeconf.Original"))
        Makeconf <- readLines(R.Makeconf.File)
        Makeconf <- sub('-Wall', '', Makeconf)
        writeLines(Makeconf, con = R.Makeconf.File)
     } 
 
Trying to avoid editing Makeconf is not easy; using '-Wno-ignored-attributes' in TMB::compile 'flags' argument works for simple cpp code:

      
     # Using a clean folder and with an unmodified Makeconf file, which still has the '-Wall' flags
        
     file.copy(paste0(R.home(), '/library/TMB/examples/linreg_parallel.', c('cpp' , 'R')), '.')   
     compile("linreg_parallel.cpp")  # RcppEigen warnings
     file.remove(paste0('linreg_parallel.', c('o', 'dll')))
     
     compile("linreg_parallel.cpp", flags = '-Wno-ignored-attributes') # No RcppEigen warnings
     
But that doesn't work for more complicated C code, such as VAST's 'VAST_v12_0_0.cpp'

     download.file("https://raw.githubusercontent.com/James-Thorson-NOAA/VAST/master/inst/executables/VAST_v12_0_0.cpp" , destfile = "VAST_v12_0_0.cpp")
     compile("VAST_v12_0_0.cpp", flags = '-Wno-ignored-attributes')  # Error

Comparing the calls (all the way to the right), we see that using flags = '-Wno-ignored-attributes' removes more that just '-Wall':

 
     # With  flags = '-Wno-ignored-attributes'
     "C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"W:/MRO/MRO/include" -DNDEBUG -I"W:/MRO/MRO/library/TMB/include"   -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_VAST_v12_0_0  -DTMB_LIB_INIT=R_init_VAST_v12_0_0          -Wno-ignored-attributes -c VAST_v12_0_0.cpp -o VAST_v12_0_0.o
     
     # Without  flags = '-Wno-ignored-attributes'
     "C:/rtools40/mingw64/bin/"g++ -std=gnu++11  -I"W:/MRO/MRO/include" -DNDEBUG -I"W:/MRO/MRO/library/TMB/include"   -DTMB_SAFEBOUNDS -DLIB_UNLOAD=R_unload_VAST_v12_0_0  -DTMB_LIB_INIT=R_init_VAST_v12_0_0   -Wno-ignored-attributes       -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign -c VAST_v12_0_0.cpp -o VAST_v12_0_0.o
 
Adding the missing parts to the 'flags' argument minus '-Wall' which is not wanted, we get something that works:

     compile("VAST_v12_0_0.cpp", flags = "-Wno-ignored-attributes -O2 -mfpmath=sse -msse2 -mstackrealign" )  

Which isn't a general solution for compile(), but the approach does work when compile() is buried in code as in VAST.

A wrapper for compile() also isn't a perfect solution as it does temporarily  change Makeconf, however it puts the original Makeconf back in place:

     # -------------------------  Wrapper function for compile ----------------------
     
     compile_win <- function(...) {
     
         # On Windows, temporarily remove the 'all warnings' flags '-Wall' from the Makeconf file and 
         #    save what was originally encountered (perhaps previously modified by a user or another program).
         
         if(.Platform$OS.type == "windows" ) { 
            if(!file.exists(paste0(R.home(), "/etc/x64/Makeconf.Original")))
                file.copy(R.Makeconf.File, paste0(R.home(), "/etc/x64/Makeconf.Original"))
            R.Makeconf.File <- paste0(R.home(), "/etc/x64/Makeconf")
            Makeconf_Org_temp <- tempfile()
            file.copy(R.Makeconf.File, Makeconf_Org_temp)
            Makeconf <- readLines(R.Makeconf.File)
            Makeconf <- sub('-Wall', '', Makeconf)
            writeLines(Makeconf, con = R.Makeconf.File)
            on.exit(file.copy(Makeconf_Org_temp, R.Makeconf.File, overwrite = TRUE))
            on.exit(rm(Makeconf_Org_temp), add = TRUE)
         }
         
         require(TMB)
         TMB::compile(...) 
     }
     
        # In a clean folder and with an unmodified Makeconf file, which still has the '-Wall' flags try:
      
        library(TMB)
        
        # Copy and compile the 'linreg_parallel' example
        file.copy(paste0(R.home(), '/library/TMB/examples/linreg_parallel.', c('cpp' , 'R')), '.')
     
        # Eigen warnings
        compile('linreg_parallel.cpp', )
        file.remove(paste0('linreg_parallel.', c('o', 'dll')))
        
        # No Eigen warnings
        compile_win('linreg_parallel.cpp')
        
        # Clean up
        file.remove(paste0('linreg_parallel.', c('o', 'dll', 'cpp', 'R')))
        
        
        
        # Copy and compile the 'simple' example
        file.copy(paste0(R.home(), '/library/TMB/examples/simple.', c('cpp' , 'R')), '.')
        
        # The 'Simple' example is too simple and recieves aggressive loop optimization warnings. 
        compile_win('simple.cpp')
        file.remove(paste0('simple.', c('o', 'dll')))
        
        # But that warning can also be silenced. 
        compile_win('simple.cpp', flags = '-Wno-aggressive-loop-optimizations')
        
        # Clean up
        file.remove(paste0('simple.', c('o', 'dll', 'cpp', 'R')))
