### ISSUE TITLE
Using `simulate` feature with distributions that are not implemented

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#278]
Hi there,

I would like to explore using the `simulate` feature for my package `VAST` to explore optimal sampling designs.  VAST includes many standard probability distributions for data, but also some nonstandard ones (i.e., `dtweedie` plus my own implementation of a compound Poisson-gamma, `dPoisGam`).  

Is there any advice for how to deal with non-implemented options for the `simulate` feature?  Clearly the worst option is that it does not simulate new data for cases that are not available in `simulate`.  The next better is to throw some informative error message.  The best would be some suggestions on how to efficiently implement new `simulate` features for user-defined probability distributions.

Jim

**Comment by mebrooks** [comment]
Hi Jim, 

Here's some code for the [Tweedie](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L167).

In general, if you can find the inverse of the cumulative density of your distribution (i.e. the quantile function), then you can use [inverse transform sampling ](https://en.wikipedia.org/wiki/Inverse_transform_sampling). You simulate a uniform (0,1) then use the quantile function to transform that sample to be in the distribution you defined. In glmmTMB, we used the quantile function of the Poisson to [simulate](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L743) from the truncated Poisson. The C version of `qpois` is available as `Rf_qpois` if you add [this code](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/glmmTMB.cpp#L191) to your program. Maybe that could come in handy for the compound Poisson-gamma, but I don't know much about it. I hope that helps. 

I see there's an R package called `fishMod` that implemented `rPoisGam`, but I don't know if it matches your definition of the distribution. Maybe you could get ideas from that.
