### ISSUE TITLE
Using `simulate` feature within functions

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#279]
I'm exploring the `simulate` feature, and it doesn't appear to work within functions.  For example, using the simple linreg.cpp example:

```cpp
#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_VECTOR(y);
  DATA_VECTOR(x);
  PARAMETER(a);
  PARAMETER(b);
  PARAMETER(sd);
  vector<Type> mu = a + b * x;
  Type nll = -sum(dnorm(y, mu, sd, true));
  SIMULATE {
    y = rnorm(mu, sd);  // Simulate response
    REPORT(y);          // Report the simulation
  }
  return nll;
}
```

compiles fine, but if I try wrapping it in a function:

```cpp
#include <TMB.hpp>

// dlnorm
template<class Type>
Type test(vector<Type> mu, vector<Type> sd){
  vector<Type> y( mu.size() );
  SIMULATE {
    y = rnorm(mu, sd);  // Simulate response
  }
  return y;
}

template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_VECTOR(y);
  DATA_VECTOR(x);
  PARAMETER(a);
  PARAMETER(b);
  PARAMETER(sd);
  vector<Type> mu = a + b * x;
  Type nll = -sum(dnorm(y, mu, sd, true));
  y = test( mu, sd );
  REPORT( y );
  return nll;
}
```

then I get an error message:

```R
In file included from C:/PROGRA~1/RRO/R-33~1.1/library/TMB/include/TMB.hpp:93:0,
                 from linreg_function.cpp:1:
linreg_function.cpp: In function 'Type test(tmbutils::vector<Type>, tmbutils::vector<Type>)':
C:/PROGRA~1/RRO/R-33~1.1/library/TMB/include/tmb_core.hpp:210:1: error: invalid use of 'this' in non-member function
 this
 ^
C:/PROGRA~1/RRO/R-33~1.1/library/TMB/include/tmb_core.hpp:331:29: note: in expansion of macro 'TMB_OBJECTIVE_PTR'
 if(isDouble<Type>::value && TMB_OBJECTIVE_PTR -> do_simulate)
                             ^
linreg_function.cpp:7:3: note: in expansion of macro 'SIMULATE'
   SIMULATE {
   ^
```

... and I can confirm that I also get this same compilation error when using a nontrivial example of this in package `VAST` (where I use functions to avoid repetition when defining the distribution of random effects in two parts of a delta-model).

Has anyone tried using `simulate` within functions, or is there some obvious work-around or solution for this use-case?

**Comment by calbertsen** [comment]
To use `simulate` within functions, you have to pass the `objective_function` class pointer to the function and modify the `SIMULATE` or  `TMB_OBJECTIVE_PTR` macro accordingly. That is why you get the "invalid use of 'this'" error.

You can modify your code to something like this:

 ```cpp
#include <TMB.hpp>

// dlnorm
template<class Type>
vector<Type> test(vector<Type> mu, Type sd, objective_function<Type>* of){
  vector<Type> y( mu.size() );
  if(isDouble<Type>::value && of->do_simulate) {
    y = rnorm(mu, sd);  // Simulate response
  }

  return y;
}

#undef  TMB_OBJECTIVE_PTR
#define TMB_OBJECTIVE_PTR of    
template<class Type>
vector<Type> test2(vector<Type> mu, Type sd, objective_function<Type>* of){
  vector<Type> y( mu.size() );
  SIMULATE {
    y = rnorm(mu, sd);  // Simulate response
  }

  return y;
}
#undef  TMB_OBJECTIVE_PTR
#define TMB_OBJECTIVE_PTR this
  

template<class Type>
Type objective_function<Type>::operator() ()
{
  DATA_VECTOR(y);
  DATA_VECTOR(x);
  PARAMETER(a);
  PARAMETER(b);
  PARAMETER(sd);
  vector<Type> mu = a + b * x;
  Type nll = -sum(dnorm(y, mu, sd, true));
  y = test( mu, sd, this );
  REPORT( y );
  vector<Type> y2 = test2( mu, sd, this);
  REPORT( y2 );
  return nll;
}
```

In the function `test`, the SIMULATE macro function has been altered, while it is the `TMB_OBJECTIVE_PTR` macro in `test2`. Obviously, you only have to use one of them. There is an [example of the latter approach in the documentation](https://kaskr.github.io/adcomp/group__macros.html#ga50653183cdc71e3cb81b410768f23efb)

**Comment by James-Thorson** [comment]
Thanks Christoffer!

Do you have any feedback on which of those implementation is more computationally efficient?  It seems like the first (function `test`) has fewer new lines to trip up a new reader of the code, so I imagine that would be the better choice, but I welcome any feedback on choosing between the two in case you're still interested in the topic?

**Comment by calbertsen** [comment]
It should be exactly the same; however, an advantage of the second approach is that it is safer if something changes in the internal parts of TMB (e.g. if Kasper decides to change the `do_simulate` flag to `run_simulate` or something like that)
