### ISSUE TITLE
error when using devtools::install_github("kaskr/adcomp/TMB")

### ISSUE THREAD

**Issue by perretti** [kaskr/adcomp#280]
TMB installs fine from CRAN, but when I try to install via GitHub using using `devtools::install_github("kaskr/adcomp/TMB")` I get:

`clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.4/Resources/library/Matrix/include" -I/usr/local/include  -fopenmp -fPIC  -Wall -g -O2  -c external_metis.c -o external_metis.o`
```
clang: error: unsupported option '-fopenmp'
make: *** [external_metis.o] Error 1
ERROR: compilation failed for package ‘TMB’
```

Any suggestions?

**Comment by kaskr** [comment]
Duplicate of #245 ?

**Comment by perretti** [comment]
That fixed it. Thanks, Kasper.
