### ISSUE TITLE
Which TMB wrapper might be giving me this warning: In par[-random] <- par.fixed: number of items to replace is not a multiple of replacement length

### ISSUE THREAD

**Issue by bchasco** [kaskr/adcomp#290]
I am simulation testing a mixed effect model with fixed and random effects and I sometimes, but not always, receive the following warning, 

In par[-random] <- par.fixed :
  number of items to replace is not a multiple of replacement length

The model estimates the parameters correctly and produces a positive definite hessian. The error seems pretty self explanatory, save the fixed effects to a par vector where the indices are not equal to the random effect indices. My problem is the model returns a set of parameters for the fixed effects that is the correct length for parameter list that the model receives. So, I guess I just need to know which wrapper I should look in to figure out was might be happening, and why this error is being generated.

Thanks,
Brandon

**Comment by bbolker** [comment]
Maybe [here](https://github.com/kaskr/adcomp/blob/05363910c58285ed74e79fc373902752a548c241/TMB/R/TMB.R#L582) ?

**Comment by vtrijoulet** [comment]
I suspect you may be mapping on the random effects. Please send a reproducible example so we can help further.

**Comment by bchasco** [comment]
Thanks for the suggestion on where to look. I finally made it back to this project and found the issue had to do with a random effects vector that had a length of n, and a likelihood for the random effect that only went to n-1.
