### ISSUE TITLE
Gauss-Kronrod integration with vector 

### ISSUE THREAD

**Issue by BertvanderVeen** [kaskr/adcomp#307]
I've been attempting to fit a latent variable model for which the marginal likelihood cannot be approximated using Laplace's method, and the latent variable has unknown dimension at the time the script is compiled. Though the example using multivariate Romberg integration shows how to pass a vector of a dynamic size to the function, the example with adaptive Gauss-Kronrod quadrature does not. 

Is it possible to do the same with Gauss-Kronrod, and if so, how?

Additionally, I noted the AD takes considerably longer when using mvIntegrate versus Integrate.

Thanks!
Bert

**Comment by BertvanderVeen** [comment]
I'm now including code here, which I scraped together from the examples, to give an impression of what I'm trying to accomplish, in the hope that clarifies things. 

As part of a log-likelihood derived using Variational Approximations, I would like to evaluate an expectation that lacks a closed form expression (as far as I can tell): E(1/exp(eta)), eta = z1*theta + z2*theta2, is the linear predictor and z1_i, z2_i ~ MVRN(a_i, A_i). This is evaluated, i = 1...n times as part of the log-likelihood. 

I've been trying to do this using TMB's adaptive Gauss-Kronrod implementation, but seem to be falling short. As I have nothing to compare the results of the numerical integration to for the above example, I've instead compared the results of the numerical integration with E(exp(eta)) for which I do have a closed form expression. Though the integration results are accurate (similar) at the start of the optimization (3 or so decimals at least), for some sites (i) the result of the numerical integration is quite poor, i.e. it deviates from the closed-form answer quite rapidly into the optimization, eventually resulting in a negative, negative log-likelihood (i.e. a positive log-likelihood, where the closed-form expression performs just fine) I've gone over my code a dozen times, and can't seem to find mistakes.

Three issues I would appreciate help with/input on:
1) I couldn't get the script to compile when passing TMB-type vectors to the integrand (so this is different from above as that relates to a question for passing a vector to `mvIntegrate`, rather than having to `wrt()` for each of the latent variables). So, instead, I used single column matrices. Is this possible?
2) (I think as a consequence of 1, seemingly not being able to pass a TMB-type vector) I can't use `REGISTER_ATOMIC()` (which I hoped would reduce the RAM usage of `MakeADFun()`, though please correct me if I'm wrong)
3) Is there any other possibility for me to improve the results of the numerical integration?

I've attempted to increase the relative and absolute tolerances, but that only resulted in a higher RAM usage. Happy to repost to the TMB user group if you deem this more appropriate there. `eval` below is evaluated for every i = 1...n.

```
template<class Float>
struct integrand {
  typedef Float Scalar; // Required by integrate
  matrix<Float> theta1;
  matrix<Float> theta2;
  matrix<Float> a;
  matrix<Float> A;
  
  //z1,z2 ~ NMVRN(a,A)  
    Float z1; //Latent variable 1
    Float z2; //Latent variable 2
  
    Float operator() () {

    matrix <Float> z(1,A.cols());
    z(0,0) = z1;
    z(0,1) = z2;

    Float ans = 0;
    ans += (z.array()*theta1.array()).sum() - (z.array()*z.array()*theta2.array()).sum();
    //Subtract negative log-likelihood for the Multivariate Normal as I want the log-likelihood to be added (i.e. int exp(eta(z))h(z)d(z), where h(z) is the Multivariate normal
    ans -= density::MVNORM(A)(z.row(0)-a.row(0));

    return ans;
  }
  
  // Integrate wrt (x,y)
  Float integrate() {
    using namespace gauss_kronrod;
    Float ans = mvIntegrate(*this, control(100,1e-5,1e-5)).
    wrt(z1, -INFINITY, INFINITY).
    wrt(z2, -INFINITY, INFINITY) ();
    return ans;
  }
};

template<class Float>
Float eval(matrix<Float> theta1, matrix<Float> theta2, matrix<Float> a, matrix<Float> A){
  integrand<Float> f = {theta1, theta2, a, A};
  return f.integrate();
}
```

**Comment by kaskr** [comment]
Note that integrand should return *density* not *log(density)* as [here](https://github.com/kaskr/adcomp/blob/52002f8dd4e022661b1f4f32986a0c40a19fbd75/tmb_examples/adaptive_integration.cpp#L22)

> Happy to repost to the TMB user group if you deem this more appropriate there.

Yes, please

**Comment by BertvanderVeen** [comment]
Thanks for responding Kasper, apologies for the mistake in my example, that's not the case in the "real" code. I will repost this to the user group, feel free to close this issue.
