### ISSUE TITLE
[R TMB package] Use C++ to do simulation

### ISSUE THREAD

**Issue by of1201** [kaskr/adcomp#308]
I was using the R TMB package to do parameter estimation for Stochastic Volatility Model. The data is based on a csv file which contains 48 stocks' historical price, but the volatility for those stocks is not given, which means I have to treat V in the SV model as the latent random variable and integrate it out.

Now I have done the parameter estimation and I will need to use the estimated parameters to do simulation. However I cannot do this in R simply because the V is not given. So I guess I will have to do this in C++ again using the simulate function, which I heard from:
https://kaskr.github.io/adcomp/Simulation.html

However, I still have to include the V in the simulation first in C++ code. I am just wondering if I did this and called the C++ code from R, can I still integrate the V out when calling the  "MakeADFun" function? And then hopefully I can run the "xxx$simulate()" function correctly?

**Comment by skaug** [comment]
I think it should be possible to do the simulation fully within R. You have a model
for V, and you can use estimated values to simulate from that. This may be a good
check even if you use https://kaskr.github.io/adcomp/Simulation.html

**Comment by of1201** [comment]
Sorry what do u mean I have a model for V? 
When I was doing parameter estimation and was using the “MakeADFun” function, I set the default value for V to be “VIX” which is the volatility for S&P 500 (I was simulating the price for an individual stock so theoretically I cannot use the index volatility as its volatility) and then I integrated V out. I notice that I only need a starting value for V and X to simulate future asset values. So does that mean that I can just pick a starting value of V to be the VIX at some time point and run the simulation?

**Comment by skaug** [comment]
In my (limited) experience with stochastic volatility there is a model for V, but it sounds like 
it is not in your case. Anyway, I doubt that moving to C++ will solve your problem.

As a side comment, your question seems to be appropriate for the user list:

https://groups.google.com/forum/#!forum/tmb-users
