### ISSUE TITLE
Weird gradient calculation messing things up

### ISSUE THREAD

**Issue by pthompson234** [kaskr/adcomp#312]
Hi, I've been using TMB for the last few months for a model I'm working on. It's been working quite well and I've enjoyed using it, but recently I've encountered an odd error with one of my datasets. I've been fitting the model to multiple datasets, and for some it works as expected, while for others it gives me a very odd error. I wonder if this may be something related to the quality of these specific data sets, but either way, I figured I'd see if anyone on here has any insight with regards to this problem.

![bad_tmb_output](https://user-images.githubusercontent.com/47431897/81201194-3ec77180-8f82-11ea-931d-64e7d1479dc6.png)

The problem can be, in short, explained by the screenshot above. L.comb1pk is an output of a call to MakeADFun, with 12 parameters. I've set up the function so it reports a Type variable "val" and then returns "val" as the value from the objective function; in other words, L.comb1pk$report$val should always be equal to L.comb1pk$fn. In this case, this is almost never true. I've realized that this is because of the way the gradient is calculated. For some reason, at every parameter set I have tried, the gradient is the same thing: all zeroes except the third and fourth parameters are 1. So the value of L.comb1pk$fn is just a linearly increasing function of those parameters (and none of the other parameters matter). This results in a very odd minimum (and of course, the optimization routine doesn't even converge) that stems from very large negative values of the third and fourth parameter. As you can see, the "actual value" as reported by the function is quite large, and would certainly not be a minimum for this function.

I understand that obviously your objective function has to be continuous and differentiable for all this to work. Although my function is rather complicated, it certainly does meet these criteria (after all, it works for other datasets). The most confusing part is, without having to explain the entirety of what this function should be doing, there is no reason the third gradient component at the current set of parameters shouldn't be zero. The way the function is written, this parameter will only have an effect on the return value of the function if the 10th parameter is not zero, and you can see here that it is. Additionally, a bunch of other parameters definitely would have an effect on the function here (parameters 5-8 in particular), but the gradient component for those is zero everywhere. Changing these values changes the output of the reported variable val in the way I'd expect it to. Because this problem only pops up depending on the data set I'm using, I understand that it might just be a problem with the data itself that I have to unearth. But if anyone has encountered a problem like this, please let me know, because it might be something I can fix in the arguments passed to MakeADFun or the C++ file for the objective function itself.

Thanks for the help,
Peter Thompson

**Comment by kaskr** [comment]
I realize that the previous issue template was not clear enough. Should now be fixed:

https://github.com/kaskr/adcomp/blob/master/.github/ISSUE_TEMPLATE.md
