### ISSUE TITLE
TMB and R Version 4.0 on Windows

### ISSUE THREAD

**Issue by rishihermit** [kaskr/adcomp#318]
#### IMPORTANT TO READ CAREFULLY BEFORE POSTING AN ISSUE

**Only post an issue if you are fairly sure you've found a bug in TMB.**

**Questions on how to use TMB or get help on errors relative to your own models should be posted to https://groups.google.com/forum/#!forum/tmb-users.**

**Use the following as template for your issue post:**

#### Description:
Describe the issue as clearly as possible.

#### Reproducible Steps:
Please report steps to reproduce the issue. If it's not possible to reproduce, please include a description of how you discovered the issue.

If you have a reproducible example, please include it.

Please make the example as short as possible.

#### Current Output:
If applicable, any relevant output from TMB.

#### Expected Output:
If applicable, the output you expected from TMB.

#### TMB Version:
The version of TMB you are running (e.g., from `packageVersion("TMB")`)

#### R Version:
The version of R you are running (e.g., from `R.version.string`)

#### Operating System:
Your operating system (e.g., OS X 10.11.3)

**Comment by rishihermit** [comment]
TMB was working fine, until all of a sudden, I deleted one library which may have had some inherent libraries connected to it. Now it refuses to compile anything, I have checked the path for the compiler, reinstalled everything twice, but still no go. Any help on this would be much appreciated. Thanks

**Comment by the-sushi** [comment]
Sounds like an individual issue/question rather than one with TMB.  I suggest posting to the [TMB Users Forum](https://groups.google.com/forum/#!forum/tmb-users), preferably with more information on what you did.
