### ISSUE TITLE
GitHub releases are tracked incorrectly

### ISSUE THREAD

**Issue by the-sushi** [kaskr/adcomp#320]
GitHub lists the latest release as from 2017.  This is because, although TMB has version tags, they are not set up as GitHub releases (despite, confusingly, being listed as them).  I'll fix it if that's alright, but I figured I should ask first though ([relevant](https://xkcd.com/1172/)).

**Comment by kaskr** [comment]
Sounds good.

Each tag represents a CRAN submission and changelog is in the TMB/NEWS file.

**Comment by the-sushi** [comment]
Done
