### ISSUE TITLE
sdreport error when getReportCovariance=FALSE and no ADREPORT variables present

### ISSUE THREAD

**Issue by James-Thorson-NOAA** [kaskr/adcomp#333]
#### Description:
`sdreport` throws an error to R terminal:

```R
Error in sqrt(unlist(tmp)) : 
  non-numeric argument to mathematical function
```

when `getReportCovariance=FALSE` and there are no `ADREPORT`ed variables in CPP file.

#### Reproducible Steps:
Adapting from my install-testing script here: https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/Steps-to-install-TMB ...

the following script works:

```R
######################
# Simulate data for a linear mixed model with random intercepts
######################

set.seed(1)
Factor = rep( 1:10, each=10)
Z = rnorm( length(unique(Factor)), mean=0, sd=1)

X0 = 0
Y = Z[Factor] + X0 + rnorm( length(Factor), mean=0, sd=1)

######################
# Run in TMB
######################

install.packages("TMB")
library(TMB)
Version = "linear_mixed_model"

# Download CPP file
if( FALSE ){
  setwd( tempdir() )
  download.file( url="https://raw.githubusercontent.com/James-Thorson/mixed-effects/master/linear_mixed_model/linear_mixed_model.cpp", destfile="linear_mixed_model.cpp", method="auto")
}else{
  setwd( "C:/Users/James.Thorson/Desktop/Work files/AFSC/2020-12 -- TMB bug report" )
}

compile( paste0(Version,".cpp") )

# Generate inputs for TMB
Data = list( "n_data"=length(Y), "n_factors"=length(unique(Factor)), "Factor"=Factor-1, "Y"=Y)
Parameters = list( "X0"=-10, "log_SD0"=2, "log_SDZ"=2, "Z"=rep(0,Data$n_factor) )
Random = c("Z")

# Build TMB object
dyn.load( dynlib(Version) )
Obj = MakeADFun(data=Data, parameters=Parameters, random=Random)  #

# Check that TMB is working
Obj$fn( Obj$par )

Opt = nlminb( start=Obj$par, objective=Obj$fn, gradient=Obj$gr )
SD = sdreport( Obj, getReportCovariance=FALSE )
```

However, editing the CPP locally to remove all `ADREPORT` lines in the CPP then throws the error. 

#### Current Output:
NA

#### Expected Output:
NA

#### TMB Version:
1.7.16

#### R Version:
R version 4.0.2 (2020-06-22)

#### Operating System:
Windows 10

**Comment by Cole-Monnahan-NOAA** [comment]
What behavior do you want? You're asking for the SE of non-existent variables. Seems like you could set `skip.delta.method=TRUE` to skip it.

https://github.com/kaskr/adcomp/blob/a81ff89f5e65fae801ce0d2634cde575d460ee70/TMB/R/sdreport.R#L245

Or you could take this line and add a check for if `phi` is empty. Seems like either would be a simple fix.
