### ISSUE TITLE
Add RcppEigen to Imports

### ISSUE THREAD

**Issue by Enchufa2** [kaskr/adcomp#350]
A user or another package that compiles against TMB may not use RcppEigen, but TMB require RcppEigen. The LinkingTo field ensures that RcppEigen is present at TMB installation, but not necessarily when TMB is being used. This happens when we ship CRAN packages in Linux repositories: TMB is built against RcppEigen, but then when we compile other package that uses TMB (such as `unamarked`), RcppEigen is missing, and compilation fails. See e.g. [this log](https://download.copr.fedorainfracloud.org/results/iucar/cran/fedora-rawhide-x86_64/02296759-R-CRAN-unmarked/builder-live.log.gz)

**Comment by kaskr** [comment]
It has been documented how packages are supposed to avoid this issue here:
https://github.com/kaskr/adcomp/wiki/Development#distributing-code
(by adding `LinkingTo: TMB, RcppEigen` to `DESCRIPTION`)

**Comment by Enchufa2** [comment]
Thanks, then moving the issue to the `unmarked` package. Feel free to close this.
