### ISSUE TITLE
TMB shared object not unloaded with namespace

### ISSUE THREAD

**Issue by jaganmn** [kaskr/adcomp#353]
The TMB shared object is loaded with the TMB namespace when `loadNamespace("TMB")` is called, but not unloaded with the TMB namespace when `unloadNamespace("TMB")` is called. This is not standard behaviour:

```r
R.version.string # 4.1.0
packageVersion("TMB") # 1.7.21

f <- function(pkg) {
  is_dll_loaded <- function() pkg %in% names(getLoadedDLLs())
  loadNamespace(pkg)
  before_unload <- is_dll_loaded()
  unloadNamespace(pkg)
  after_unload <- is_dll_loaded()
  c(before_unload, after_unload)
}
f("Matrix") # TRUE FALSE
f("nlme") # TRUE FALSE
f("lme4") # TRUE FALSE
f("TMB") # TRUE TRUE
```

This issue is resolved by adding the following code to `R/zzz.R`:

```r
.onUnload <- function(libpath) {
  library.dynam.unload("TMB", libpath)
}
```

See section "Good practice" in `?.onUnload`. Note that glmmTMB has the same problem... @bbolker 

```r
packageVersion("glmmTMB") # 1.1.2.3
f("glmmTMB") # TRUE TRUE
```

**Comment by kaskr** [comment]
Thanks @jaganmn
