### ISSUE TITLE
Segfault `runSymbolicAnalysis()` with two phases fitting approach

### ISSUE THREAD

**Issue by kklot** [kaskr/adcomp#359]
#### Description:

Fitting a model in two phases as in the `spde.R` example, after updating the model object with the new parameter estimated from phase 1, running `runSymbolicAnalysis` causes segfault. Found this after trying to run symbolic analyses on my model.

#### Reproducible Steps:

1.  Run example `spde.R` example
2. add `runSymbolicAnalysis(obj)` after \https://github.com/kaskr/adcomp/blob/2bc57ba198ce7bb81c6d510a015185ae7981c90c/tmb_examples/spde.R#L48

#### Current Output:

```r
> runSymbolicAnalysis(obj)
Optimizing tape... Done
Entering externallib

 *** caught segfault ***
address 0x1, cause 'memory not mapped'

Traceback:
 1: runSymbolicAnalysis(obj)
```

#### Expected Output:

No segfault?

#### TMB Version:
```
> packageVersion("TMB")
[1] ‘1.7.22’
```

#### R Version:
```r
[1] "R version 3.6.0 (2019-04-26)"
```

#### Operating System:
Scientific Linux 7

**Comment by kaskr** [comment]
The Matrix package 'recently' updated the SuiteSparse library which changed the layout of some structs. You'll need:

```
> Matrix:::.SuiteSparse_version()
[1] ‘5.7.1’
```

**Comment by kaskr** [comment]
@kklot I'm assuming this is solved

**Comment by kklot** [comment]
Yes, thanks!
