### ISSUE TITLE
Book generation code is broken somewhere

### ISSUE THREAD

**Issue by bbolker** [kaskr/adcomp#375]
Something is wrong with the book generation pipeline, e.g. https://kaskr.github.io/adcomp/_book/Tutorial.html#obtaining-data-and-parameter-values-from-r is rendered with lots of  weird tags like this:

<[code](https://kaskr.github.io/adcomp/structTMBad_1_1op__info.html#abf0a1eac216e5f53dd67f695b381b296)>[code](https://kaskr.github.io/adcomp/structTMBad_1_1op__info.html#abf0a1eac216e5f53dd67f695b381b296)" href="../group__macros.html#ga97c14a26ca75571090d332f15130ae4b">DATA_ARRAY()[code](https://kaskr.github.io/adcomp/structTMBad_1_1op__info.html#abf0a1eac216e5f53dd67f695b381b296)>,

**Comment by kaskr** [comment]
Ok now
