### ISSUE TITLE
besselK problem when used inside function for gauss_kronrod integration

### ISSUE THREAD

**Issue by alexiosg** [kaskr/adcomp#376]
# Issue
I'm trying to calculate the absolute moment of a standardized distribution (Normal Inverse Gaussian), using gauss_kronrod integration, which makes use of the besselK function. When trying to compile the code I receive a number of errors (see below). Would appreciate any suggestions.

Also:
1. Is there something I should be aware of in terms of restrictions using gauss_kronrod e.g. are CppAD::CondExp?? conditions not allowed?
2. I noticed that the implementation of besselK does not include the option for exponential scaling (seems that the bessel_k function in atomic.hpp hardcodes the 'expo' argument in bessel_k.cpp to 1 i.e. no scaling). Is there any reason for doing so?
 
Many Thanks,

Alexios

# Compiler Errors
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/distributions_R.hpp:467:6: error: no matching function for call to 'Variable'
  if(CppAD::Variable(nu)) {
     ^~~~~~~~~~~~~~~
./distfun.h:117:64: note: in instantiation of function template specialization 'besselK<atomic::tiny_ad::variable<1, 2>>' requested here
        Type pdf =  -log(M_PI) + log(alpha) + log(delta) + log(besselK(tmp,Type(1.0))) + delta*sqrt(alpha*alpha-beta*beta)+beta*xm-Type(0.5)*log(d+xm*xm);
                                                               ^
./distfun.h:203:30: note: in instantiation of function template specialization 'distfun::dnig_std<atomic::tiny_ad::variable<1, 2>>' requested here
            ans += fabs(u) * dnig_std(u, skew, shape, give_log);
                             ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/tiny_ad/integrate/integrate.hpp:83:37: note: in instantiation of member function 'distfun::struct_nig<atomic::tiny_ad::variable<1, 2>>::operator()' requested here
      for(int i=0; i<n; i++) x[i] = f(x[i]);
                                    ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/tiny_ad/integrate/integrate.cpp:1656:5: note: in instantiation of member function 'gauss_kronrod::Integral<distfun::struct_nig<atomic::tiny_ad::variable<1, 2>>>::vectorized_integrand::operator()' requested here
    f(vec, 15, ex); /* -> new vec[] overwriting old vec[] */
    ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/tiny_ad/integrate/integrate.cpp:524:5: note: in instantiation of function template specialization 'gauss_kronrod::rdqk15i<atomic::tiny_ad::variable<1, 2>, gauss_kronrod::Integral<distfun::struct_nig<atomic::tiny_ad::variable<1, 2>>>::vectorized_integrand>' requested here
    rdqk15i(f, ex, &boun, inf, &c_b6, &c_b7, result, abserr, &defabs, &resabs);
    ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/tiny_ad/integrate/integrate.cpp:241:5: note: (skipping 8 contexts in backtrace; use -ftemplate-backtrace-limit=0 to see all)
    rdqagie(f, ex, bound, inf, epsabs, epsrel, limit, result, abserr, neval, ier,
    ^
./distfun.h:220:21: note: in instantiation of function template specialization 'distfun::nigabs<double>' requested here
    TMB_BIND_ATOMIC(nigabs, 11, evalnig(x[0], x[1]))
                    ^
./distfun.h:225:29: note: in instantiation of function template specialization 'distfun::nigabs<double>' requested here
            return distfun::nigabs(CppAD::vector<Type>(args))[0];
                            ^
./kappa.h:63:28: note: in instantiation of function template specialization 'distfun::nig_abs_moment<CppAD::AD<double>>' requested here
            out = distfun::nig_abs_moment(skew, shape);
                           ^
example_integrate.cpp:15:23: note: in instantiation of function template specialization 'kappa::abs_moment_func<CppAD::AD<double>>' requested here
    Type ans = kappa::abs_moment_func(skew, shape, lambda, dclass);   
                      ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/tmb_core.hpp:1286:6: note: in instantiation of member function 'objective_function<CppAD::AD<double>>::operator()' requested here
    F(); // Run through user template (modifies reportvector)
     ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/TMB.hpp:171:8: note: candidate function not viable: no known conversion from 'atomic::tiny_ad::variable<1, 2>' to 'double' for 1st argument
  bool Variable(double x)CSKIP({ return false; })
       ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/cppad/local/par_var.hpp:102:7: note: candidate template ignored: could not match 'AD' against 'variable'
        bool Variable(const AD<Base> &x)
             ^
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/cppad/local/par_var.hpp:111:7: note: candidate template ignored: could not match 'VecAD' against 'variable'
        bool Variable(const VecAD<Base> &x)
             ^
In file included from example_integrate.cpp:1:
In file included from /Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/TMB.hpp:189:
/Library/Frameworks/R.framework/Versions/4.1/Resources/library/TMB/include/tiny_ad/atomic.hpp:30:1: error: no matching function for call to 'Integer'

# Calling Function

```
template<class Float>
    struct struct_nig {
        typedef Float Scalar; // Required by integrate
        Float skew, shape;    // Data
        Float operator() (Float u) {
            Float ans = 0;
            const int give_log = 0;
            ans += fabs(u) * dnig_std(u, skew, shape, give_log);
            if (ans == 0) ans = 0;
            using atomic::tiny_ad::isfinite;
            if (!isfinite(ans)) ans = 0;
            return ans;
        }
        Float marginal() {
            using gauss_kronrod::integrate;
            Float ans = integrate(*this, -INFINITY, INFINITY);
            return ans;
        }
    };
    template<class Float>
    Float evalnig(Float skew, Float shape) {
        struct_nig<Float> f = {skew, shape};
        return f.marginal();
    }
    TMB_BIND_ATOMIC(nigabs, 11, evalnig(x[0], x[1]))
        template<class Type>
        Type nig_abs_moment(Type skew, Type shape) {
            vector<Type> args(3); // Last index reserved for derivative order
            args << skew, shape, 0;
            return distfun::nigabs(CppAD::vector<Type>(args))[0];
```
# Other Details

dnig_std calls a vectorized function  which has a few calls to besselK

**Comment by kaskr** [comment]
(This is more appropriate for the tmb users list...)

I assume you took inspiration from https://github.com/kaskr/adcomp/blob/master/tmb_examples/adaptive_integration.cpp ?
As the name indicates this is a general approach for *adaptive* algorithms i.e., algorithms that require if-else branching on parameters. All calculations done with the 'Float' type are done with a different AD engine (tapeless forward mode) than normal TMB (taped reverse mode). It would therefore not make sense to apply taped if-else branching (CondExp) when you can just use normal comparision operators.
Regarding `besselK` you can see how it's implemented here:
https://github.com/kaskr/adcomp/blob/master/TMB/inst/include/tiny_ad/atomic.hpp
It simply redirects to `bessel_utils::bessel_k(x[0], x[1], 1.)` using a fixed exponential scaling argument. You can use `bessel_utils::bessel_k` in your own code (tapeless forward mode only).

**Comment by alexiosg** [comment]
Thanks Kasper, will post to the users list.
