### ISSUE TITLE
determinant(Cholesky(A, ...)) in forthcoming Matrix

### ISSUE THREAD

**Issue by jaganmn** [kaskr/adcomp#380]
Starting with Matrix 1.6-0, `determinant(Cholesky(A, ...))` will have an option `sqrt=` to indicate if the determinant of `L` should be computed as opposed to the determinant of `A`.  For backwards compatibility, the default is currently `sqrt=TRUE`, indicating `L`.  We plan to change the default value to `FALSE` in the future, hence we are proactively asking packages to pass `sqrt=TRUE` to `determinant`. 

I _think_ that the only place in TMB where this matters is

https://github.com/kaskr/adcomp/blob/2eb96b6799e0f069713ed7bc09b0138981ba7a1b/TMB/R/TMB.R#L702

where you should change to `2*determinant(L, sqrt=TRUE)$mod` _not_ `determinant(L, sqrt=FALSE)$mod`, as `sqrt` is unrecognized in earlier versions of Matrix.

Without the change, users will see a (once-per-process, by default) warning:

```r
> library(Matrix)
> determinant(new("dCHMsimpl"))
$modulus
[1] 0
attr(,"logarithm")
[1] TRUE

$sign
[1] 1

attr(,"class")
[1] "det"
Warning message:
In .local(x, logarithm, ...) :
  the default value of argument 'sqrt' of method 'determinant(<CHMfactor>, <logical>)' may change from TRUE to FALSE as soon as the next release of Matrix; set 'sqrt' when programming
```

**Comment by bbolker** [comment]
Just encountered this in `glmmTMB`, it was hard to tell where it was coming from, so thanks for posting ...

I'm not quite sure what you mean by

> where you should change to `2*determinant(L, sqrt=TRUE)$mod` not `determinant(L, sqrt=FALSE)$mod`, as `sqrt` is unrecognized in earlier versions of Matrix.

Is this change going to make `TMB` backward-incompatible with earlier versions of Matrix (i.e. we need to add `Imports: Matrix (>=1.6.0)` **or** add `if (packageVersion("Matrix") >= "1.6.0") { ... etc. }` ?)

**Comment by kaskr** [comment]
@bbolker The way I understand it, this `determinant(sqrt=TRUE)` fix will make TMB backwards compatible with any Matrix version.

**Comment by jaganmn** [comment]
@kaskr is correct: `sqrt = TRUE` is backwards and forwards compatible, whereas `sqrt = FALSE` is only forwards compatible (because in Matrix `<= 1.6-0` `det(L)` was computed unconditionally).  The patch looks right - thanks for noticing the other usage, which I missed ...
