### ISSUE TITLE
Non-interactive gdbsource hangs under windows

### ISSUE THREAD

**Issue by lentinj** [kaskr/adcomp#385]
#### Description:

Under Windows, ``gdbsource(interactive = FALSE)`` will never return.

The solution may well be quite easy. Compared to the UNIX version, the gdbscript formed in ``.gdbsource.win`` seems to be missing a final ``quit\n`` when ``interactive = FALSE``:

https://github.com/kaskr/adcomp/blob/3155ebd0ce43f7972c09c67e550d3645f04d9099/TMB/R/gdbsource.R#L51-L52

#### Reproducible Steps:

```
writeLines('print("Hello, world")', con = 'gdbsource_test.R') ;
TMB::gdbsource('gdbsource_test.R', interactive = FALSE)
```

#### Current Output:

Nothing, the gdb process hangs.

#### Expected Output:

The same as other operating systems: ``Program returned without errors``

#### TMB Version:

``TMB 1.9.6``

#### R Version:

``R-4.3.1-win.exe``

#### Operating System:

Windows 11

**Comment by kaskr** [comment]
Sorry for late reply. I've been trying to replicate without luck. It seems to work well on the Windows server I have access to (feel free to re-open if you still think there's a problem).
