### ISSUE TITLE
NAs produced when computing confidence intervals with tmbprofile() and confint()

### ISSUE THREAD

**Issue by constantin-george** [kaskr/adcomp#386]
I am using TMB for a simulation study and noticed that tmbprofile() seems return NAs when computing CI above 95%. I was wondering why this is happening? The error is not replicated with tmbroot(). I am using TMB version ‘1.9.6’.

```
### Example
runExample("simple",thisR=TRUE)
confint(tmbprofile(obj,"logsd0"), level = 0.99)
##        lower upper
## logsd0    NA    NA
```

```
tmbroot(obj,"logsd0",target = 0.5 * qchisq(0.99, df = 1))
##        lwr        upr 
## -0.1299770  0.2136796 

```

**Comment by bbolker** [comment]
You need to adjust the range of log-likelihood differences you're asking `tmbprofile` to consider:

```r
confint(tmbprofile(obj,"logsd0",ytol = 4), level = 0.99)
```

**Comment by constantin-george** [comment]
Great, that works now on my end. Thank you for the help, Ben.
