### ISSUE TITLE
Model selection and validation

### ISSUE THREAD

**Issue by markpayneatwork** [kaskr/adcomp#39]
Hi,

I have added two qns to the FAQ that are very-frequently asked questions in my life:
- **How do I choose betweeen models fitted with TMB?** e.g. how can I get a conditional AIC? Is it possible to extract a DIC value based on an estimated number of parameters, as is done in INLA?
- **How do I validate a model fitted with TMB?** The linear modelling world has a large set of residual diagnostic tools that can be used to check (qualitatively) for appropriate model specification (e.g. Tukey-anscombe, QQplots, plot residuals vs explanatory variables). How do I approach this type of thing in the context of a TMB model (with e.g. non-Gaussian observation models)?

I'd love to hear some wisdom regarding this recurring question... Put another way, what would be the minimum that you would need to include in a paper to "prove" (ha, ha!) that your model is appropriate....

Mark

**Comment by mebrooks** [comment]
Do we automatically get the hat matrix anywhere, in case we wanted to calculate the conditional AIC?

**Comment by skaug** [comment]
If you by hat matrix mean [https://en.wikipedia.org/wiki/Hat_matrix](https://en.wikipedia.org/wiki/Hat_matrix) I think the answer is no.

**Comment by bbolker** [comment]
Bumping this because it would be really handy, if there's a recipe for doing it without ridiculous effort.
