### ISSUE TITLE
Possible undefined behavior for NA values with DATA_INTEGER, DATA_IVECTOR, DATA_IMATRIX, and DATA_IARRAY. 

### ISSUE THREAD

**Issue by calbertsen** [kaskr/adcomp#399]
#### IMPORTANT TO READ CAREFULLY BEFORE POSTING AN ISSUE

**Only post an issue if you are fairly sure you've found a bug in TMB.**

**Questions on how to use TMB or get help on errors relative to your own models should be posted to https://groups.google.com/forum/#!forum/tmb-users.**

**Use the following as template for your issue post:**

#### Description:

Data passed from R to C++ in TMB is coerced to double by Rf_coerceVector. In turn, DATA_INTEGER, DATA_IVECTOR, DATA_IMATRIX, and DATA_IARRAY casts without using R implementations. If an NA value is passed from R to C++, it is converted to R_NaReal, which is a floating point NaN. Casting to int is, I believe, undefined behaviour. The casting should check for R_NaReal/NaN like Rf_coerceVector(x,INTSXP) does (e.g., https://github.com/wch/r-source/blob/dcce8baeaa14a527be1b7b688e0f44eb9f7022f7/src/main/coerce.c#L130).

On most systems, casting NaN to int will give INT_MIN, which is used by R as NA_INTEGER, so there won't be a problem. On macos arm64, casting NaN to int will give 0, so an NA in the integer data types will be converted to 0, which can cause issues in some use cases (e.g., fishfollower/SAM#77).

#### Reproducible Steps:

I have an example here: https://github.com/calbertsen/testIntNA/blob/main/testIntNA/src/test.cpp
Results on different systems can be seen here: https://github.com/r-universe/calbertsen/actions/runs/11178884689/job/31077572290#step:5:330

#### Current Output:

NA from R is converted to 0 on macos arm64 for integer data types

#### Expected Output:

NA from R is NA_INTEGER on the C++ side.

With, e.g., these modification, I get the expected output: https://github.com/calbertsen/adcomp/commit/a32b2e9adc5853c81d9606bf1faaa3154bce530e

#### TMB Version:

1.9.15

#### R Version:

4.4.1

#### Operating System:

aarch64-apple-darwin20

**Comment by kaskr** [comment]
Thanks @calbertsen for the thorough report!
