### ISSUE TITLE
Best practices for distributing TMB and R code

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#43]
Hi all,

I'm starting to plan projects where I'd like to distribute models using TMB code as stand-alone, encapsulated functions in R (i.e. index standardization, growth analysis, etc.).

I imagine that CRAN will not accept packages using TMB (because TMB isn't in CRAN), but could imagine using R-forge for cross-platform (at least windows and linux) package builds:
1.  Is there any better option I'm missing?  (I'd prefer not to just source functions into the R environment)
2.  Is there any tutorial on how to bundle a package to build directly out of GitHub (as TMB itself does)?

Jim

**Comment by mebrooks** [comment]
I dug around and it seems that the steps we took for glmmTMB are to put these lines in the Makefile to compile the cpp file
```
R=R
PACKAGE=glmmTMB
$(PACKAGE)/src/glmmTMB.so: $(PACKAGE)/src/glmmTMB.cpp
	cd $(PACKAGE)/src; echo "library(TMB); compile('glmmTMB.cpp','-O0 -g')" | $(R) --slave
```
and this line in the NAMESPACE to load the compiled code
```
useDynLib(glmmTMB)
```
Does that look right? These steps seemed to work for the other package I'm working on. I just want to document them for reference.

**Comment by bbolker** [comment]
I'm guessing that you don't even need the Makefile if you aren't trying to specify non-standard compilation flags.  It would probably be better (in general) to use a Makevars file - see [the relevant section in the R Extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars) ; you could probably just set  `PKG_CXXFLAGS="-O0 -g"` in this case.  (These are good settings for debugging, not for production ...)

**Comment by kaskr** [comment]
I have updated wiki under "development" with comments from @mebrooks and @bbolker .

**Comment by mebrooks** [comment]
Looks good. Thanks!

**Comment by mebrooks** [comment]
Is it possible to use two `.cpp` files in the same package?  When I run make install, I'm getting many duplicate symbol errors about the `.o` files. Here's the first one
```
duplicate symbol __ZN5CppAD18traceforward0sweepEi in:
    randwalk.o
    randwalk2.o
```

**Comment by mebrooks** [comment]
Playing around with this a bit more, it seems that the `.cpp` file *must* have the same name as the package. Before I had the impression that this was just a suggestion. So that answers my question about multiple `.cpp` files.

**Comment by alko989** [comment]
I have an R [package](https://github.com/alko989/s6model/tree/poormansts) with three different `.cpp` files, only one of them has the name of the package, but even that it is not necessary. For compilation I use a Makefile in the src folder with:

```
all: calcFmsy.so s6model.so s6modelts.so

calcFmsy.so: calcFmsy.cpp
	Rscript --vanilla -e "TMB::compile('calcFmsy.cpp')"

s6model.so: s6model.cpp
	Rscript --vanilla -e "TMB::compile('s6model.cpp')"

s6modelts.so: s6modelts.cpp
	Rscript --vanilla -e "TMB::compile('s6modelts.cpp')"

clean:
	rm -rf *o
```


So during installation the `compile` function from TMB compiles the three cpp files. And I use 3 `useDynLib` calls in the NAMESPACE file. To make it work for windows I have a separate makefile, Makefile.win, that is the same but instead of `.so` it has `.dll`

**Comment by alexfun** [comment]
@alko989 Can you please elaborate on what you mean when you say that you use "3 `useDynLib`" calls in the NAMESPACE file?

**Comment by alko989** [comment]
@alexfun What I meant was that my NAMESPACE file has three `useDynLib`calls  to load the three shared libraries of my package

    useDynLib(calcFmsy)
    useDynLib(s6model)
    useDynLib(s6modelts)

**Comment by alexfun** [comment]
Thanks for your reply. I had got that bit (except I am using roxygen's `@useDynLib my_dll_name` to build my namespace appropriately). What I had not understood was your comment about Makefile.win. Apparently R is smart enough to compile the files without a Makefile, so my instructions (copy and pasted from yours) were not read as I did not have .win extension.
