### ISSUE TITLE
Phases?

### ISSUE THREAD

**Issue by bchasco** [kaskr/adcomp#63]
Hello:

I feel like there was an issue about phases posted, but I can't seem to find it.  Does TMB currently have a phases feature similar to ADMB?  The fixed parameters of a gompertz equation are giving me problems.  I'd like to set each fixed parameter in a separate phase, as well as a different phase for the random effects.  I just needed to be pointed in the right direction.

Thanks,
Brandon

**Comment by johnrsibert** [comment]
The operation of phases in nmix is a bit opaque. Is more information available?
Thanks,
John

**Comment by skaug** [comment]
Hi,

There does not exist a direct equivalent of the phases in ADMB,
but it can be achieved indirectly. The key is the "map" argument
 to MakeADFun; see help(MakeADFun) in R. 

I append comments to nmix.R:
## Phase 1
map <- list(u=factor(rep(NA,data$nG)),log_sigma=factor(NA))       # Determine which factors to fix
obj <- MakeADFun(data,parameters,map=map,DLL="nmix")
opt <- nlminb(obj$par,obj$fn,obj$gr)
pl <- obj$env$parList(opt$par) ## Parameter estimate after phase 1
## Phase 2
obj <- MakeADFun(data,pl,random="u",DLL="nmix")
system.time( opt <- nlminb(obj$par,obj$fn,obj$gr) )
rep <- sdreport(obj)
rep

**Comment by johnrsibert** [comment]
I'm porting an ADMB-RE template to TMB. The `.dat` file specifies phases which are used in the declarations for each parameter in the PARAMETER_SECTION of the `.tpl` file. In response to Hans' post, I inserted the following code snippet in the R template for my model.

```R
phases=unlist(phases) # phase flag for each parameter
nap = length(phases)  # number of parameters
print(paste("number of parameters:",nap))
nphase = max(phases)  # number of phases
print(paste("number of phases",nphase))
fit.par=vector(length=nphase) # parameters estimates from each fit

for (p in 1:nphase) # loop through phases
{
   map = list() # name list of factors
   nip = 0
   for (n in 1:nap) # loop through parameters
   {
      # check phase flag for this parameter
      if ((phases[n] == -1) || (phases[n] > p))
      {
         map.entry = parameters[n]
         map = c(map,map.entry)
         nip = nip+1
	 map[[nip]]=rep(factor(NA),length(parameters[[n]]))
      }
   }
   print(paste("----------phase",p))
#  print(map)
#  build model for active parameters, omitting those in map
   if (p == 1)
   {
      obj = MakeADFun(data,parameters,map=map,random=c("U"),DLL="xssams")
   }
   else
   {
      obj = MakeADFun(data,opt.par[p-1],map=map,random=c("U"),DLL="xssams")
   }
   lower <- obj$par*0-Inf
   upper <- obj$par*0+Inf
   opt = nlminb(obj$par,obj$fn,obj$gr,lower=lower,upper=upper)
   # save parameter estimates for use in next fit
   opt.par[p] = obj$env$parList(opt$par) 
}
```

It seems a bit of a kludge, but it also seems too generate the appropriate `map` objects.

Ultimately, the model doesn't work, and it doesn't work in ADMB-RE either. But that is a different question. The whole mess can be found at https://github.com/johnrsibert/XSSA/tree/master/TMB.

**Comment by skaug** [comment]
That is useful. It is probably useful sometimes in the future to wrap
this into an R function that return the fit from the final phase.
If a certain phase fail, the function should return with an error.
"lower" and "upper" could be modified automatically for nlminb.
That would give TMB an ADMB-style interface to phases
that would be useful, not at least in a debugging stage
where one needs to easily turn off parameters by setting phase=-1.
