### ISSUE TITLE
Bounded parameters

### ISSUE THREAD

**Issue by MonHansen** [kaskr/adcomp#69]
Is there an way of implementing bounded parameters in tmb? 
In the Orange_Big  example, the parameters are bounded in the .tpl, but I am not sure how it was implemented in the R code or whether it was.

Thanks

**Comment by mebrooks** [comment]
You can bound them in whatever optimizer you choose (e.g. optim or nlminb). Unlike ADMB, the bounding isn't part of the parameter definition.

**Comment by mebrooks** [comment]
In that example, the bounds are defined on line 23 of orange_big.R
```
tid = system.time(opt<-nlminb(obj$par,obj$fn,obj$gr,lower=c(-10.0,-10,-10,-5,-5),upper=c(10.0,10,10,5.0,5.0)))
```
