### ISSUE TITLE
ofstream

### ISSUE THREAD

**Issue by MonHansen** [kaskr/adcomp#70]
We added #include <fstream> to our .cpp file to write outputs to external files. But when we tried to compile the .cpp,  It references a codevt.h in the fstream document and then gives the following error:
error: macro "length" passed 4 arguments, but takes just 1

**Comment by kaskr** [comment]
It is not common to write output to a file in TMB. use the REPORT macro instead. Example:
```
// C++
matrix<Type> a=b*c;
REPORT(a);
REPORT(b);
```

```
## R
obj <- MakeADFun(...)
obj$report()
```

**Comment by Njoselson** [comment]
Hey, I am trying to use the REPORT() macro, and it works very well for the majority of variables. However, I have a variable which prints correctly to the screen under the command
std::cout<<areacount<<std::endl; 
But when I put a REPORT(areacount) macro at the same spot, it gives seemingly random numbers.
Area Count:
"x"
"1"	1.29193028104769e-317
"2"	1.33517090637172e-317
"3"	2.12199579047121e-314
"4"	5.64009495033694e-38
"5"	2.19529496427765e-152
"6"	3.44353340195682e-86
"7"	6.588366479826e-260
"8"	1.62218074893226e+190
"9"	5.93049745072601e-38
"10"	4.66059947320211e+257
"11"	1.95930419448997e-27
"12"	3.50518950255868e-33
"13"	1.14449356419245e+243
"14"	6.96329561065964e-77
"15"	3.53605635508829e-57
"16"	2.19529496427765e-152
"17"	3.24245693361823e-86
"18"	1.5829162792474e-153
"19"	4.53575818872283e+217
"20"	1.57588661877014e-52
"21"	7.73634418346092e+226
"22"	7.07279093581086e+170
"23"	1.65813775787821e-76
"24"	4.66059946428823e+257
"25"	1.95930419448997e-27
"26"	8.23153972641237e-67
"27"	9.82142491151435e+252
"28"	1.96812909668876e-153
"29"	2.21256761236476e-52
"30"	1.39932923831569e-76
When it should just print a vector of zeros, with one element equal to 7260.

So what is the difference between REPORT() and cout that makes this difference?

**Comment by kaskr** [comment]
Is it possible to illustrate this problem with a _short_ reproducible example (in markdown so that it is easy to copy-paste)?

**Comment by Njoselson** [comment]
I am not sure how to use markdown correctly, but here is the cpp text:

```
#include <TMB.hpp>
template<class Type>
  Type objective_function<Type>::operator() (){
  DATA_IVECTOR(iarea);
  DATA_VECTOR(imacro);
  PARAMETER(A);  
  vector<Type> areacount(30) ;
      for(int i=0;i<5;i++)
      {if(imacro(i) == 2) {areacount(iarea(i)) += 1 ;}} ;   
       REPORT(areacount);
       std::cout<<areacount<<std::endl;
    Type f = Type(0);
    return f;
  }
```

And here is the R file:

```
library(TMB)
compile("Testcpp.cpp")
dyn.load(dynlib("Testcpp"))
obj<-MakeADFun(data=list(iarea = c( 2, 7, 7, 7, 7),imacro = c( 1, 2, 2, 2, 2)),parameters=list(A=1), DLL="Testcpp")
obj$report()$areacount
```

I didn't know how much I could take out, so I left an unused parameter and a zero objective function value. Also, the original dataset is 46073 points, but the problem is the same for both. The `std::cout` gives the right values, but the `obj$report()` gives random numbers. I tried it on all of the variables in the original dataset and this is the only one that it happens.  

When you create a vector with `vector<Type> X(10)` it makes a zero vector of length 10, right? It doesn't fill it with random numbers.

Thanks,
Nathaniel

**Comment by kaskr** [comment]
Memory is un-initialized in 
```
vector<Type> X(10);
```
To zero initialize add
```
X.setZero();
```
Note that std::cout formats the output. You will get the same as obj$report by
```
std::cout << std::scientific;
std::cout << X << std::endl;
```

**Comment by Njoselson** [comment]
Thanks, that worked. I haven't been zeroing the vectors after creating them.
