### ISSUE TITLE
Atomic 'D_lgamma' order not implemented.

### ISSUE THREAD

**Issue by John-R-Wallace-NOAA** [kaskr/adcomp#72]
Since D_lgamma can take a n'th order derivative:

 /\* n'th order derivative of log gamma function */
 double D_lgamma(double x, double n){
   if(n<.5)return lgammafn(x);
   else return psigamma(x,n-1.0);
 }

can lgamma be changed to pass the order to D_lgamma, something like this:

lgamma(Type x, int order){
   CppAD::vector<Type> tx(2);
   tx[0] = x;
   tx[1] = Type(0);
   return atomic::D_lgamma(tx, order)[0];
}

and then make EvalADFunObject aware that 'D_lgamma' order is now implemented.

My goal is to make obj$he() work again in a gamma TMB;nlminb model without any random components.

Currently I receive:

> obj$he()
> Error in f(x, order = 2) : Atomic 'D_lgamma' order not implemented.

FYI, switching back to lgamma_approx does fix this problem, i.e. I added:

template<class Type>
inline Type dgamma_approx(Type y, Type shape, Type scale, int give_log=0)
{
  Type logres = (shape - Type(1.0))_log(y) - y/scale - lgamma_approx(shape) - shape_log(scale);
  if(give_log)return logres; else return exp(logres);
}

to my cpp code and called dgamma_approx instead of dgamma.

Thanks,

-John Wallace

**Comment by kaskr** [comment]
This issue is now fixed on branch 'testing' for all templates using atomic functions.

**Comment by John-R-Wallace** [comment]
My atomic 'D_lgamma' error is now fixed.  Thanks!
