### ISSUE TITLE
matrix inverse methods?

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#74]
Hi all,

I have a problem involving linear algebra where, projecting forward in time t -> t+1:

Bx(t) = x(t+1)

where B is an n x n symmetric matrix, and x is an n-vector.  I'd like to project backwards in time t+1 -> t:

inv(B)x(t+1) = x(t)

where inv(B) is a matrix inverse.  Can anyone help me figure out how to do matrix inversion in TMB (i.e., compute inv(B) )?  It would be great to have documentation for the case of B being either a full matrix or a sparse matrix:

matrix<Type> B(n,n)
or 
Eigen::SparseMatrix<Type> B(n,n)

cheers,
jim

**Comment by kaskr** [comment]
Here is a quick overview.
The Eigen library offers a method to invert a matrix by LU-decomposition:
```
matrix<Type> x;
matrix<Type> y=x.inverse();
```
An atomic version of the same operation is available in TMB (uses less memory):
```
y=atomic::matinv(x);
```
In the sparse _symmetric_ case we have the LDL factorization from the Eigen library:
```
Eigen::SparseMatrix<Type> A;
matrix<Type> I(A.rows(),A.cols());
I.setIdentity();
Eigen::SimplicialLDLT< Eigen::SparseMatrix<Type> > ldlt(A);
matrix<Type> invA = ldlt.solve(I);
```
The sparse non-symmetric case should be handled by the Eigen::SparseLU. Unfortunately this factorization does not seem to work with all templated numeric types (works with 'double' but not 'ADdouble').

**Comment by James-Thorson** [comment]
Kasper, 

Thanks for this earlier response!  I now have a situation in which I have in hand the cholesky decomposition L of a covariance matrix V:
V = L * t(L)
where t() is the transpose. I'd like to cheaply compute the precision matrix P:
P = V^(-1)
This could obviously be done from V:
y=atomic::matinv(V)
but I imagine its faster using L than V.  This computation is also in invpd() but I can't follow the logic of that function.  Anyone willing to document how to compute the inverse directly from L rather than from V?

cheers,
jim

**Comment by James-Thorson** [comment]
Somewhat related to this thread -- does anyone have a working example of SVD that they can share?  I believe that JacobiSVD is appropriate for a problem I'm working on, and the code from Eigen appears to be included with TMB, but I can't seem to get it working.

**Comment by James-Thorson** [comment]
I'm re-posting this question on the TMB user group (https://groups.google.com/forum/#!forum/tmb-users) and closing it here.  Thanks @mebrooks for pointing out the user group to me!
