### ISSUE TITLE
slice of 3d array

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#75]
I need to calculate several matrices, all with the same dimension. Then the matrix I use in a calculation depends on a factor. So I would like to store them in a 3d array where the first dimension represents the factor. Is there a way to extract all elements of dimensions 2 and 3 for a fixed value of dimension 1? In ADMB this is `arr(fac)` where fac is an integer. In R this is `arr[fac, , ]`. I looked into the Eigen documentation, with no luck. It looks like 3d arrays are relatively new to Eigen.

TMB code
```
#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{
	// Data objects
	DATA_INTEGER(q);
	//Parameter objects
	PARAMETER(p);
  
	array<double> a(2,2,2); 
	a<< 1,2,3,4,5,6,7,8;
	std::cout<<"a(0) = "<< a(0)<<"\n";//returns only one number
		
	Type ans;
	return ans;
}
``` 
R code
```
library(TMB)
dat=list(q=1)
pin=list(p=1)
compile("subarray.cpp", "-g -O0")
dyn.load("subarray.so")
obj=MakeADFun(data=dat, parameters=pin, DLL="subarray")
```

**Comment by kaskr** [comment]
Have you considered using a vector of matrices?:
```
vector<matrix<Type> > v(2);
```
If you need to apply matrix operations on your matrices this is probably better than using arrays.
Back to the question. Arrays can only be sliced along the last dimension (due to the memory layout). For instance a[,,1] in R is obtained by
```
a.col(0);
```

**Comment by mebrooks** [comment]
Thanks! This solves my problem. 
In the definition, `vector<matrix<Type> > v(2);`, does the 2 refer to the size of the vector? I guess the matrices can be defined later and put in there.

If that's the case, I'm curious then, is it possible to make a vector of matrices of unequal size?

**Comment by kaskr** [comment]
Yes, 2 refers to the number of matrices. And yes, you can have matrices of unequal dimensions.

**Comment by mebrooks** [comment]
Yep, this works. Cool!
```
#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{
	// Data objects
	DATA_INTEGER(q)
	//Parameter objects
	PARAMETER(p)
  
	vector<matrix<double> > a(2);
	matrix<double> temp2(2,2);
	matrix<double> temp3(3,3);
	a(0)=temp2;
	a(1)=temp3;
	a(0)<< 1,2,3,4;
	a(1)<< 5,6,7,8,9,10,11,12,13;
	std::cout<<"a(0) =\n"<< a(0)<<"\n";
	std::cout<<"a(1) =\n"<< a(1)<<"\n";
	//std::cout<<"a = "<< a<<"\n";
	
	Type ans;
	return ans;
}
```

**Comment by brianstock** [comment]
Just a note of appreciation - this was useful to me, thank you!

In case this is useful to anyone else, I modified the above to see what `a` looks like when reported to R. It's a list of matrices, convenient.
```
#include <TMB.hpp>
template<class Type>
Type objective_function<Type>::operator() ()
{
    // Data objects
    DATA_INTEGER(q);
    DATA_IVECTOR(mat_dims);
    //Parameter objects
    PARAMETER(p);

    vector<matrix<double> > a(q);
    for(int i=0; i<q; i++){
        matrix<double> temp(mat_dims(i), mat_dims(i));
        temp.fill((double)i);
        a(i) = temp;
    }
    REPORT(a);

    Type ans;
    return ans;
}
```
R side:
```
library(TMB)
dat=list(q=3, mat_dims=c(2,4,3))
pin=list(p=1)
compile("3darray.cpp")
dyn.load("3darray.so")
obj=MakeADFun(data=dat, parameters=pin, DLL="3darray")
obj$report()$a[[1]] # get 1st matrix, 2x2
obj$report()$a[[2]] # get 2nd matrix, 4x4
obj$report()$a[[3]] # get 3rd matrix, 3x3
```

**Comment by shyunuw** [comment]
Hi.
When I compiled your above CPP file, I got error message regarding  p and ans, because p and ans were not used there.    Then I removed (turned off) p and ans, but still failed to compile the revised CPP file.  Would you mind posting another (simple) CPP?  I would greatly appreciate your help.  Cheers.

**Comment by emilylil** [comment]
I'm also playing around with a vector of matrices in TMB and ran into issues that led me to this thread. What is the suggested syntax for trying to extract a single value from one of those matrices within the vector? Based on the example from mbrooks, it would be like trying to extract a(0)(1,1) instead of the whole matrix. Do I need to always set up a temporary object though to pass anything to a?

**Comment by brianstock** [comment]
Hi Emily,

I don't remember, but you can look at how I did used this structure in [wham_v0.cpp](https://github.com/timjmiller/wham/blob/master/src/wham_v0.cpp#L200) and the [helper functions](https://github.com/timjmiller/wham/blob/master/src/helper_functions.hpp). Search for `selpars` and `selpars_re_mats`, a couple examples I see extraction of a single value, so seems like what you want to do should work.
```
selpars_re_mats(b)(y,j)
selpars_re_mats(b).matrix()(i,j-jstart)
Type a50 = selpars(b)(y,0);
```

**Comment by emilylil** [comment]
Thanks Brian! It still looks like you're having to build a temporary matrix and assign it to the 3d object. Though this is what I suspected I'd have to do, so it just confirms it.
