### ISSUE TITLE
REPORT() macro for sparse matrices

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#77]
Hi all,

I've been using sparse matrices, i.e., as passed using:

  DATA_SPARSE_MATRIX(G0);

or as generated using:

  Eigen::SparseMatrix<Type> G0(n,n);
  G0.coeffRef(0,0) = X

and this is very computationally and memory efficient.  However, the REPORT() macro doesn't appear to work for sparse matrices, and hence require converting to dense matrices for debugging purposes.  Any chance sparse matrices could be implemented in the REPORT macro?

cheers,
jim

**Comment by kaskr** [comment]
Sparse matrices can now be reported.
