### ISSUE TITLE
Extracting a slice from an array

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#78]
I'd like to extract a matrix "slice" from an array:

matrix<Type> B(n_y,n_z);
array<Type> A(n_x,n_y,n_z);
B = fun(A, ...)

where fun is the function I seek (which might take as arguments the dimension to slice, the element of that dimension, etc).  I see from previous questions that an array is implemented as a vector, so I understand that I can do this manually, and having a pre-made function will likely be inefficient depending upon what dimension I'd like to slice.  However, in some (many) cases I prioritize easy reading over computation speed.

Any thoughts on how to do this using clean and efficient code?

cheers,
jim

**Comment by kaskr** [comment]
Hi Jim,

I think you are looking for something like this:
```
template<class Type>
matrix<Type> sliceByColumn(array<Type> x, int j){
  array<Type> a = x.col(j);
  matrix<Type> m = a;
  m.resize(a.size() / a.cols(), a.cols());
  return m;
}

template<class Type>
matrix<Type> sliceByRow(array<Type> x, int i){
  array<Type> a = x.rotate(-1);
  return sliceByColumn(a, i);
}
```
It is most expensive to slice by row because an array permutation is required. If you need to slice many times by row it is better to permute the array once, then do the multiple slices by column.
