### ISSUE TITLE
Suggestion for using numbered releases that can be installed via devtools

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#80]
Hi all,

I'd like to pose a suggestion for the workflow of the TMB project.  I hope to spark some discussion of whether this idea is worth the time of developers (which is obviously valuable, and already stretched thin!).

Basically, I've been developing shared code for wide and public distribution (https://github.com/nwfsc-assess/geostatistical_delta-GLMM) that uses TMB.  I also frequently update TMB because I'm involved with small development tasks.  My shared package (which depends on TMB) recently started using considerably greater memory when calling sdreport() on a fitted model, and appears to do so even when reverting to earlier versions of my code.  One hypothesis is some change in TMB code.  I therefore would benefit if TMB generated "releases" (i.e. using the "release" tab on the main GitHub page).  These are then saved as ZIP files for later inspection, and can be downloaded directly using, e.g.,:

  devtools::install_github("nwfsc-assess/geostatistical_delta-GLMM", ref="3.0.0")

in R.  I could then document which release-version of TMB I'm using when comparing performance across models.  It would also allow me to track dependencies better in projects that use TMB.

Obviously clicking through the "release" process requires some additional time.  However, I think that it would improve back-compatibility better, as well as testing for complicated projects that use TMB.

please tell me if I can help,
jim

**Comment by kaskr** [comment]
This is a good suggestion. We should add releases from now on when new features are merged into the master branch, and maybe highlight a few points in the history.
Another efficient way to locate regressions as the one you describe is to use 'git bisect'. Instructions have been added to the wiki under 'Development'.

**Comment by alko989** [comment]
It is not exactly what you are asking maybe, but I have a function that returns the version of TMB (or any package) and if it is installed through devtools:::install_github it returns the SHA1 code of the commit.

    getVersion <- function (pkg = packageName()) 
    {
        pd <- packageDescription(pkg)
        v <- paste0(pd$Package, "_v", pd$Version)
        if (is.null(pd$GithubRef)) 
            return(v)
        else paste0(v, "@", pd$GithubSHA1)
    }
    getVersion("TMB")
    ## "TMB_v1.1@6bad48979801d164f199fd5766df4f928ce2d895"
