### ISSUE TITLE
Max Array Size

### ISSUE THREAD

**Issue by Njoselson** [kaskr/adcomp#83]
Is there no functionality for arrays larger than 4d? 
In ADMB: 
<code>6darray preference(1,2,1,2,1,2,1,2,0,20,0,20);</code>
In TMB, the same:
<code>array<Type> preference(2,2,2,2,21,21)</code>

But I get a message:
<code> error: no matching function for call to 'tmbutils::array<double>::array(int, int, int, int, int, int)'</code>

If there is no 6d array, any efficient tips on circumventing the problem?

Nathaniel

**Comment by kaskr** [comment]
Arrays up to 7d are implemented on this branch:
https://github.com/kaskr/adcomp/tree/testing

**Comment by Njoselson** [comment]
Perfect! Works perfectly.
