### ISSUE TITLE
Tracking Limit Error

### ISSUE THREAD

**Issue by Njoselson** [kaskr/adcomp#84]
Trying to interpret the following error when compiling the .cpp in TMB:
 
<code>wcrl2tmb.cpp:6:6: note: variable tracking size limit exceeded with -fvar-tracking-assignments, retrying without
wcrl2tmb.cpp: In member function 'Type objective_function<Type>::operator()() [with Type = CppAD::AD<CppAD::AD<double> >]':</code>
 
Is there a maximum size to the .cpp?

**Comment by kaskr** [comment]
No, have not seen this error before. Maybe something windows specific.
Could you post an example that demonstrates the problem?

**Comment by MonHansen** [comment]
I think that in order to get this problem the .cpp has to be super large or have many variables. So I don’t know how practical this would be.
