### ISSUE TITLE
Fitting random walk with drift model

### ISSUE THREAD

**Issue by kforeman** [kaskr/adcomp#92]
I’m wondering if anyone has any advice on how to fit a “random walk with drift” model in TMB. E.g. 

Y_t ~ N(mu_t, sigma)
mu_t = alpha + (delta * t) + eta_t
eta ~ N(0, tau)

where eta_t is a GMRF of LCAR form (-1 for neighbors, count of neighbors on the diagonal plus 1e-6 to avoid impropriety).

Is there a recommended way to enforce stationarity on the random walk (eta) so that when extrapolating/projecting out of sample mu is centered around alpha + delta * t? 

The problem is that without constraints the model is unidentified, leading to gigantic SDs on eta. In WinBUGS one would typically apply something like a sum-to-zero constraint on eta, but in TMB that seems to destroy the sparsity pattern.

I can reformulate the model using AR1 with an IID distribution for the second parameter to achieve something similar, but I'm wondering if anyone has suggestions for the RW + drift version? Thanks!

**Comment by skaug** [comment]
Hi, I am not sure I can give a simple answer to your questions, but let me try to help on a few points.
1. RW cannot be made stationary (but AR1 can as you say; TMB docs contain info). Maybe you mean "zero mean". 
2. You can turn the "1e-6" that you add to the diagonal on the precision matrix into a parameter "delta" that you can estimate. This works well in TMB.

In general I like using only proper probability distributions when I build models (delta>0 ensures this).

Hans

**Comment by kforeman** [comment]
Thanks, @skaug. 

1. I do indeed intend to say "zero mean", thanks for catching that. 
2. I hadn't thought to parameterize delta, will try that.

Using ARIMA terminology, what I'd like is an "ARIMA(0 1 0) model with constant", but I'm not sure how to implement it. Here's what I've tried:

Simulate some data in R as such:
```R
### simulate data
## model: y_{n,t} = alpha + eta_{t} + N(0,sigma)
##        eta_{t} = eta_{t-1} + beta + epsilon_{t}
##        epsilon_{t} ~ N(0,tau)
set.seed(1)
# size
N <- 10    # number of samples
T <- 50    # number of steps
# alpha (intercept)
alpha <- 10
# beta (drift)
beta <- -0.5
# epsilon (innovations) and its sd (tau)
tau <- 1.0
epsilon <- matrix(rnorm(N*T, 0, tau), nrow=N)
# eta (RW/innovations)
eta <- rep(NA, T)
for (i in seq(T)) {
    if (i == 1) eta[i] <- beta + epsilon[i]
    else eta[i] <- eta[i-1] + beta + epsilon[i]
}
# noise
sigma <- 0.4
noise <- matrix(rnorm(N*T, 0, sigma), nrow=N)
# y
y <- matrix(NA, nrow=N, ncol=T)
for (n in seq(N)) {
    for (t in seq(T)) {
        y[n,t] <- alpha + eta[t] + noise[n,t]
    }
}
# plot it
matplot(t(y), type='l')
```

Here's the corresponding TMB model:
```c
#include <TMB.hpp>

using namespace density;

template<class Type>
Type objective_function<Type>::operator() ()
{
// DATA
  DATA_MATRIX(y);
  int N = y.rows();
  int T = y.cols();

// PARAMETERS
  PARAMETER(alpha);
  PARAMETER(beta);
  PARAMETER_VECTOR(epsilon);
  PARAMETER(log_tau);
  PARAMETER(log_sigma);

// RW GMRF
  Eigen::SparseMatrix<Type> rw(T,T);
  for (size_t t1 = 0; t1 < T; t1++) {
    rw.coeffRef(t1,t1) = 1e-6; // small non-zero offset on diagonal to eliminate zero eigen vectors and ensure propriety
    for (size_t t2 = 0; t2 < T; t2++) {
      if ((t1 > t2 ? t1 - t2 : t2 - t1) == 1) {
        rw.coeffRef(t1,t2) = -1; // negative one for neighbors
        rw.coeffRef(t1,t1) += 1; // count of neighbors on diagonal
      }
    }
  }
  Type nll = SCALE(GMRF(rw), exp(log_tau))(epsilon);

// PREDICTIONS (MU)
  vector<Type> eta(T);
  vector<Type> mu(T);
  for (size_t t = 0; t < T; t++) {
    if (t == 0) eta(t) = beta + epsilon(t);
    else eta(t) = eta(t-1) + beta + epsilon(t);
    mu(t) = alpha + eta(t);
  }
  REPORT(mu);
  REPORT(eta);

// DATA LIKELIHOOD
  for (size_t t = 0; t < T; t++) {
    for (size_t n = 0; n < N; n++) {
      nll -= dnorm(y(n,t), mu(t), exp(log_sigma), true);
    }
  }
  return nll;
}
```

And then fit in R:
```R
data <- list(y=y)
init <- list(alpha=0., beta=0., epsilon=rep(0, T), log_tau=0., log_sigma=0.)

library(TMB)
TMB::compile('test_rw_drift.cpp')
dyn.load(dynlib('test_rw_drift'))

obj <- MakeADFun(data, init, random=c('epsilon'))
opt <- do.call('optim', obj)

sdreport(obj)
```

The sdreport returns:
```
               Estimate   Std. Error
alpha      9.3810908758   1.11847740
beta      -0.0001312305 152.41242266
log_tau    0.0748461970   0.11301166
log_sigma -0.8359733549   0.03347833
epsilon   -0.5137158088 152.41618197
...
epsilon    0.1328662217 152.41253074
```

So the `epsilon` terms soak up the entire trend and `beta` is effectively 0.

If I apply a a sum-to-zero constraint on `epsilon` by replacing `eta(t) = ... + epsilon(t)` with `eta(t) = ... + (epsilon(t) - epsilon.mean())` (which I believe is bad in TMB as it makes the hessian dense?) then the correct value for `beta` (~ -0.5) is found, but the std err on the `epsilon` terms is still huge.

**Comment by kaskr** [comment]
Hi Kyle,

It seems that your C++ template does not correspond correctly to your
simulation code? (in the simulation epsilon is IID but in the C++
template epsilon is RW).

I would suggest that you implement this model as a line by line
translation of the simulation code. No need for GMRFs. E.g. translate
the R code

```R
eta[i] <- eta[i-1] + beta + epsilon[i]
```

to

```c++
nll -= dnorm(eta[i], eta[i-1] + beta, tau, true);
```

using 'eta' as random effect (no need for epsilon in the template).

The model should work without sum to zero constraints. Even with
improper random effect prior, the distribution of random effects given
the data should become proper (as is the case for the TMB example
'mvrw').

Cheers,
Kasper

**Comment by kforeman** [comment]
Ah, brilliant. Thanks, @kaskr! 

I had tried several IID RW implementations before without luck so that's why I was attempting the GMRF. But I had never thought of combining the drift into its likelihood.

Works great, so I'm posting the code here for future reference and closing the issue. Thanks again, both!

```cpp
#include <TMB.hpp>

using namespace density;

template<class Type>
Type objective_function<Type>::operator() ()
{
// DATA
  DATA_MATRIX(y);
  int N = y.rows();
  int T = y.cols();

// PARAMETERS
  PARAMETER(alpha);
  PARAMETER(beta);
  PARAMETER_VECTOR(eta);
  PARAMETER(log_tau);
  PARAMETER(log_sigma);

// RW + DRIFT
  Type nll = 0;
  for (size_t t = 0; t < T; t++)
    nll -= dnorm(eta(t), beta + (t == 0 ? 0 : eta(t-1)), exp(log_tau), true);

// PREDICTIONS
  vector<Type> mu(T);
  for (size_t t = 0; t < T; t++)
    mu(t) = alpha + eta(t);
  REPORT(mu);

// DATA LIKELIHOOD
  for (size_t t = 0; t < T; t++)
    for (size_t n = 0; n < N; n++)
      nll -= dnorm(y(n,t), mu(t), exp(log_sigma), true);
  return nll;
}
```
