### ISSUE TITLE
tmb_symbolic not installed

### ISSUE THREAD

**Issue by markpayneatwork** [kaskr/adcomp#93]
Hi,

When I run the runSymbolicAnalysis() function on our cluster, I get the following warning:
"note: tmb_symbolic not installed"
Is this something I should be worried about and how should I fix it? I had the impression that running a symbolic analysis before fitting should improve the speed (substantially).

Mark

**Comment by kaskr** [comment]
Hi Mark,

For some large models ```runSymbolicAnalysis()``` improves speed substantially (have seen up to x10).
Have you tried the instructions in the README under 'Metis orderings'?

**Comment by markpayneatwork** [comment]
That explains it! Thanks! Maybe it might be good to clarify the meeting 
of "tmb_symbolic" a bit more in the warning message?

Cheers,

Mark
