### ISSUE TITLE
Example of passing and calling elements of lists in TMB

### ISSUE THREAD

**Issue by James-Thorson** [kaskr/adcomp#96]
Hi all,

I see that there's some functionality for passing lists, and calling elements of lists in TMB (i.e., in the R_inla.cpp file).  Can anyone provide examples or an explanation for how to use lists declared within TMB to simplify code (i.e, when the number of sparse matrices used in some model is equal to integer that is passed, and is therefore not built a priori into the code, etc.)?

jim

**Comment by kaskr** [comment]
Hi Jim,

I think I can give you an example of how to pass a list of sparse matrices from R.
First, make your own C++ container type to hold the list, with a specialized constructor to read in the data from R (if you want you can put it in a separate file):

```c++
#include <TMB.hpp>

using namespace Eigen;
using namespace tmbutils;

/* List of sparse matrices */
template<class Type>
struct LOSM_t : vector<SparseMatrix<Type> > {
  LOSM_t(SEXP x){  /* x = List passed from R */
    (*this).resize(LENGTH(x));
    for(int i=0; i<LENGTH(x); i++){
      SEXP sm = VECTOR_ELT(x, i);
      if(!isValidSparseMatrix(sm))
            error("Not a sparse matrix");
      (*this)(i) = asSparseMatrix<Type>(sm);
    }
  }
};
```

Then use the new container from the model template like this:
```c++
template<class Type>
Type objective_function<Type>::operator() ()
{
  // x = list of sparse matrices
  DATA_STRUCT(x, LOSM_t);
  // Get the first...
  SparseMatrix<Type> y = x(0);
}
```

Cheers,
Kasper

**Comment by dsjohnson** [comment]
How would one pass a list of arrays? I done this for vectors, e.g.,

//** Structure for list of vectors from R **//
template<class Type>
struct VECTOR_LIST : vector< vector<Type> >{
  VECTOR_LIST(SEXP x){ // Constructor
    (*this).resize(LENGTH(x));
    for(int i=0; i<LENGTH(x); i++){
      SEXP sm = VECTOR_ELT(x, i);
      (*this)(i) = asVector<Type>(sm);
    }
  }
};
But, there's no `asArray<Type>()` function to do the same thing. Is there an alternative?
