### ISSUE TITLE
random variable causes NaN

### ISSUE THREAD

**Issue by mebrooks** [kaskr/adcomp#99]
Sorry, this is not a general issue, but I've been struggling with this problem and don't know where else to ask for help. I'm fitting a model with 3 latent variable objects. Two are just vectors of random deviates like in mixed models; the other is the unobserved state variable `w`. When I only integrate over the random deviates, the objective function seems fine (i.e. is a real number), but when I integrate over the random deviates and the latent state, I get NaN for the objective function.  
`mod=MakeADFun(data=Ldat, parameters=Lpin, random=c("indiv_growth_dev", "year_growth_dev"), DLL="growth")`
versus
`mod=MakeADFun(data=Ldat, parameters=Lpin, random=c("indiv_growth_dev", "year_growth_dev", "w"), DLL="growth")`

In the latter case, the output is 
`
iter: 1  value: 21523.76 mgc: 19598.34 ustep: 0.9999 
iter: 2  value: 21523.76 mgc: 0.0003009696 ustep: 0.99995 
iter: 3  value: 21523.76 mgc: 1.258826e-08 ustep: 0.999975 
iter: 4  Error in newton(par = structure(c(2.88305506945901, 2.88305506945901,  : 
  Newton failed to find minimum.
In addition: Warning messages:
1: In updateCholesky(L, h, t) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
2: In updateCholesky(L, h) :
  Cholmod warning 'matrix not positive definite' at file ../Supernodal/t_cholmod_super_numeric.c, line 729
[1] NaN
`

I've tried different initial values for `w`. I tried outputting the 5 parts of the joint negative log likelihood (initial distribution of latent state, process model for latent state, observation model, random effect of year, random effect of individual) and they're all real numbers. 

Any ideas for what I should check next?

**Comment by skaug** [comment]
Hi, 

You can fit random=c("indiv_growth_dev", "year_growth_dev") and check that it 
really is a proper fit, in the sense of producing a covariance matrix via sdreport().
If the answer is "yes", then I would use that fit as starting values for the
random=c("indiv_growth_dev", "year_growth_dev", "w") fit. 

Hans

**Comment by mebrooks** [comment]
Hi Hans, 

Thanks for the advice. The fit with `random=c("indiv_growth_dev", "year_growth_dev")` did not converge even when I increased `control=list(eval.max=10000, iter.max=10000)`. That seemed really strange to me, so I started doubting my model. To check it, I simulated data. I found that the model gets back the right parameters if we observe all of the latent process or even if 2 out of 2000 observations are missing. However, it stops converging (acts like with the real data) if 3 observations are missing (slightly dependent on the seed). Is it possible that my state-space model is this sensitive? I checked that there is at least one observation per individual. 

Mollie

**Comment by mebrooks** [comment]
If anyone feels like taking a look, I'm more than happy to send the simulation and TMB code.

**Comment by skaug** [comment]
The general strategy is then to omit the "random" argument, fix the associated variances via "map".
(Do not change .cpp file. )
You are then in a non-statespace model, ie ordinary nonlinear optimization. If this
does not work either keep on fixig parameters via "map". This should identify the
difficulty. It may be a problem with the model formulation as you say. It 
is easy to get these types of model wrong.

Hans

**Comment by mebrooks** [comment]
Thanks Hans, I found a few combinations of fixed parameters that seem to let the model converge. I'm systematically working through the combinations to get some insight. However, I can't do `sdreport` on these models. Is that expected?
`
> sdr=sdreport(mod)
Problem with these parameter entries:
 log_year_growth_sd log_indiv_growth_sd      log_sigma_proc                   w    indiv_growth_dev 
                  1                   2                   4                   5                   9 
    year_growth_dev 
                 10 
Error in MakeADFun(obj$env$data, obj$env$parameters, type = "ADFun", ADreport = TRUE,  : 
  Only numeric matrices, vectors and arrays can be interfaced
`

**Comment by skaug** [comment]
I have not seen this before, but one thing is sure: if you follow my
recipe it is necessary that sdreport() works before you can
start turning parameters back to being random effects.

Hans

**Comment by mebrooks** [comment]
I determined that the problem occurs only for data sets where the latent state of an individual extends beyond the year of our last observation of that individual (i.e. it's fine to have observations missing in the middle of an individual's life, but not at the end). I expected that the latent state could still be estimated in this case, but would just have wider confidence intervals. Would you expect this behavior? I also tried it with a covariate on the latent state (thinking that the extra information might help) and got the same problem.

**Comment by skaug** [comment]
It should in general be no problem to let the latent process extend into the future. That
is the way to get projections with uncertainty. Of course the mechanism matters,
but if you the latent process follows an AR(1) model adding the projection bit
should be unproblematic (parameter estimates should not be affected).
Hans

**Comment by mebrooks** [comment]
I figured out the problem. The loop for the process part of the model wasn't going all the way to the end of the latent state, `w`. So the last elements of `w` were not factoring into the log-likelihood. This was fine when `w` was treated as a fixed effect (those elements stayed at their initial values), but caused problems when `w` was treated as random.
